const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
let now=0; const noop=()=>{}; const grad={addColorStop:noop};
const ctx=new Proxy({createLinearGradient:()=>({...grad}),createRadialGradient:()=>({...grad}),measureText:t=>({width:String(t).length*7}),setTransform:noop,clearRect:noop,fillRect:noop,strokeRect:noop,beginPath:noop,closePath:noop,moveTo:noop,lineTo:noop,quadraticCurveTo:noop,arc:noop,ellipse:noop,fill:noop,stroke:noop,save:noop,restore:noop,translate:noop,rotate:noop,scale:noop,setLineDash:noop,drawImage:noop,roundRect:noop,fillText:noop},{get:(o,k)=>k in o?o[k]:0,set:(o,k,v)=>(o[k]=v,true)});
const canvas={width:0,height:0,style:{},getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0}),addEventListener:noop,setPointerCapture:noop,releasePointerCapture:noop};
const sandbox={console,Math,Date,performance:{now:()=>now},requestAnimationFrame:noop,setTimeout:noop,clearTimeout:noop,innerWidth:390,innerHeight:844,devicePixelRatio:2,window:null,document:{hidden:false,addEventListener:noop}};
sandbox.window=sandbox;sandbox.window.SF={};sandbox.addEventListener=noop;vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'js/config.js'),'utf8'),sandbox);
const SF=sandbox.window.SF; const nopProxy=new Proxy({}, {get:()=>noop});
SF.ui={...nopProxy,showHud:noop,hideScreens:noop,renderGameOver:noop,flashMsg:noop,renderPause:noop,renderHud:noop};
SF.storage={saveGame:noop,loadRanking:()=>[],saveRanking:noop,loadGame:()=>null,clearGame:noop};SF.audio=nopProxy;SF.assets={getBackground:()=>null,getShip:()=>null,getEnemy:()=>null,getObstacle:()=>null};
vm.runInContext(fs.readFileSync(path.join(root,'js/game.js'),'utf8'),sandbox,{filename:'game.js'});
SF.game.init(canvas); SF.game.startNew('ECO','vanguard');
const G=SF.game.state;
G.checkpoint={sector:1,wave:4,score:0,nextLifeAt:9000}; SF.game.restartCheckpoint();
const kinds=new Set(G.enemies.filter(e=>e.role==='formation').map(e=>e.kind));
for(const k of ['sentinel','reanimator','breeder']) if(!kinds.has(k)) throw new Error('missing ecology kind '+k);
if(!G.formation.pattern || G.formation.pattern==='block') throw new Error('wave 4 should exercise a non-block formation pattern');
for(let i=0;i<420;i++){now+=16;SF.game.loop(now);}
if(G.formation.y>G.layout.maxFormationY+.01) throw new Error('ecology formation escaped mobile band');
if(G.enemyBullets.length>G.layout.enemyBulletCap) throw new Error('ecology bullet cap failed');
console.log('ECOLOGY SMOKE OK',{pattern:G.formation.pattern,kinds:[...kinds].filter(k=>['sentinel','reanimator','breeder'].includes(k)),enemies:G.enemies.length,eBul:G.enemyBullets.length});
