/**
 * NeuroExplora — evolution-data.js  v3.0
 * Cada etapa tiene su propio debate científico único
 * y datos curiosos propios (sin sección global repetida).
 */

const EVOLUTION_STAGES = [
  {
    id: 'first-vertebrates',
    number: 1,
    name: 'Primer Vertebrado',
    subtitle: 'La chispa del tubo neural',
    period: 'Hace ~520 millones de años',
    era: 'Cámbrico — Explosión de la vida',
    color: '#f43f5e',
    colorDark: '#9f1239',
    svgAsset: 'assets/brain-evo-1.svg',
    brainVolume: '< 0.1 cm³',
    animals: [
      { name: 'Pikaia',            emoji: '🪱', note: 'Primer cordado conocido — apenas una notocorda' },
      { name: 'Haikouichthys',     emoji: '🐟', note: 'Primer vertebrado (~520 Ma) — tubo neural simple' },
      { name: 'Lamprea (actual)',   emoji: '🐡', note: 'Agnato vivo — conserva el plan neural del Cámbrico' },
    ],
    structures: ['Tubo neural primitivo', 'Mielencéfalo (bulbo)', 'Mesencéfalo básico', 'Vesículas cerebrales primarias'],
    capabilities: [
      { icon: '💓', label: 'Funciones vitales mínimas',   desc: 'Respiración, circulación y balance osmótico gestionados por el tubo neural' },
      { icon: '👁️', label: 'Fotorrecepción primitiva',    desc: 'Células sensibles a la luz. La visión impulsó el desarrollo cerebral desde el inicio' },
      { icon: '⚡', label: 'Reflejos de escape',          desc: 'Respuestas involuntarias ante amenazas. Base de todos los reflejos posteriores' },
      { icon: '🌊', label: 'Detección de vibraciones',    desc: 'Línea lateral primitiva para sentir movimientos en el agua' },
    ],
    childExplanation: 'Hace 520 millones de años, un pequeño animal marino tenía apenas un tubo de neuronas donde hoy tienes tu cerebro. Era tan simple que apenas podía nadar y escapar de los depredadores. Pero era el comienzo de todo.',
    funFacts: [
      { icon: '🧬', text: 'El tubo neural embrionario humano se forma exactamente igual que en estos primeros vertebrados. En la semana 3 del embarazo, tu cerebro era un simple tubo de células — repitiendo 520 millones de años de evolución en días.' },
      { icon: '👁️', text: 'La hipótesis del "ojo del depredador" de Andrew Parker propone que la aparición del ojo en el Cámbrico desencadenó una carrera armamentística evolutiva que aceleró el desarrollo de cerebros más complejos en toda la biota marina.' },
      { icon: '🐟', text: 'Las lampreas actuales conservan un cerebro casi idéntico al de estos primeros vertebrados. Son "fósiles vivientes" neurológicos: estudiarlas permite entender el estado del cerebro hace 500 millones de años.' },
    ],
    stageCuriosities: [
      { icon: '💥', text: 'La Explosión Cámbrica (~541 Ma) produjo casi todos los grandes planes corporales en menos de 25 millones de años. Es el evento evolutivo más rápido y diverso de la historia de la vida — y el cerebro nació dentro de él.' },
      { icon: '🔬', text: 'El gen Pax6 que controla el desarrollo del ojo es idéntico en moscas, ratones y humanos. Surgió en los primeros vertebrados y ha sido conservado sin cambios fundamentales durante 500 millones de años.' },
    ],
    debate: {
      title: '¿Fueron los ojos los que crearon los cerebros?',
      content: 'Andrew Parker (Oxford, 2003) propuso en "In the Blink of an Eye" que la evolución del ojo en el Cámbrico fue el desencadenante de la explosión de vida compleja: los primeros animales con ojos podían cazar y huir, creando una presión selectiva que favoreció cerebros más complejos en todo el árbol evolutivo. La teoría es atractiva pero contestada: otros científicos señalan que la complejidad ecológica del Cámbrico se explica también por cambios en la química oceánica, el oxígeno atmosférico y la predación sin visión. El debate sigue abierto.',
      verdict: 'Hipótesis influyente — causa probable entre otras',
    },
  },
  {
    id: 'jawed-fish',
    number: 2,
    name: 'Peces con Mandíbula',
    subtitle: 'El cerebro visual y el olfativo',
    period: 'Hace ~420 millones de años',
    era: 'Silúrico-Devónico',
    color: '#f97316',
    colorDark: '#9a3412',
    svgAsset: 'assets/brain-evo-1.svg',
    brainVolume: '~0.1–1 cm³',
    animals: [
      { name: 'Placodermo',    emoji: '🦈', note: 'Primeros peces con mandíbula (~430 Ma)' },
      { name: 'Pez pulmonado', emoji: '🐠', note: 'Pariente vivo más cercano de los tetrápodos — hipocampo primitivo' },
      { name: 'Tiburón',       emoji: '🦈', note: 'Cerebro sin cambios significativos en 400 millones de años' },
    ],
    structures: ['Telencéfalo olfativo (primitivo)', 'Tectum óptico (visión)', 'Cerebelo primitivo', 'Pares craneales'],
    capabilities: [
      { icon: '👃', label: 'Olfato dominante',        desc: 'El telencéfalo surge inicialmente para procesar el olfato. Fue el primer "cerebro superior"' },
      { icon: '🎯', label: 'Visión binocular básica', desc: 'El tectum óptico integra imágenes y guía movimientos de caza' },
      { icon: '⚖️', label: 'Equilibrio refinado',     desc: 'El cerebelo primitivo coordina la natación tridimensional con mayor precisión' },
      { icon: '🔊', label: 'Audición vibratoria',     desc: 'Detección de ondas de presión — precursor del oído de los mamíferos' },
    ],
    childExplanation: '¿Sabías que el primer "cerebro" que evolucionó fue para oler, no para pensar? Los peces desarrollaron cerebro principalmente para detectar comida y peligros por el olfato. ¡El pensamiento vino mucho después!',
    funFacts: [
      { icon: '👃', text: 'El telencéfalo humano — donde piensas y sientes — surgió originalmente como un procesador de olores. Nuestra corteza cerebral es una expansión radical del antiguo bulbo olfativo de los peces.' },
      { icon: '🫁', text: 'El pez pulmonado puede sobrevivir hasta 4 años sin agua enterrado en barro. Tiene una vejiga natatoria convertida en pulmón primitivo y una región cerebral homóloga al hipocampo humano.' },
      { icon: '🦈', text: 'El tiburón blanco puede detectar una gota de sangre en 100 litros de agua. Su cerebro cambió muy poco en 400 millones de años porque el diseño ya era óptimo.' },
    ],
    stageCuriosities: [
      { icon: '🦴', text: 'La mandíbula de los vertebrados con mandíbula evolucionó a partir de los arcos branquiales (agallas) de sus ancestros. El mismo tejido que servía para respirar bajo el agua se reconvirtió en la estructura que permite morder.' },
      { icon: '🔀', text: 'Los peces cartilaginosos (tiburones, rayas) y los óseos (la mayoría de peces) divergieron hace ~420 Ma y tomaron caminos neurológicos distintos. Los tiburones apostaron por el olfato; los óseos expandieron el tectum visual. Ambas apuestas siguen siendo exitosas hoy.' },
    ],
    debate: {
      title: '¿Tenían "inteligencia" los primeros peces?',
      content: 'Durante décadas se asumió que los peces eran autómatas neurológicos sin capacidad de aprendizaje complejo. Estudios recientes (Bshary et al., 2014; Kohda et al., 2019) desafiaron esta visión: el pez limpiador (*Labroides dimidiatus*) supera el test del espejo en condiciones específicas y los peces teleósteos demuestran aprendizaje social, engaño táctico y cognición numérica básica. El debate es si estas capacidades son homólogas a las de los mamíferos o análogas — misma función, distinto origen evolutivo. La respuesta cambia cómo entendemos cuándo y dónde emergió la "inteligencia" en el árbol de la vida.',
      verdict: 'Debate abierto — la inteligencia de los peces fue subestimada',
    },
  },
  {
    id: 'tetrapod-transition',
    number: 3,
    name: 'Transición al Suelo',
    subtitle: 'El cerebro sale del agua',
    period: 'Hace ~375 millones de años',
    era: 'Devónico Tardío',
    color: '#84cc16',
    colorDark: '#3f6212',
    svgAsset: 'assets/brain-evo-1.svg',
    brainVolume: '~0.5–3 cm³',
    animals: [
      { name: 'Tiktaalik',      emoji: '🐊', note: 'Pez con aletas adaptadas para arrastrarse (~375 Ma)' },
      { name: 'Acanthostega',   emoji: '🦎', note: 'Primer tetrápodo (~365 Ma) — 8 dedos, aún acuático' },
      { name: 'Anfibio actual', emoji: '🐸', note: 'Conserva este plan cerebral básico desde hace 350 Ma' },
    ],
    structures: ['Médula espinal desarrollada', 'Cerebelo expandido', 'Telencéfalo bilobulado', 'Sistema vestibular completo'],
    capabilities: [
      { icon: '🦵', label: 'Coordinación de extremidades',  desc: 'El cerebelo se expande para gestionar el movimiento en tierra — mucho más complejo que nadar' },
      { icon: '👂', label: 'Oído aéreo primitivo',          desc: 'Los huesos de las mandíbulas de peces se transforman en los primeros huesos auditivos' },
      { icon: '🫁', label: 'Control respiratorio nuevo',    desc: 'Respirar aire requiere nuevos circuitos en el tronco encefálico' },
      { icon: '🌡️', label: 'Termorregulación conductual',  desc: 'El cerebro gestiona la búsqueda activa de calor o frío externo' },
    ],
    childExplanation: 'Hace 375 millones de años, un pez llamado Tiktaalik empezó a usar sus aletas para arrastrarse fuera del agua. Su cerebro tuvo que aprender a coordinar movimientos completamente nuevos. ¡Fue el primer paso de millones de años hacia ti!',
    funFacts: [
      { icon: '🦴', text: 'Los tres huesecillos del oído humano (martillo, yunque y estribo) son directamente homólogos a los huesos de la mandíbula de los peces. La evolución reciclió mandíbulas en oídos.' },
      { icon: '🐊', text: 'Tiktaalik fue descubierto en 2004 en el Ártico canadiense. Tenía cuello, podía mover los ojos independientemente y sus aletas pectorales tenían los mismos huesos que tu brazo: húmero, radio y cúbito.' },
      { icon: '🐸', text: 'El cerebro de un sapo actual es funcionalmente casi idéntico al de los primeros anfibios. Los anfibios llevan 350 millones de años con el mismo diseño — la evolución no "mejora" lo que ya funciona.' },
    ],
    stageCuriosities: [
      { icon: '🌊', text: 'La transición del agua al suelo no fue un evento único: ocurrió de forma independiente al menos 30 veces en distintos linajes de vertebrados a lo largo de la historia evolutiva. El suelo era un recurso sin explotar.' },
      { icon: '🧠', text: 'La gravedad terrestre impuso presiones neurológicas completamente nuevas. Mantener el equilibrio bípedo o cuadrúpedo sin el soporte del agua exigió una expansión masiva del cerebelo — que en los anfibios primitivos ya duplicó su tamaño respecto a los peces.' },
    ],
    debate: {
      title: '¿Salieron los vertebrados al suelo "empujados" o "atraídos"?',
      content: 'El debate clásico enfrenta dos hipótesis sobre la transición al suelo. La hipótesis del "empuje" propone que los primeros anfibios salieron por necesidad: estanques que se secaban durante el Devónico los obligaron a arrastrarse hacia otros cuerpos de agua. La hipótesis de la "atracción" sugiere que el suelo era un nicho sin depredadores lleno de artrópodos terrestres — una oportunidad evolutiva, no una fuga. Los estudios más recientes (Clack, 2012; Daeschler et al.) apoyan un escenario mixto: los primeros tetrápodos vivían en zonas pantanosas y probablemente usaban las extremidades primitivas para moverse entre vegetación acuática densa antes de aventurarse en tierra firme.',
      verdict: 'Hipótesis mixta — oportunidad y necesidad combinadas',
    },
  },
  {
    id: 'reptile-era',
    number: 4,
    name: 'Reptiles y Cerebro Instintivo',
    subtitle: 'El "cerebro reptiliano": ¿mito o realidad?',
    period: 'Hace ~310 millones de años',
    era: 'Carbonífero',
    color: '#ef4444',
    colorDark: '#991b1b',
    svgAsset: 'assets/brain-evo-1.svg',
    brainVolume: '~1–8 cm³',
    animals: [
      { name: 'Hylonomus',   emoji: '🦎', note: 'Primer reptil conocido (~312 Ma)' },
      { name: 'Cocodrilo',   emoji: '🐊', note: 'Cerebro casi idéntico al de sus ancestros del Triásico' },
      { name: 'Serpiente',   emoji: '🐍', note: 'Neocórtex mínimo — tronco y cerebelo dominantes' },
    ],
    structures: ['Tronco encefálico completo', 'Ganglios basales (rituales)', 'Cerebelo refinado', 'Telencéfalo aún pequeño'],
    capabilities: [
      { icon: '🏃', label: 'Conductas rituales y territoriales', desc: 'Los ganglios basales maduran: defensa de territorio y rituales de apareamiento' },
      { icon: '🌡️', label: 'Ectotermia gestionada',             desc: 'El tronco encefálico regula la termorregulación conductual con alta precisión' },
      { icon: '🥚', label: 'Cuidado mínimo de crías',           desc: 'Algunos reptiles desarrollan precursores del cuidado parental sin vínculo emocional' },
      { icon: '😐', label: 'Sin emociones complejas',           desc: 'El sistema límbico es rudimentario. Las conductas son instintivas, no emocionales' },
    ],
    childExplanation: 'Los cocodrilos llevan 200 millones de años sin cambiar mucho su cerebro porque les funciona perfectamente para lo que hacen: cazar, defenderse y reproducirse. El cerebro no evoluciona para ser "mejor en general" — solo cambia si hay presión para ello.',
    funFacts: [
      { icon: '🐊', text: 'El cocodrilo del Nilo tiene una arquitectura cerebral que apenas ha cambiado desde el Triásico. Sin embargo, estudios recientes muestran que los cocodrilos juegan y tienen cierta capacidad de aprendizaje social.' },
      { icon: '🧠', text: 'Los ganglios basales reptilianos son los mismos que hoy controlan tus hábitos, rituales y comportamientos automáticos. Cuando repites una rutina sin pensar, son tus ganglios basales trabajando.' },
      { icon: '🌡️', text: 'Un reptil a 15°C puede ser lento y vulnerable; el mismo animal a 35°C es un depredador ágil. La temperatura controla directamente la velocidad de los circuitos nerviosos.' },
    ],
    stageCuriosities: [
      { icon: '⚠️', text: 'Los reptiles incluyen a las tortugas, que tienen un origen más antiguo del que se creía. Un estudio de 2008 (Lyson et al.) sugiere que las tortugas derivan de un ancestro diápsido, no de los primeros reptiles anápsidos como se pensaba.' },
      { icon: '🐍', text: 'Las serpientes perdieron las patas hace ~100 Ma al adaptarse a la vida subterránea o acuática. Su cerebro se reorganizó drásticamente: perdieron la corteza visual de movimiento y expandieron la quimiorrecepción (el sentido de la lengua).' },
    ],
    debate: {
      title: '¿Es válida la teoría del "Cerebro Triúnico" de MacLean?',
      content: 'Paul MacLean propuso en los años 60-70 que el cerebro humano tiene tres capas evolutivas anidadas: el "complejo R" reptiliano (tronco + ganglios basales), el "sistema límbico paleomamífero" y el "neocórtex neomamífero". La teoría fue enormemente influyente en psicología, educación y divulgación. Sin embargo, la neurociencia moderna la considera una simplificación excesiva: (1) los peces ya poseen equivalentes del sistema límbico; (2) las estructuras no se "apilaron" intactas sino que co-evolucionaron y se transformaron; (3) no hay una separación limpia entre "instinto reptiliano" y "emoción mamífera". Hoy se usa como referencia histórica pedagógica — útil para introducir el tema, imprecisa como modelo anatómico.',
      verdict: 'Referencia histórica — útil pedagógicamente, superada científicamente',
    },
  },
  {
    id: 'early-mammals',
    number: 5,
    name: 'Los Primeros Mamíferos',
    subtitle: 'El nacimiento de las emociones y la memoria',
    period: 'Hace ~225 millones de años',
    era: 'Triásico Tardío',
    color: '#f59e0b',
    colorDark: '#b45309',
    svgAsset: 'assets/brain-evo-2.svg',
    brainVolume: '~1–15 cm³',
    animals: [
      { name: 'Morganucodon',  emoji: '🐀', note: 'Primer mamífero conocido (~225 Ma) — nocturno, pequeño' },
      { name: 'Ratón',         emoji: '🐭', note: 'Sistema límbico muy desarrollado y funcional' },
      { name: 'Ornitorrinco',  emoji: '🦆', note: 'Mamífero ovíparo — puente evolutivo con reptiles' },
    ],
    structures: ['Hipocampo (memoria)', 'Amígdala (emociones/miedo)', 'Hipotálamo completo', 'Corteza límbica', 'Tálamo expandido'],
    capabilities: [
      { icon: '😊', label: 'Emociones verdaderas',     desc: 'La amígdala genera respuestas afectivas genuinas. Base del vínculo madre-cría' },
      { icon: '🧠', label: 'Memoria episódica',         desc: 'El hipocampo permite recordar eventos específicos situados en tiempo y espacio' },
      { icon: '👶', label: 'Cuidado parental intenso',  desc: 'Característica exclusiva de los mamíferos: crías inmaduras que requieren cuidado prolongado' },
      { icon: '🌙', label: 'Vida nocturna y olfato',    desc: 'Los primeros mamíferos eran nocturnos — olfato y oído se refinaron dramáticamente' },
    ],
    childExplanation: 'Los primeros mamíferos eran como ratoncitos nocturnos que vivían aterrorizados por los dinosaurios. Pero tenían algo que los dinosaurios no: podían sentir miedo de verdad, recordar dónde estaba el peligro y querer a sus crías. Esas emociones les dieron ventaja para sobrevivir.',
    funFacts: [
      { icon: '🌙', text: 'Los primeros mamíferos vivieron ~160 millones de años a la sombra de los dinosaurios, principalmente nocturnos. Esta "presión nocturna" refinó el oído, el olfato y el procesamiento táctil en formas que los humanos aún conservamos.' },
      { icon: '💭', text: 'La memoria episódica del hipocampo — recordar qué pasó, dónde y cuándo — fue una ventaja evolutiva decisiva. Un animal que recuerda dónde vio al depredador ayer sobrevive más que uno que no lo recuerda.' },
      { icon: '🦆', text: 'El ornitorrinco pone huevos y tiene veneno. Su cerebro refleja la transición reptil-mamífero: tiene sistema límbico pero su neocórtex es muy pequeño. Es un "fósil viviente" de la transición.' },
    ],
    stageCuriosities: [
      { icon: '💥', text: 'La extinción masiva del Cretácico (~66 Ma) que eliminó a los dinosaurios no fue el "comienzo" de los mamíferos — ya llevaban 160 millones de años evolucionando. Fue, sin embargo, su liberación: de noche, en madrigueras, a plena luz del día.' },
      { icon: '🔥', text: 'Los mamíferos de sangre caliente (endotermos) mantienen la temperatura corporal estable con energía metabólica interna. Esto requiere un 70% más de alimento que los reptiles del mismo tamaño, pero permite actividad nocturna y en invierno — ventaja evolutiva decisiva.' },
    ],
    debate: {
      title: '¿La vida nocturna "hizo" a los mamíferos?',
      content: 'La "hipótesis del cuello de botella nocturno" (Walls, 1942; revisada por Gerkema et al., 2013) propone que los mamíferos se confinaron a la actividad nocturna durante el dominio de los dinosaurios (~230-66 Ma), y que esta presión evolutiva prolongada explica muchas características del sistema visual y nervioso de los mamíferos: baja resolución de color (muchos mamíferos son dícromos), grandes ojos con muchos bastones para visión nocturna, y una expansión del olfato y el oído. La hipótesis tiene sólido soporte fósil y molecular, aunque algunos paleontólogos señalan que varios grupos de mamíferos mesozoicos eran probablemente diurnos o crepusculares, lo que matiza el escenario de "cuello de botella" estricto.',
      verdict: 'Hipótesis bien soportada con matices importantes',
    },
  },
  {
    id: 'primate-expansion',
    number: 6,
    name: 'Primates y Neocórtex',
    subtitle: 'La expansión del pensamiento social',
    period: 'Hace ~55 millones de años',
    era: 'Eoceno',
    color: '#8b5cf6',
    colorDark: '#5b21b6',
    svgAsset: 'assets/brain-evo-3.svg',
    brainVolume: '~30–400 cm³',
    animals: [
      { name: 'Adapiformes',  emoji: '🐒', note: 'Primeros primates verdaderos (~55 Ma)' },
      { name: 'Chimpancé',    emoji: '🐒', note: '380 cm³ — herramientas, engaño, teoría de la mente básica' },
      { name: 'Gorila',       emoji: '🦍', note: '430–500 cm³ — vida social compleja, duelo, empatía' },
    ],
    structures: ['Neocórtex expandido', 'Corteza prefrontal (inicial)', 'Corteza parietal expandida', 'Surco central desarrollado', 'Circunvoluciones (gyri)'],
    capabilities: [
      { icon: '🤝', label: 'Cognición social',                    desc: 'Reconocimiento de individuos, jerarquías, alianzas y traición' },
      { icon: '🔧', label: 'Uso y fabricación de herramientas',   desc: 'Los chimpancés fabrican herramientas de ramas para pescar termitas' },
      { icon: '🪞', label: 'Auto-reconocimiento',                 desc: 'Los grandes simios se reconocen en espejos — precursor de la introspección' },
      { icon: '🎭', label: 'Teoría de la mente básica',           desc: 'Entender que otro individuo tiene creencias distintas a las propias' },
    ],
    childExplanation: '¡Los chimpancés pueden mentir! Cuando un chimpancé sabe dónde hay comida y finge no saberlo delante de otros para quedársela solo, está usando una habilidad mental muy sofisticada: imaginar lo que el otro sabe.',
    funFacts: [
      { icon: '👥', text: 'Robin Dunbar descubrió que el tamaño del neocórtex en primates predice casi perfectamente el tamaño del grupo social. Los humanos tenemos el mayor "número de Dunbar": ~150 relaciones sociales estables.' },
      { icon: '🐒', text: 'Los chimpancés superan a los humanos adultos en tareas de memoria visual a corto plazo. En un experimento icónico, los chimpancés memorizan la posición de números en pantalla más rápido que estudiantes universitarios.' },
      { icon: '🌳', text: 'La separación evolutiva entre el linaje chimpancé y el humano ocurrió hace ~6-7 millones de años. Compartimos el 98.7% del ADN. La diferencia cognitiva emerge de pequeñas modificaciones en genes reguladores.' },
    ],
    stageCuriosities: [
      { icon: '🍎', text: 'La hipótesis del "cerebro frugívoro" propone que comer fruta — que requiere reconocer cuándo está madura, recordar dónde está el árbol y competir con otros — impulsó la expansión cognitiva en primates más que la vida social. Ambas hipótesis (social y ecológica) tienen evidencia, y probablemente ambas contribuyeron.' },
      { icon: '🧬', text: 'El gen ASPM y la microcefalina, relacionados con el tamaño cerebral humano, muestran señales de selección positiva muy reciente en el linaje humano. Cambios en apenas 2-3 genes reguladores del desarrollo cortical explican gran parte de la diferencia de tamaño entre el cerebro humano y el del chimpancé.' },
    ],
    debate: {
      title: '¿Creció el cerebro por lo social o por lo ecológico?',
      content: 'Dos hipótesis rivales intentan explicar la expansión del neocórtex en primates. La "hipótesis del cerebro social" (Dunbar, 1998) propone que gestionar relaciones sociales complejas — recordar quién ayudó a quién, quién engañó a quién, prever alianzas — fue la presión selectiva principal. La "hipótesis ecológica" (Milton, 1988) señala que localizar alimentos distribuidos espacialmente y temporalmente (como fruta madura en distintos árboles en distintas estaciones) requiere memoria y planificación similares. Los datos más recientes (Shultz & Dunbar, 2010; DeCasien et al., 2017) sugieren que ambas presiones actuaron simultáneamente, con distintos pesos según el linaje de primates.',
      verdict: 'Las dos hipótesis son complementarias, no excluyentes',
    },
  },
  {
    id: 'homo-sapiens',
    number: 7,
    name: 'Homo sapiens',
    subtitle: 'El cerebro que se piensa a sí mismo',
    period: 'Hace ~300,000 años',
    era: 'Pleistoceno Tardío',
    color: '#06b6d4',
    colorDark: '#0e7490',
    svgAsset: 'assets/brain-evo-4.svg',
    brainVolume: '~1,350 cm³',
    animals: [
      { name: 'Homo habilis',   emoji: '🪨', note: '~2.5 Ma — 600 cm³, primeras herramientas Olduvayenses' },
      { name: 'Homo erectus',   emoji: '🔥', note: '~1.8 Ma — 900 cm³, fuego, migración fuera de África' },
      { name: 'Homo sapiens',   emoji: '🧑', note: '~300 Ka — 1,350 cm³, lenguaje, arte, ciencia' },
    ],
    structures: ['Corteza prefrontal hiperdesarrollada', 'Áreas de Broca y Wernicke', 'Corteza de asociación multimodal', 'Red neuronal por defecto (self)', 'Fascículo arqueado expandido'],
    capabilities: [
      { icon: '💬', label: 'Lenguaje simbólico recursivo',   desc: 'Solo los humanos usan gramática recursiva: podemos hablar de ideas sobre ideas sobre ideas' },
      { icon: '🎨', label: 'Arte y pensamiento simbólico',   desc: 'Arte rupestre desde hace 40,000 años. Capacidad de representar lo que no está presente' },
      { icon: '🔭', label: 'Metacognición y autoconciencia', desc: 'Podemos pensar sobre nuestros propios procesos mentales y preguntarnos por nuestra existencia' },
      { icon: '🌐', label: 'Cooperación simbólica masiva',   desc: 'Única especie que coopera en millones bajo ficciones compartidas: leyes, dinero, naciones' },
    ],
    childExplanation: '¡Solo los humanos se hacen preguntas como "¿quién soy?" o "¿qué pasará después de que muera?". Ningún otro animal que conozcamos puede hacer eso. Es lo que nos hace únicos: un cerebro que se observa a sí mismo.',
    funFacts: [
      { icon: '📈', text: 'En solo 3 millones de años, el cerebro humano triplicó su volumen. Es la tasa de cambio evolutivo más rápida de cualquier órgano en cualquier especie conocida.' },
      { icon: '🧬', text: 'La "Eva mitocondrial" — la antepasada femenina común de todos los humanos actuales — vivió hace ~150,000-200,000 años en África. No era la única mujer de su época, sino la única cuya línea materna sobrevivió ininterrumpida hasta hoy.' },
      { icon: '🌍', text: 'Homo sapiens alcanzó Australia hace ~65,000 años, cruzando 90 km de océano abierto. Para eso necesitaba planificar, comunicarse y cooperar a escala de grupo. Es la primera evidencia indirecta de lenguaje complejo.' },
    ],
    stageCuriosities: [
      { icon: '🍳', text: 'Richard Wrangham (Harvard) propone que cocinar los alimentos fue el factor decisivo en el crecimiento cerebral humano. Cocinar aumenta 3-4x las calorías extraíbles de los alimentos, lo que permitió nutrir un cerebro que consume el 20% de la energía del cuerpo sin necesitar un aparato digestivo enorme.' },
      { icon: '👣', text: 'El Homo sapiens es la única especie que colonizó todos los continentes habitables en menos de 70,000 años — desde África hasta el extremo de América del Sur. Esta capacidad de adaptación sin cambio físico es el resultado de la cultura acumulativa, posible solo con lenguaje complejo.' },
    ],
    debate: {
      title: '¿Es el lenguaje la clave de la singularidad humana?',
      content: 'Noam Chomsky propuso que el lenguaje humano es cualitativamente único: tiene "recursividad" (estructuras incrustadas infinitamente) que ningún sistema de comunicación animal posee. Esta visión fue desafiada por Hauser, Fitch & Chomsky (2002), quienes distinguieron entre el "lenguaje en sentido amplio" (compartido con animales) y el "lenguaje en sentido estricto" (solo humano, con recursividad). Daniel Everett respondió con su estudio del Pirahã (una lengua amazónica que según él carece de recursividad), poniendo en duda incluso el carácter universal de esta característica. El debate sobre qué hace único al lenguaje humano sigue siendo uno de los más activos en lingüística cognitiva y neurociencia.',
      verdict: 'Debate vivo — el lenguaje humano sigue siendo difícil de definir',
    },
  },
];

// ── RAMA NEANDERTHAL ────────────────────────────────────────────
const BRANCH_STAGES = [
  {
    id: 'homo-erectus-branch',
    name: 'Homo erectus',
    period: '~1.8 Ma — 300 Ka',
    color: '#f59e0b',
    brainVolume: '~900 cm³',
    description: 'Primero en controlar el fuego (~1 Ma) y salir de África. Su cerebro creció rápidamente pero su corteza prefrontal era menos elaborada que la de Homo sapiens. Probable lenguaje primitivo.',
    funFact: 'Homo erectus vivió durante ~1.5 millones de años — más tiempo que cualquier otra especie del género Homo. En comparación, Homo sapiens lleva apenas 300,000 años.',
  },
  {
    id: 'neanderthal-branch',
    name: 'Homo neanderthalensis',
    period: '~400 Ka — 40 Ka',
    color: '#a78bfa',
    brainVolume: '~1,400–1,600 cm³',
    description: 'Tenía un cerebro más grande que el Homo sapiens pero con diferente organización: menor corteza prefrontal y parietal, mayor corteza visual y occipital. Enterraban a sus muertos, usaban pigmentos y fabricaban herramientas sofisticadas (Musteriense).',
    funFact: 'Los humanos no africanos llevamos entre el 1-4% de ADN neanderthal. Los neandertales no "desaparecieron" del todo: una parte de ellos vive en nosotros.',
    interbreedingNote: 'Cruzamiento confirmado con Homo sapiens en Oriente Medio hace ~50,000-60,000 años.',
  },
];
