/**
 * NeuroExplora — neuron-data.js  v2.0
 * Datos de las 7 partes de la neurona + tipos de neuronas.
 */

const NEURON_PARTS = [
  {
    id: 'dendrites',
    name: 'Dendritas',
    emoji: '🌿',
    color: '#38bdf8',
    tagline: 'Las antenas receptoras',
    description: 'Las dendritas son extensiones ramificadas del cuerpo celular que reciben señales electroquímicas de otras neuronas. Cuantas más dendritas tiene una neurona y más ramificadas están, más conexiones puede establecer. Una sola neurona puede recibir hasta 200,000 señales simultáneas a través de sus dendritas.',
    childExplanation: '¡Son como los brazos de un pulpo! Siempre extendidas buscando mensajes de otras neuronas vecinas. Cuanto más largas y ramificadas, más mensajes pueden captar al mismo tiempo.',
    funFacts: [
      { icon: '🌳', text: 'Las dendritas de las neuronas de Purkinje del cerebelo son las más ramificadas del cuerpo — parecen árboles completos con miles de ramas. Una sola puede recibir señales de hasta 200,000 neuronas distintas simultáneamente.' },
      { icon: '🏋️', text: 'El aprendizaje hace crecer nuevas ramas dendríticas. Estudiar un instrumento, hablar otro idioma o practicar deporte literalmente hace que tus dendritas se ramifiquen más. Se puede ver al microscopio el efecto de la práctica.' },
      { icon: '⚡', text: 'Las dendritas no solo reciben: también procesan señales localmente antes de enviarlas al soma. Son más inteligentes de lo que se creía — actúan como unidades de procesamiento distribuido, no simples cables.' },
    ],
  },
  {
    id: 'soma',
    name: 'Soma (Cuerpo Celular)',
    emoji: '⭕',
    color: '#4f8ef7',
    tagline: 'El centro de comando',
    description: 'El soma o cuerpo celular contiene el núcleo con el ADN de la neurona y toda la maquinaria metabólica necesaria para mantenerla viva. Integra todas las señales que llegan de las dendritas y decide si la suma total supera el umbral necesario para generar un impulso nervioso (potencial de acción).',
    childExplanation: '¡Es la central de mando de la neurona! Recibe todos los mensajes que llegan por las dendritas, los suma y decide: "¿es suficientemente importante como para reenviar esta señal?" Si sí, dispara el impulso. Es un árbitro constante.',
    funFacts: [
      { icon: '🔋', text: 'Aunque el cerebro es solo el 2% del peso corporal, consume el 20% de toda la glucosa y el oxígeno que respiras. Si el suministro de oxígeno al soma se interrumpe 5 minutos, las neuronas comienzan a morir irreversiblemente.' },
      { icon: '📏', text: 'El soma más grande del sistema nervioso humano es el de las neuronas motoras de la médula espinal. Su axón puede medir más de un metro, alcanzando los dedos del pie. Es literalmente la célula más larga del cuerpo.' },
      { icon: '🚫', text: 'Las neuronas maduras no se dividen — a diferencia de casi todas las demás células del cuerpo. Por eso las lesiones graves del sistema nervioso central son tan difíciles de recuperar. Las mismas neuronas que tienes hoy las tendrás toda la vida.' },
    ],
  },
  {
    id: 'axon-hillock',
    name: 'Cono Axónico',
    emoji: '🔺',
    color: '#60a5fa',
    tagline: 'El disparador del impulso',
    description: 'El cono axónico es la zona de transición entre el soma y el axón. Es donde se toma la decisión final de disparar o no el potencial de acción. Si la suma algebraica de todas las señales entrantes supera el umbral de aproximadamente −55 mV, aquí se genera el impulso eléctrico que viajará por el axón.',
    childExplanation: '¡Es como el gatillo de una pistola de agua! Solo dispara cuando la presión acumulada supera un nivel crítico. Si todas las señales que llegan suman suficiente fuerza, se dispara automáticamente el impulso nervioso — sin posibilidad de cancelarlo una vez iniciado.',
    funFacts: [
      { icon: '📊', text: 'El umbral de disparo es de aproximadamente −55 mV. En reposo, la neurona está a −70 mV. Cuando las señales acumuladas elevan el voltaje hasta −55 mV, se dispara el potencial de acción. Este diferencial de 15 mV es la "distancia" entre silencio y acción.' },
      { icon: '⚖️', text: 'El cono axónico suma señales excitatorias (que activan, acercan a −55 mV) e inhibitorias (que frenan, alejan de −55 mV). La neurona es literalmente un sumador analógico que decide en milisegundos.' },
      { icon: '💥', text: 'Una vez iniciado el potencial de acción en el cono axónico, es imposible detenerlo. Es una respuesta "todo o nada": o se dispara con intensidad completa o no se dispara en absoluto. No hay impulsos "a media potencia".' },
    ],
  },
  {
    id: 'axon',
    name: 'Axón',
    emoji: '⚡',
    color: '#34d399',
    tagline: 'La autopista del impulso nervioso',
    description: 'El axón es una extensión larga y delgada que conduce el potencial de acción desde el soma hasta los terminales sinápticos. Puede medir desde fracciones de milímetro hasta más de un metro en nervios que van de la médula espinal a los pies. La velocidad de conducción depende de su diámetro y de si está mielinizado.',
    childExplanation: '¡Es la autopista de la neurona! El impulso viaja por ella como un rayo. Si la autopista tiene buenas vías (mielina), el impulso va a más de 430 km/h. Sin mielina, apenas pasa de 2 km/h. ¡Una diferencia de 200 veces!',
    funFacts: [
      { icon: '📏', text: 'El axón más largo del cuerpo humano va desde la médula espinal hasta el dedo gordo del pie — más de un metro de longitud en una sola célula. Una célula tan larga que si la ampliáramos para que su soma fuera del tamaño de una pelota de tenis, el axón mediría 1.6 kilómetros.' },
      { icon: '🚀', text: 'Los axones mielinizados conducen el impulso a 70-120 m/s (más de 430 km/h). Los no mielinizados lo hacen a 0.5-2 m/s. Un axón mielinizado puede ser 240 veces más rápido que uno desnudo del mismo diámetro.' },
      { icon: '🔄', text: 'El impulso nervioso siempre viaja en una sola dirección: del soma hacia los terminales. Los canales iónicos del axón solo permiten este sentido — como válvulas de un único flujo. Esto garantiza que la información no "rebote".' },
    ],
  },
  {
    id: 'myelin',
    name: 'Vaina de Mielina',
    emoji: '🛡️',
    color: '#fbbf24',
    tagline: 'El acelerador del impulso',
    description: 'La vaina de mielina es una capa rica en lípidos que envuelve el axón en segmentos, producida por células de Schwann (sistema nervioso periférico) u oligodendrocitos (sistema nervioso central). Actúa como aislante eléctrico y acelera la conducción mediante la "conducción saltatoria" entre los nódulos de Ranvier.',
    childExplanation: '¡Es como el plástico que recubre los cables eléctricos de tu casa! Sin él, la electricidad se pierde por el camino. Con la mielina, el impulso "salta" rápidamente de nódulo en nódulo — como saltar charcos en vez de atravesar el agua centímetro a centímetro.',
    funFacts: [
      { icon: '🦠', text: 'La esclerosis múltiple es una enfermedad autoinmune donde el propio sistema inmune destruye la mielina. Sin ella, los impulsos se vuelven lentos, débiles o se pierden — causando los síntomas neurológicos característicos: visión doble, debilidad, temblores.' },
      { icon: '👶', text: 'Los bebés nacen con muy poca mielina. El proceso completo de mielinización dura hasta los 25 años, avanzando de atrás (tronco) hacia adelante (corteza prefrontal). La maduración tardía de la corteza prefrontal explica la toma de decisiones impulsiva en adolescentes.' },
      { icon: '🏃', text: 'La conducción saltatoria no solo acelera: también ahorra energía. El impulso solo se "regenera" en los nódulos de Ranvier (apenas el 1% de la superficie axónica), no en toda la longitud. Una ventaja metabólica decisiva para cerebros de alta energía.' },
    ],
  },
  {
    id: 'nodes',
    name: 'Nódulos de Ranvier',
    emoji: '🔘',
    color: '#e2e8f0',
    tagline: 'Las estaciones de amplificación',
    description: 'Los nódulos de Ranvier son pequeñas interrupciones en la vaina de mielina donde el axón queda expuesto al fluido extracelular. En estas zonas se concentran densamente los canales iónicos de sodio y potasio. El potencial de acción "salta" de nódulo a nódulo (conducción saltatoria), regenerándose y amplificándose en cada uno.',
    childExplanation: '¡Son como estaciones de carga en una autopista! El impulso salta de estación en estación. En cada parada, se recarga completamente para llegar con toda la fuerza al final. Sin estas estaciones, el impulso se iría debilitando hasta desaparecer.',
    funFacts: [
      { icon: '📐', text: 'Los nódulos están espaciados con precisión: cada 1-2 mm a lo largo del axón. Este espaciado optimiza la velocidad — demasiado juntos o demasiado separados y el impulso sería más lento. La selección natural "encontró" el espaciado óptimo.' },
      { icon: '🔬', text: 'Fueron descubiertos en 1878 por el anatomista francés Louis-Antoine Ranvier al observarlos al microscopio como pequeñas "estricturaciones" periódicas en los nervios. Tardó casi un siglo entender exactamente para qué servían.' },
      { icon: '⚡', text: 'En cada nódulo, miles de canales de sodio se abren en cascada en menos de 1 milisegundo, regenerando completamente el potencial de acción. Es una explosión electroquímica microscópica que se repite centenares de veces por segundo.' },
    ],
  },
  {
    id: 'terminals',
    name: 'Botones Sinápticos',
    emoji: '💊',
    color: '#a78bfa',
    tagline: 'Los mensajeros químicos',
    description: 'Los botones sinápticos son las terminaciones del axón donde se produce la transmisión sináptica. Cuando llega el potencial de acción, el influjo de calcio desencadena la fusión de vesículas sinápticas con la membrana, liberando neurotransmisores hacia la hendidura sináptica para activar la neurona siguiente.',
    childExplanation: '¡Son sobres que lanzan mensajes! Cuando llega el impulso, los botones liberan pequeñas bolsitas llenas de mensajes químicos (neurotransmisores). Esos mensajes cruzan la hendidura nadando y "tocan el timbre" de la neurona siguiente para activarla.',
    funFacts: [
      { icon: '🧪', text: 'Existen más de 100 neurotransmisores conocidos: dopamina (motivación/placer), serotonina (estado de ánimo), GABA (inhibición/calma), glutamato (excitación/aprendizaje), acetilcolina (movimiento/memoria), norepinefrina (alerta)... Cada uno tiene efectos distintos según el receptor al que se une.' },
      { icon: '⏱️', text: 'El proceso completo — llegada del impulso, liberación de neurotransmisores, cruce de la hendidura, unión al receptor — ocurre en 0.3-0.5 milisegundos. Es una de las reacciones bioquímicas más rápidas del organismo.' },
      { icon: '💊', text: 'La mayoría de psicofármacos actúan en la sinapsis: antidepresivos ISRS (bloquean la recaptación de serotonina), benzodiacepinas (potencian el GABA), estimulantes (liberan dopamina/norepinefrina). Toda la psiquiatría farmacológica es básicamente química sináptica.' },
    ],
  },
];

// Etapas del impulso nervioso (para la animación)
const IMPULSE_STAGES = [
  {
    id: 'dendrite-signal',
    label: 'Señal en dendritas',
    desc: 'Una señal química llega de otra neurona. Los neurotransmisores se unen a los receptores de las dendritas y generan pequeñas corrientes eléctricas que viajan hacia el soma.',
    highlight: 'dendrites',
    color: '#38bdf8',
  },
  {
    id: 'soma-integration',
    label: 'Integración en el soma',
    desc: 'El soma suma todas las señales recibidas. Si la suma supera el umbral de −55 mV en el cono axónico, se dispara el potencial de acción — una respuesta "todo o nada".',
    highlight: 'soma',
    color: '#4f8ef7',
  },
  {
    id: 'action-potential',
    label: 'Potencial de acción en el axón',
    desc: 'El impulso eléctrico viaja por el axón "saltando" de nódulo en nódulo gracias a la vaina de mielina — conducción saltatoria. Velocidad: hasta 120 m/s.',
    highlight: 'axon',
    color: '#34d399',
  },
  {
    id: 'neurotransmitter-release',
    label: 'Liberación sináptica',
    desc: 'El impulso llega a los botones sinápticos. Se libera calcio, las vesículas se fusionan y los neurotransmisores cruzan la hendidura sináptica para activar la neurona siguiente.',
    highlight: 'terminals',
    color: '#a78bfa',
  },
];

// ── TIPOS DE NEURONAS ────────────────────────────────────────────
const NEURON_TYPES = {
  structural: [
    {
      id: 'multipolar',
      name: 'Multipolares',
      badge: 'Más abundantes',
      badgeColor: '#4f8ef7',
      emoji: '✳️',
      description: 'Tienen un soma central, un axón largo y múltiples dendritas. Son el tipo más común del sistema nervioso. Incluyen las neuronas motoras, las interneuronas corticales y las células de Purkinje. La mayoría de las neuronas que imaginas cuando piensas en "una neurona" son multipolares.',
      where: 'Corteza cerebral, médula espinal, cerebelo',
      example: 'La neurona motora que mueve tu dedo, las interneuronas de la corteza',
      funFact: 'Una sola neurona de Purkinje (multipolar) del cerebelo puede recibir hasta 200,000 conexiones sinápticas distintas — más que cualquier otra célula del cuerpo.',
    },
    {
      id: 'bipolar',
      name: 'Bipolares',
      badge: 'Órganos sensoriales',
      badgeColor: '#34d399',
      emoji: '🔁',
      description: 'Tienen un soma con exactamente dos extensiones: una dendrita y un axón, en polos opuestos. Son especializadas en transmitir información sensorial desde los órganos de los sentidos hacia el sistema nervioso central.',
      where: 'Retina, oído interno, epitelio olfativo',
      example: 'Las células bipolares de la retina que transmiten señales visuales al nervio óptico',
      funFact: 'Las neuronas bipolares de la retina son las responsables directas de que puedas leer esto ahora mismo. Sin ellas, los fotorreceptores (conos y bastones) no podrían enviar sus señales al cerebro.',
    },
    {
      id: 'pseudounipolar',
      name: 'Pseudounipolares',
      badge: 'Sensación corporal',
      badgeColor: '#f97316',
      emoji: '🔀',
      description: 'Tienen un solo proceso que sale del soma y se divide en T: una rama va a la periferia (piel, músculos) y la otra al sistema nervioso central. Se llaman "pseudo" unipolares porque en el desarrollo embrionario comienzan siendo bipolares y sus dos procesos se fusionan.',
      where: 'Ganglios raquídeos (dorsal root ganglia), ganglios trigeminales',
      example: 'La neurona que detecta cuando te pinchas el dedo y transmite la señal de dolor',
      funFact: 'Cuando te quemas y sientes el dolor antes de haber visto que te quemaste, es una neurona pseudounipolar la que envió la señal directamente hacia la médula sin pasar por el cerebro primero — reflejo de retirada.',
    },
  ],
  functional: [
    {
      id: 'sensory',
      name: 'Neuronas Sensoriales',
      badge: 'Aferentes',
      badgeColor: '#38bdf8',
      emoji: '🎯',
      description: 'Llevan información desde los órganos sensoriales hacia el sistema nervioso central. Responden a estímulos externos (luz, sonido, presión, temperatura) o internos (posición articular, tensión muscular). Generalmente son neuronas pseudounipolares o bipolares.',
      example: 'Detectan calor en la piel, luz en la retina, presión al caminar',
      funFact: 'Tienes aproximadamente 10-14 millones de neuronas sensoriales. Cada cm² de piel tiene cientos de terminaciones nerviosas sensoriales especializadas en diferentes tipos de estímulos.',
    },
    {
      id: 'motor',
      name: 'Neuronas Motoras',
      badge: 'Eferentes',
      badgeColor: '#fb923c',
      emoji: '🏃',
      description: 'Llevan órdenes desde el sistema nervioso central hacia los músculos y glándulas. Son multipolares con axones muy largos. Las motoras superiores (corteza) controlan las motoras inferiores (médula), que actúan directamente sobre los músculos.',
      example: 'Ordenan a tu mano cerrarse, a tu corazón latir más rápido',
      funFact: 'La enfermedad de Lou Gehrig (ELA) destruye específicamente las neuronas motoras, dejando la sensación y el pensamiento intactos mientras el cuerpo pierde progresivamente la capacidad de moverse.',
    },
    {
      id: 'interneurons',
      name: 'Interneuronas',
      badge: 'Procesamiento interno',
      badgeColor: '#a78bfa',
      emoji: '🔗',
      description: 'Conectan neuronas entre sí dentro del sistema nervioso central. Constituyen más del 99% de las neuronas del cerebro. Forman los circuitos que procesan, integran y modulan la información entre la entrada sensorial y la salida motora.',
      example: 'Las neuronas de tu corteza que conectan percepción con decisión',
      funFact: 'El 99% de las ~86,000 millones de neuronas de tu cerebro son interneuronas. Las sensoriales y motoras que conectan con el cuerpo representan menos del 1% del total neuronal.',
    },
  ],
  specialized: [
    {
      id: 'purkinje',
      name: 'Células de Purkinje',
      badge: 'Cerebelo',
      badgeColor: '#6ee7b7',
      emoji: '🌳',
      description: 'Las neuronas más grandes y complejas del sistema nervioso. Ubicadas en la corteza cerebelosa, tienen un árbol dendrítico bidimensional extraordinariamente elaborado que puede recibir hasta 200,000 conexiones. Son la única salida de información de la corteza cerebelosa.',
      funFact: 'Una célula de Purkinje puede recibir señales de más neuronas distintas que cualquier otra célula del organismo. Son las neuronas más "sociales" del sistema nervioso.',
    },
    {
      id: 'pyramidal',
      name: 'Células Piramidales',
      badge: 'Corteza cerebral',
      badgeColor: '#fbbf24',
      emoji: '🔺',
      description: 'Neuronas multipolares con una dendrita apical larga que sube hacia la superficie cortical y múltiples dendritas basales. Son las principales neuronas de proyección de la corteza cerebral — las que envían información a otras regiones del cerebro y la médula espinal.',
      funFact: 'Las células piramidales gigantes de Betz (en la corteza motora) tienen los axones más gruesos y rápidos del sistema nervioso humano. Sus señales llegan a los músculos en menos de 30 milisegundos.',
    },
    {
      id: 'mirror',
      name: 'Neuronas Espejo',
      badge: 'Frontal / Parietal',
      badgeColor: '#f9a8d4',
      emoji: '🪞',
      description: 'Se activan tanto cuando realizas una acción como cuando observas a otro realizarla. Fueron descubiertas en macacos en los años 90 y se postula que existen en humanos. Se relacionan con la imitación, la empatía, la comprensión de intenciones y el aprendizaje social.',
      funFact: 'Giacomo Rizzolatti (Italia, 1992) descubrió las neuronas espejo accidentalmente cuando una neurona de un macaco se activó al ver a un investigador comerse un helado. Fue uno de los descubrimientos más citados de la neurociencia del siglo XX.',
    },
  ],
};
