(function(){
  const STOP=new Set(['a','al','de','del','el','la','las','lo','los','un','una','unas','unos','y','es']);
  const visits=new Map();
  function normalize(value){return String(value||'').toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zñ0-9]+/g,' ').trim();}
  function cleanDisplay(value){return String(value||'').toLocaleLowerCase('es').replace(/[.,!?¡¿;:]/g,'').trim();}
  function blank(){return {version:1,words:{},pages:{},skills:{},stories:{}};}
  function support(){const s=EmiliaStore.get();if(!s.readingSupport||typeof s.readingSupport!=='object')s.readingSupport=blank();s.readingSupport.words=s.readingSupport.words||{};s.readingSupport.pages=s.readingSupport.pages||{};s.readingSupport.skills=s.readingSupport.skills||{};s.readingSupport.stories=s.readingSupport.stories||{};return s.readingSupport;}
  function pageKey(storyId,page){return String(storyId||'story')+':'+String(page||1);}
  function ensurePage(storyId,page,skill,audioFocus){const r=support(),k=pageKey(storyId,page);if(!r.pages[k])r.pages[k]={storyId,page,skill:skill||'',audioFocus:!!audioFocus,views:0,models:0,wordHelps:0,microErrors:0,microDone:0,lastSeen:0};const p=r.pages[k];if(skill)p.skill=skill;p.audioFocus=!!audioFocus;return p;}
  function ensureStory(id){const r=support(),k=String(id||'story');if(!r.stories[k])r.stories[k]={pagesViewed:0,models:0,wordHelps:0,microIndependent:0,microAssisted:0,completed:0,lastSeen:0};return r.stories[k];}
  function ensureSkill(id){if(!id)return null;const r=support();if(!r.skills[id])r.skills[id]={signals:0,support:0,independent:0,recovered:0,errors:0,lastSeen:0};return r.skills[id];}
  function inferSkill(word,fallback){const key=normalize(word);if(!key)return fallback||'';const missions=(window.EMILIA_CONTENT&&EMILIA_CONTENT.missions)||[],defs=new Map(((window.EMILIA_CONTENT&&EMILIA_CONTENT.skills)||[]).map(x=>[x.id,x]));let candidates=[];for(const m of missions){for(const q of (m.activities||[])){const qw=normalize(q.word||''),rawSay=String(q.say||'').trim(),qs=normalize(rawSay);if(qw===key||(qs===key&&!/\s/.test(rawSay))){if(q.skill&&!candidates.includes(q.skill))candidates.push(q.skill);}}}if(fallback&&!candidates.includes(fallback))candidates.push(fallback);if(!candidates.length)return fallback||'';const score=id=>{let n=0;const def=defs.get(id);try{const m=window.EmiliaMastery&&EmiliaMastery.skill?EmiliaMastery.skill(id):null;if(m&&m.total>0)n+=120;if(def&&window.EmiliaMastery&&EmiliaMastery.prereqsMet&&EmiliaMastery.prereqsMet(def.prereqs||[]))n+=45;}catch(_){}if(/^word_/.test(id))n+=35;else if(/words|word_image/.test(id))n+=25;if(/^blend_/.test(id))n+=12;if(def&&def.group==='Palabras')n+=18;if(id===fallback)n+=8;return n;};return candidates.sort((a,b)=>score(b)-score(a))[0]||fallback||'';}
  function ensureWord(display,skill){const r=support(),key=normalize(display);if(!key)return null;if(!r.words[key])r.words[key]={display:cleanDisplay(display)||key,skill:inferSkill(display,skill),seen:0,models:0,helps:0,microIndependent:0,microAssisted:0,errors:0,reviews:0,recovered:0,lastSeen:0};const w=r.words[key];if(!w.display)w.display=cleanDisplay(display)||key;if(!w.skill)w.skill=inferSkill(display,skill);return w;}
  function uniqueWords(text){const out=[],seen=new Set();String(text||'').split(/\s+/).map(cleanDisplay).filter(Boolean).forEach(w=>{const k=normalize(w);if(k&&!seen.has(k)){seen.add(k);out.push(w);}});return out;}
  function beginPage(storyId,page,text,skill,opts={}){const now=Date.now(),p=ensurePage(storyId,page,skill,opts.audioFocus),st=ensureStory(storyId),k=pageKey(storyId,page);visits.set(k,{models:0,wordHelps:0,startedAt:now,audioFocus:!!opts.audioFocus});p.views+=1;p.lastSeen=now;st.pagesViewed+=1;st.lastSeen=now;for(const token of uniqueWords(text)){const w=ensureWord(token,skill);if(w){w.seen+=1;w.lastSeen=now;}}EmiliaStore.save();return p;}
  function notePageModel(storyId,page,text,skill,opts={}){const now=Date.now(),p=ensurePage(storyId,page,skill,opts.audioFocus),st=ensureStory(storyId),k=pageKey(storyId,page),v=visits.get(k)||{models:0,wordHelps:0,audioFocus:!!opts.audioFocus};v.models+=1;visits.set(k,v);p.models+=1;p.lastSeen=now;st.models+=1;st.lastSeen=now;const addSupport=!opts.audioFocus;for(const token of uniqueWords(text)){const w=ensureWord(token,skill);if(!w)continue;w.models+=1;w.lastSeen=now;if(addSupport){const sk=ensureSkill(w.skill||skill);if(sk){sk.signals+=1;sk.support+=.45;sk.lastSeen=now;}}}EmiliaStore.save();}
  function noteWordHelp(storyId,page,word,skill){const now=Date.now(),p=ensurePage(storyId,page,skill,false),st=ensureStory(storyId),w=ensureWord(word,skill),k=pageKey(storyId,page),v=visits.get(k)||{models:0,wordHelps:0,audioFocus:false};v.wordHelps+=1;visits.set(k,v);p.wordHelps+=1;p.lastSeen=now;st.wordHelps+=1;st.lastSeen=now;if(w){w.helps+=1;w.lastSeen=now;const sk=ensureSkill(w.skill||skill);if(sk){sk.signals+=1;sk.support+=1;sk.lastSeen=now;}}EmiliaStore.save();}
  function noteMicroMiss(storyId,page,skill,target){const now=Date.now(),p=ensurePage(storyId,page,skill,false),st=ensureStory(storyId),w=ensureWord(target,skill);p.microErrors+=1;p.lastSeen=now;if(w){w.errors+=1;w.lastSeen=now;}const sk=ensureSkill((w&&w.skill)||skill);if(sk){sk.signals+=1;sk.support+=1.6;sk.errors+=1;sk.lastSeen=now;}st.lastSeen=now;EmiliaStore.save();}
  function noteMicroComplete(storyId,page,skill,meta={}){const now=Date.now(),p=ensurePage(storyId,page,skill,!!meta.audioFocus),st=ensureStory(storyId),w=ensureWord(meta.target||'',skill),k=pageKey(storyId,page),v=visits.get(k)||{models:0,wordHelps:0,audioFocus:!!meta.audioFocus};const attempts=Number(meta.attempts||0),assisted=attempts>0||(v.wordHelps||0)>0||(!v.audioFocus&&(v.models||0)>0);p.microDone+=1;p.lastSeen=now;if(assisted)st.microAssisted+=1;else st.microIndependent+=1;st.lastSeen=now;if(w){if(assisted)w.microAssisted+=1;else w.microIndependent+=1;w.lastSeen=now;}const sk=ensureSkill((w&&w.skill)||skill);if(sk){sk.signals+=1;if(assisted)sk.support+=attempts>0?1.1:.6;else sk.independent+=1;sk.lastSeen=now;}EmiliaStore.save();return {assisted,attempts,wordHelps:v.wordHelps||0,models:v.models||0};}
  function noteStoryComplete(storyId){const st=ensureStory(storyId);st.completed+=1;st.lastSeen=Date.now();EmiliaStore.save();}
  function noteReviewResult(word,skill,ok,assisted){const now=Date.now(),w=ensureWord(word,skill),sk=ensureSkill((w&&w.skill)||skill);if(w){w.reviews+=1;if(ok&&!assisted)w.recovered+=1;else if(!ok)w.errors+=1;w.lastSeen=now;}if(sk){sk.signals+=1;if(ok&&!assisted){sk.recovered+=1;sk.independent+=1;}else if(!ok){sk.errors+=1;sk.support+=1.3;}else sk.support+=.35;sk.lastSeen=now;}EmiliaStore.save();}
  function wordNeed(row){if(!row)return 0;const raw=(row.helps||0)*2.4+(row.errors||0)*2.1+(row.microAssisted||0)*1.25+(row.models||0)*.35-(row.recovered||0)*2.4-(row.microIndependent||0)*.55;const exposure=Math.max(1,Math.min(5,row.seen||1));const age=row.lastSeen?Math.min(1.2,(Date.now()-row.lastSeen)/(1000*60*60*24*14)):0;return Math.max(0,raw/(.8+exposure*.22)+age*.12);}
  function supportWords(max=8){const rows=Object.entries(support().words).map(([key,w])=>({key,display:w.display||key,skill:w.skill||'',need:wordNeed(w),seen:w.seen||0,helps:w.helps||0,models:w.models||0,errors:w.errors||0,recovered:w.recovered||0,lastSeen:w.lastSeen||0})).filter(r=>r.display&&r.display.length>1&&!STOP.has(normalize(r.display))&&r.need>=.65);rows.sort((a,b)=>b.need-a.need||b.lastSeen-a.lastSeen);return rows.slice(0,max);}
  function weakCount(){return supportWords(20).length;}
  function skillPriority(id){const s=support().skills[id];if(!s)return 0;return Math.max(0,(s.support||0)+(s.errors||0)*.6-(s.recovered||0)*1.6-(s.independent||0)*.12);}
  function knownWordPool(){return Object.values(support().words).map(w=>({display:w.display,skill:w.skill,seen:w.seen||0})).filter(w=>w.display&&w.display.length>1&&!STOP.has(normalize(w.display))&&w.seen>0);}
  function shuffleStable(arr,seed){const out=arr.slice();for(let i=out.length-1;i>0;i--){seed=(seed*1664525+1013904223)>>>0;const j=seed%(i+1);[out[i],out[j]]=[out[j],out[i]];}return out;}
  function reviewActivities(max=2,excludeSkills=[]){const exclude=new Set(excludeSkills||[]),rows=supportWords(14).filter(r=>r.skill&&!exclude.has(r.skill)),pool=knownWordPool(),out=[],used=new Set(),session=(EmiliaStore.get().sessions||0)+1;for(const row of rows){const target=cleanDisplay(row.display);if(!target||used.has(normalize(target)))continue;const alternatives=pool.filter(x=>normalize(x.display)!==normalize(target)&&x.skill!==''&&x.seen>0).sort((a,b)=>Math.abs(a.display.length-target.length)-Math.abs(b.display.length-target.length));const chosen=[];for(const x of alternatives){const k=normalize(x.display);if(used.has(k)||chosen.some(c=>normalize(c)===k))continue;chosen.push(cleanDisplay(x.display));if(chosen.length>=2)break;}if(chosen.length<2)continue;const opts=shuffleStable([target,...chosen],session*97+target.length*31+out.length*17);out.push({id:'adaptive_read_'+normalize(target).replace(/\s+/g,'_')+'_'+session+'_'+out.length,type:'listenPick',skill:row.skill,prompt:'Escucha y encuentra la palabra',voicePrompt:`Escucha ${target}. Toca esa palabra.`,say:target,options:opts,answer:target,coach:`Escucha ${target} otra vez.`,review:true,adaptiveReading:true,sourceWord:target});used.add(normalize(target));if(out.length>=max)break;}return out;}
  function adultSummary(max=5){return supportWords(max).map(r=>({word:r.display,need:Math.round(r.need*10)/10,helps:r.helps,models:r.models,errors:r.errors,recovered:r.recovered,skill:r.skill}));}
  window.EmiliaReadingAdapt={normalize,beginPage,notePageModel,noteWordHelp,noteMicroMiss,noteMicroComplete,noteStoryComplete,noteReviewResult,supportWords,weakCount,skillPriority,reviewActivities,adultSummary,inferSkill};
})();
