const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
function runProfile(cfg){
  const store=new Map(),noop=()=>{};
  const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
  const ctx=new Proxy({measureText:t=>({width:String(t??'').length*7}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null},{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});
  function el(id){const e={id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,appendChild:noop,remove:noop,setAttribute:noop,getAttribute:()=>null,focus:noop,blur:noop,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',textContent:'',innerHTML:'',clientWidth:cfg.w,clientHeight:cfg.h,offsetWidth:cfg.w,offsetHeight:cfg.h,getBoundingClientRect:()=>({left:0,top:0,width:cfg.w,height:cfg.h,right:cfg.w,bottom:cfg.h})};if(id==='game'){e.getContext=()=>ctx;e.width=cfg.w;e.height=cfg.h;ctx.canvas=e;}return e;}
  const els=new Map(),document={getElementById:id=>{if(!els.has(id))els.set(id,el(id));return els.get(id)},querySelector:()=>el('q'),querySelectorAll:()=>[],createElement:t=>el(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:cfg.w,clientHeight:cfg.h},body:el('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,fonts:{ready:Promise.resolve()},visibilityState:'visible'};
  class ImageMock{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this._src='';}set src(v){this._src=v}get src(){return this._src}addEventListener(){}}
  class AudioMock{constructor(src=''){this.src=src;this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;}play(){return Promise.resolve()}pause(){}addEventListener(){}removeEventListener(){}load(){}}
  const visualViewport={width:cfg.w,height:cfg.h,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},userAgent:'profile-test',maxTouchPoints:cfg.coarse?5:0,hardwareConcurrency:cfg.hw,deviceMemory:cfg.mem},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
  const matchMedia=()=>({matches:!!cfg.coarse,addEventListener:noop,removeEventListener:noop});
  const w={document,visualViewport,devicePixelRatio:cfg.dpr,innerWidth:cfg.w,innerHeight:cfg.h,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia,setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:AudioMock,Image:ImageMock};w.window=w;w.self=w;w.top=w;w.parent=w;
  const sandbox={...w,window:w,self:w,globalThis:w,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:AudioMock,Image:ImageMock,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl,matchMedia,addEventListener:noop,removeEventListener:noop};
  vm.createContext(sandbox);let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');src=src.replace(/\}\)\(\);\s*$/,`window.__PROFILE_TEST={VERSION,DEVICE,PERF,effectiveDpr,performanceGovernorTick,performanceStatus,getG:()=>G};})();`);vm.runInContext(src,sandbox,{timeout:7000});
  const t=w.__PROFILE_TEST;t.getG().screen='GAME';const full=t.effectiveDpr();for(let i=0;i<100;i++)t.performanceGovernorTick(.04);const recovery=t.performanceStatus();return {name:cfg.name,device:t.DEVICE,fullDpr:full,recovery};
}
const results=[runProfile({name:'desktop-high',w:1920,h:1080,dpr:1,hw:16,mem:16,coarse:false}),runProfile({name:'tablet-mid',w:1280,h:720,dpr:2,hw:4,mem:4,coarse:false}),runProfile({name:'mobile-lite',w:844,h:390,dpr:3,hw:2,mem:2,coarse:true})];
const expected=['HIGH','MID','LITE'];const ok=results.every((r,i)=>r.device.class===expected[i]&&r.recovery.tier==='RECOVERY'&&r.recovery.effectiveDpr<r.fullDpr&&r.recovery.effectiveDpr>=.85);
console.log(JSON.stringify({ok,results},null,2));process.exit(ok?0:4);
