const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){}
function makeCtx(){const target={measureText:t=>({width:String(t??'').length*7}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(target,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}
const ctx2d=makeCtx();
function makeEl(id){const e={id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,appendChild:noop,remove:noop,setAttribute:noop,getAttribute:()=>null,focus:noop,blur:noop,click:noop,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',textContent:'',innerHTML:'',value:'',checked:false,disabled:false,clientWidth:1280,clientHeight:720,offsetWidth:1280,offsetHeight:720,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720,right:1280,bottom:720})};if(id==='game'){e.getContext=()=>ctx2d;e.width=1280;e.height=720;ctx2d.canvas=e;e.toDataURL=()=>'';}return e;}
const els=new Map(),getEl=id=>{if(!els.has(id))els.set(id,makeEl(id));return els.get(id)};
const document={getElementById:getEl,querySelector:()=>makeEl('q'),querySelectorAll:()=>[],createElement:t=>makeEl(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:makeEl('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,fonts:{ready:Promise.resolve()},visibilityState:'visible'};
class ImageMock{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this.width=1024;this.height=1024;this.onload=null;this.onerror=null;this._src='';}set src(v){this._src=v;if(this.onload)setTimeout(()=>this.onload(),0)}get src(){return this._src}addEventListener(){}}
class AudioMock{constructor(src=''){this.src=src;this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},userAgent:'node-smoke',maxTouchPoints:0,hardwareConcurrency:4,deviceMemory:4},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:2,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:()=>({matches:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:AudioMock,Image:ImageMock};windowObj.window=windowObj;windowObj.self=windowObj;windowObj.top=windowObj;windowObj.parent=windowObj;
const sandbox={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:AudioMock,Image:ImageMock,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl};sandbox.matchMedia=windowObj.matchMedia;sandbox.addEventListener=noop;sandbox.removeEventListener=noop;
vm.createContext(sandbox);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');
src=src.replace(/\}\)\(\);\s*$/,`window.__V21516_TEST={VERSION,META,G,SECTORS,BOSS_STANDARD,CH2_ARENA_PRESENTATION,CH2_BOSS_AFTERMATH,bossArenaAftermathSpec,startBossArenaAftermath,updateBossArenaAftermath,bossArenaAftermathStatus,drawBossArenaAftermath,drawBossArenaPresentation,bossDeathProfile,killBoss,hasSave,loadRun,PERF,getG:()=>G};})();`);
try{vm.runInContext(src,sandbox,{filename:'game.js',timeout:9000});}catch(e){console.error('RUNTIME_EVAL_FAIL',e.stack);process.exit(2)}
const t=windowObj.__V21516_TEST;if(!t){console.error('TEST_HOOK_MISSING');process.exit(3)}
function reset(world=11,training=false){const g=t.getG();g.screen='GAME';g.mode=training?'training':'campaign';g.sector=world;g.elapsed=10;g.particles=[];g.pickups=[];g.eBullets=[];g.enemies=[];g.obstacles=[];g.frontThreats=[];g.postBossT=0;g.postBossMax=0;g.sectorClear=false;g.bossAftermath=null;g.player=g.player||{x:240,y:360,r:18,maxHp:100,hp:100,maxShield:100,shield:100,inv:0};g.player.x=240;g.player.y=360;const sec=t.SECTORS[world-1];g.boss={x:900,y:360,r:82,hp:100,maxHp:100,phase:3,pattern:sec.pattern,name:sec.boss,family:sec.family,dead:false,dying:false,deathT:t.BOSS_STANDARD.deathDuration,deathStage:0,telegraph:'',telegraphT:0,specialT:0,chargeT:0,guardT:0,coreOpenT:0,phaseTransitionT:0,signatureAttack:null,razorBeamT:0,razorBeamWind:0};return g;}
const worlds=Object.keys(t.CH2_BOSS_AFTERMATH).map(Number);
const defsOK=worlds.length===10&&worlds[0]===11&&worlds[9]===20&&new Set(worlds.map(w=>t.CH2_BOSS_AFTERMATH[w].id)).size===10&&new Set(worlds.map(w=>t.CH2_BOSS_AFTERMATH[w].motif)).size===10;
const labelsOK=worlds.every(w=>t.CH2_BOSS_AFTERMATH[w].label&&t.CH2_BOSS_AFTERMATH[w].after&&t.CH2_BOSS_AFTERMATH[w].secondary);
let startOK=true,stageOK=true,renderOK=true,profilesOK=true;
for(const w of worlds){const g=reset(w);const a=t.startBossArenaAftermath(g.boss);startOK=startOK&&!!a&&a.world===w&&a.stage===0&&a.max>t.BOSS_STANDARD.deathDuration;const sec=t.SECTORS[w-1],dp=t.bossDeathProfile(sec);profilesOK=profilesOK&&dp.primary!==undefined&&dp.secondary!==undefined&&dp.label!=='NÚCLEO';try{t.updateBossArenaAftermath(.7);t.drawBossArenaAftermath();t.updateBossArenaAftermath(.8);t.drawBossArenaAftermath();t.updateBossArenaAftermath(1.1);t.drawBossArenaAftermath();stageOK=stageOK&&g.bossAftermath.stage>=3&&g.bossAftermath.pulses>=3;g.bossAftermath.finalized=true;g.postBossMax=8;g.postBossT=3.5;t.updateBossArenaAftermath(1.0);t.drawBossArenaAftermath();renderOK=renderOK&&true;}catch(e){renderOK=false;console.error('RENDER_FAIL_W'+w,e.stack);}}
// Arena presentation hands off to aftermath during dying without throwing.
let handoffOK=true;try{const g=reset(16);g.boss.dying=true;t.drawBossArenaPresentation();t.startBossArenaAftermath(g.boss);t.drawBossArenaAftermath();}catch(e){handoffOK=false;}
// Training remains clean: no aftermath state created.
const gt=reset(20,true);const trainingExcluded=t.startBossArenaAftermath(gt.boss)===null&&!gt.bossAftermath;
// Kill path starts the aftermath without altering enemy counts or creating combat entities.
const gk=reset(20);const enemyCount=gk.enemies.length;t.killBoss();const killStarts=!!gk.bossAftermath&&gk.boss.dying&&gk.boss.hp===0&&gk.enemies.length===enemyCount;
// Post-boss reward field turns on only after finalize flag and collection window.
gk.bossAftermath.finalized=true;gk.postBossMax=8;gk.postBossT=6;const rewardField=t.bossArenaAftermathStatus().rewardField===true;
// Performance mode is respected by draw path; smoke both FULL and RECOVERY.
let perfRender=true;try{t.PERF.tier='FULL';t.drawBossArenaAftermath();t.PERF.tier='RECOVERY';t.drawBossArenaAftermath();t.PERF.tier='FULL';}catch(e){perfRender=false;}
// v2.15.15 -> v2.15.16 save migration.
localStorage.clear();localStorage.setItem('swarm_rift_run_v21515',JSON.stringify({version:'2.15.15',mode:'campaign',runDifficulty:'normal',sector:18,wave:3,score:1717,credits:255,hp:85,shield:42,powers:{},queue:[],powerRanks:{}}));const migSeen=t.hasSave(),migLoad=t.loadRun(),migrationOK=migSeen&&migLoad&&t.getG().sector===18&&t.getG().wave===3;
const gameText=fs.readFileSync(path.join(root,'js/game.js'),'utf8'),indexText=fs.readFileSync(path.join(root,'index.html'),'utf8'),swText=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const neutralBlock=gameText.slice(gameText.indexOf('// v2.15.16 · BOSS DEATH'),gameText.indexOf('// DRAW — fondos planetarios'));
const gameplayNeutral=!/hitPlayer\(|spawnEnemy\(|damageEntity\(|ringBullets\(|spawnPickup\(/.test(neutralBlock);
const checks={version:t.VERSION==='2.15.16',worlds20:t.SECTORS.length===20,aftermathWorlds11to20:defsOK,aftermathLabels:labelsOK,distinctMotifs:defsOK,startsPerWorld:startOK,stagedCollapse:stageOK,deathColorProfilesCH2:profilesOK,renderSmoke40Calls:renderOK,arenaDeathHandoff:handoffOK,trainingExcluded,killPathStartsAftermath:killStarts,rewardField,performanceAwareRender:perfRender,gameplayNeutral,arenaPresentationPreserved:Object.keys(t.CH2_ARENA_PRESENTATION).length===10,saveMigration21515:migrationOK,indexCacheBust:indexText.includes('js/game.js?v=21516'),serviceWorkerCache:swText.includes("swarm-rift-v2.15.16"),statusProbe:gameText.includes('__SWARM_V21516_STATUS'),bossDeathAnimationPreserved:gameText.includes("if(e.dying)return 'death'"),microSwarmPreserved:gameText.includes('function spawnMicroSwarm'),riftAllyPreserved:gameText.includes('function summonRiftAlly'),lastChancePreserved:gameText.includes('function beginLastChance'),assetStreamerPreserved:gameText.includes('function streamPrepareWorld'),performanceGovernorPreserved:gameText.includes('function performanceGovernorTick'),waveChoreographerPreserved:gameText.includes('CH2_WAVE_CHOREOGRAPHY'),preBossEscalationPreserved:gameText.includes('CH2_PREBOSS_ESCALATION')};
const passed=Object.values(checks).filter(Boolean).length,total=Object.keys(checks).length,ok=passed===total;console.log(JSON.stringify({ok,summary:{passed,total},checks,status:t.bossArenaAftermathStatus()},null,2));process.exit(ok?0:4);
