const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){} function makeCtx(){const t={measureText:x=>({width:String(x??'').length*6.4}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(t,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}const ctx=makeCtx();
function el(id){return {id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,setAttribute:noop,getAttribute:()=>null,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',textContent:'',getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720,right:1280,bottom:720})};}
const els=new Map(),getEl=id=>{if(!els.has(id)){const e=el(id);if(id==='game'){e.getContext=()=>ctx;e.width=1280;e.height=720;ctx.canvas=e;}els.set(id,e);}return els.get(id)};
const document={getElementById:getEl,querySelector:()=>el('q'),querySelectorAll:()=>[],createElement:t=>el(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:el('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,visibilityState:'visible'};
class Img{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this._src='';}set src(v){this._src=v}get src(){return this._src}addEventListener(){}} class Aud{constructor(){this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},hardwareConcurrency:4,deviceMemory:4,maxTouchPoints:0},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:2,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:()=>({matches:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:Aud,Image:Img};windowObj.window=windowObj;windowObj.self=windowObj;
const sb={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:Aud,Image:Img,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Uint32Array,Intl};sb.addEventListener=noop;sb.removeEventListener=noop;vm.createContext(sb);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');src=src.replace(/\}\)\(\);\s*$/,`window.__T={VERSION,SECTORS,META,HIVE_DIRECTOR_CONFIG,HIVE_TACTICAL_IDENTITY,HIVE_ARENA_IDENTITY,HIVE_COUNTER_EVOLUTION_IDENTITY,HIVE_MICRO_SEQUENCE_IDENTITY,PERF,getG:()=>G,hiveDirectorSelfTest,hiveOrchestratorSelfTest,hiveOrchestratorState,hiveOrchestratorContext,hiveOrchestratorPermit,hiveOrchestratorCommit,hiveOrchestratorTick,hiveOrchestratorSnapshot,hiveDirectorSampleInterval,hiveStartBoss,hiveSpatialState,hiveCounterEvolutionState,hasSave,loadRun,activeSectorCount,bossIdentity,resetHive:()=>{if(G)G.hiveDirector=null;}};})();`);vm.runInContext(src,sb,{timeout:10000});const t=windowObj.__T;if(!t)throw Error('hook');
const checks={};
checks.version=t.VERSION==='2.15.27';
checks.worlds=t.activeSectorCount()===20&&t.SECTORS.length===20;
checks.schema=t.HIVE_DIRECTOR_CONFIG.schema===9&&t.HIVE_DIRECTOR_CONFIG.mode==='CONTEXTUAL_ORCHESTRATION';
checks.contextual=t.HIVE_DIRECTOR_CONFIG.orchestratorContextual===true&&t.HIVE_DIRECTOR_CONFIG.orchestratorPhaseTotalCap===5&&t.HIVE_DIRECTOR_CONFIG.orchestratorPhaseMajorCap===2;
checks.identities=Object.keys(t.HIVE_TACTICAL_IDENTITY).length===10&&Object.keys(t.HIVE_ARENA_IDENTITY).length===10&&Object.keys(t.HIVE_COUNTER_EVOLUTION_IDENTITY).length===10&&Object.keys(t.HIVE_MICRO_SEQUENCE_IDENTITY).length===10;
const hs=t.hiveDirectorSelfTest();checks.directorSelf=hs.pass&&hs.contextualOrchestration&&hs.phaseAttentionCap&&hs.gracefulRecoveryDeferral&&hs.heavyCountermeasuresShadow;
const os=t.hiveOrchestratorSelfTest();checks.orchestratorSelf=os.pass&&os.contextPass&&os.recoveryDefersVisual&&os.phaseCountTracked&&os.sampling.ordered;
// migration from v2.15.26 run
localStorage.clear();localStorage.setItem('swarm_rift_run_v21526',JSON.stringify({version:'2.15.26',mode:'campaign',runDifficulty:'normal',sector:18,wave:2,score:100,credits:50,hp:90,shield:30,powers:{},queue:[],powerRanks:{}}));checks.runMigration=t.hasSave()&&t.loadRun()&&t.getG().sector===18;
// Direct contextual gate and performance graceful degradation.
let g=t.getG();g.mode='campaign';g.sector=16;g.elapsed=30;g.player={x:180,y:250,hp:100,maxHp:100,shield:60,maxShield:100};g.boss={name:t.SECTORS[15].boss,pattern:t.SECTORS[15].pattern,hp:700,maxHp:1000,phase:2,phaseElapsed:12,entry:0,phaseTransitionT:0,signatureAttack:null,telegraphT:0,specialT:0,chargeT:0};g.hiveDirector={startedAt:10,state:'A3',confidence:.94,experience:{risk:2,coverage:.55,signatureDebt:1},spatial:{confidence:.9,read:'EVASIVE'},counterEvolution:{currentTactic:'EVASIVE',streak:4,learned:{EVASIVE:'X'},active:null},orchestrator:{budget:82,quietUntil:0,recent:[],events:[],spent:{},denied:{},commits:0,phaseCounts:{},phaseTotals:{},phaseMajors:{},lastByType:{},lastUtility:{},performanceDeferrals:0,contextDenials:0}};
t.PERF.tier='FULL';const util=t.hiveOrchestratorContext('ARENA_MORPHOLOGY');checks.utilityMeaningful=util.score>=t.HIVE_DIRECTOR_CONFIG.orchestratorMajorUtility;const c1=t.hiveOrchestratorCommit('ARENA_MORPHOLOGY',{major:true,reason:'test'});checks.commitTracks=c1&&t.hiveOrchestratorSnapshot().phaseCounts[2].ARENA_MORPHOLOGY===1;
g.elapsed+=3;t.hiveOrchestratorTick(3);const cd=t.hiveOrchestratorPermit('ARENA_MORPHOLOGY',{major:true});checks.typeCooldown=!cd.ok&&cd.reason==='type_cooldown';
t.PERF.tier='RECOVERY';g.elapsed+=8;t.hiveOrchestratorTick(8);const rec=t.hiveOrchestratorPermit('ARENA_MORPHOLOGY',{major:true});checks.recoveryDeferral=!rec.ok&&rec.reason==='performance_recovery';
// Phase attention cap independent of costs.
t.PERF.tier='FULL';const st=t.hiveOrchestratorState();st.quietUntil=0;st.phaseTotals[2]=5;st.phaseMajors[2]=1;st.lastByType={};st.recent=[];st.budget=100;const cap=t.hiveOrchestratorPermit('COUNTER_TRIAL',{major:false,skipContext:true});checks.phaseAttentionCap=!cap.ok&&cap.reason==='phase_attention_cap';
// Sampling degrades only the Director cadence.
t.PERF.tier='FULL';const full=t.hiveDirectorSampleInterval();t.PERF.tier='BALANCED';const bal=t.hiveDirectorSampleInterval();t.PERF.tier='RECOVERY';const recovery=t.hiveDirectorSampleInterval();checks.sampling=full===1&&bal>full&&recovery>bal;
// Low-value interventions are rejected even with budget; A1 recovers salience faster.
t.PERF.tier='FULL';g.hiveDirector.state='A1';g.hiveDirector.confidence=.12;g.hiveDirector.experience={risk:0,coverage:1,signatureDebt:0};g.hiveDirector.spatial={confidence:.1,read:'READING'};g.hiveDirector.counterEvolution={currentTactic:'READING',streak:0,learned:{},active:null};const low=t.hiveOrchestratorState();low.budget=100;low.quietUntil=0;low.phaseTotals={};low.phaseMajors={};low.phaseCounts={};low.lastByType={};low.recent=[];const lowPermit=t.hiveOrchestratorPermit('COUNTER_TRIAL',{major:false});checks.lowUtilityGate=!lowPermit.ok&&lowPermit.reason==='low_context_utility';low.budget=0;t.hiveOrchestratorTick(1);checks.a1RecoveryBoost=Math.abs(low.budget-(t.HIVE_DIRECTOR_CONFIG.orchestratorRecoveryPerSec*t.HIVE_DIRECTOR_CONFIG.orchestratorA1RecoveryBoost))<.001;
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
checks.cacheBust=index.includes('css/game.css?v=21527')&&index.includes('js/game.js?v=21527')&&sw.includes("swarm-rift-v2.15.27");
checks.statusHook=game.includes('__SWARM_V21527_STATUS')&&game.includes('__SWARM_HIVE_CONTEXTUAL_ORCHESTRATOR_SELFTEST');
checks.metaTelemetryMigration=game.includes("loadJSON('swarm_rift_meta_v21526'")&&game.includes("KEY_HIVE_TELEMETRY_PREV='swarm_rift_hive_telemetry_v21526'")&&game.includes("migrated?'2.15.26'");
checks.noHeavyActivation=!game.includes("wouldApply:true,resource:")&&game.includes("inactiveInterventions:['reactive_armor','symbiotic_assist','rift_disruption','rift_rebirth','extra_soft_gates']");
checks.noNetworkInHive=!/fetch\(|XMLHttpRequest|sendBeacon|WebSocket/.test(game.slice(game.indexOf('// v2.15.27 · ADAPTIVE HIVE BOSS DIRECTOR'),game.indexOf('let shopReturn=')));
checks.noStatInflation=t.HIVE_DIRECTOR_CONFIG.orchestratorCosts.ARENA_MORPHOLOGY===24&&game.includes('noHpInflation:true')&&game.includes('noDamageBoost:true')&&game.includes('noExtraProjectiles:true');
const passed=Object.values(checks).filter(Boolean).length,total=Object.keys(checks).length,ok=passed===total;console.log(JSON.stringify({ok,summary:{passed,total},checks,selftest:os},null,2));process.exit(ok?0:4);
