const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){} function makeCtx(){const t={measureText:x=>({width:String(x??'').length*6.4}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(t,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}const ctx=makeCtx();
function el(id){return {id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,setAttribute:noop,getAttribute:()=>null,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',getBoundingClientRect:()=>id==='topActions'?({left:585,top:6,width:253,height:44,right:838,bottom:50}):({left:0,top:0,width:844,height:390,right:844,bottom:390})};}
const els=new Map(),getEl=id=>{if(!els.has(id)){const e=el(id);if(id==='game'){e.getContext=()=>ctx;e.width=1280;e.height=720;ctx.canvas=e;}els.set(id,e);}return els.get(id)};
const document={getElementById:getEl,querySelector:()=>el('q'),querySelectorAll:()=>[],createElement:t=>el(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:el('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,visibilityState:'visible'};
class Img{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this._src='';}set src(v){this._src=v}get src(){return this._src}addEventListener(){}} class Aud{constructor(){this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},hardwareConcurrency:4,deviceMemory:4,maxTouchPoints:0},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:2,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:q=>({matches:q.includes('pointer:coarse')?!!windowObj.__coarse:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:Aud,Image:Img};windowObj.__coarse=false;windowObj.window=windowObj;windowObj.self=windowObj;
const sb={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:Aud,Image:Img,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl};sb.matchMedia=windowObj.matchMedia;sb.addEventListener=noop;sb.removeEventListener=noop;vm.createContext(sb);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');src=src.replace(/\}\)\(\);\s*$/,`window.__T={VERSION,SECTORS,META,getG:()=>G,setViewport:(w,h,c=false)=>{W=w;H=h;window.__coarse=c;},setSafe:(top,right,bottom,left)=>{SAFE_AREA={top,right,bottom,left};},uiProfile,compactUI,hudFocusMode,hudPriorityStatus,hudPresentationStatus,syncHudPresentation,drawHUD,drawInsect,setScreen,hasSave,loadRun,topActions,shopBtn,playerCombatBounds,actionRailExclusion,touchStartExcluded,sanitizeTouchPoint,mobileErgonomicsStatus,safeHudCenterX};})();`);vm.runInContext(src,sb,{timeout:10000});const t=windowObj.__T;if(!t)throw Error('hook');
function reset(){const g=t.getG();g.screen='GAME';g.mode='campaign';g.sector=16;g.wave=2;g.goal=40;g.kills=12;g.runDifficulty='normal';g.elapsed=10;g.score=1000;g.credits=200;g.xp=20;g.xpNext=100;g.level=5;g.powers={};g.powerQueue=[];g.maxActivePowers=6;g.maxQueuePowers=3;g.combo=0;g.preBossT=0;g.postBossT=0;g.bossWarningT=0;g.bossWarningText='';g.lastChanceT=0;g.frenzyT=0;g.familyPlay=null;g.waveObjective=null;g.riftAlly=null;g.apexT=0;g.fusionSurgeT=0;g.player={x:200,y:200,r:18,hp:72,maxHp:100,shield:40,maxShield:100,inv:0};g.boss=null;return g;}
const checks={};
reset();checks.worlds20=t.SECTORS.length===20;
t.setViewport(1280,720,false);t.setSafe(0,0,0,0);checks.desktop=t.uiProfile()==='DESKTOP'&&!t.compactUI();checks.desktopBounds=JSON.stringify(t.playerCombatBounds())===JSON.stringify({left:28,right:1252,top:44,bottom:690});
t.setViewport(844,390,true);t.setSafe(0,47,21,47);checks.mobileLandscape=t.uiProfile()==='MOBILE_LANDSCAPE'&&t.compactUI();const b=t.playerCombatBounds();checks.safeAreaBounds=b.left===73&&b.right===771&&b.top===44&&b.bottom===341;
const edge=t.sanitizeTouchPoint(843,389);checks.edgeClamp=edge.x<=b.right&&edge.y<=b.bottom&&edge.x>=b.left&&edge.y>=b.top;
const rail=t.actionRailExclusion(8);checks.actionRailValid=rail.left<rail.right&&rail.top<rail.bottom&&rail.right<=844;checks.actionRailExcluded=t.touchStartExcluded(820,20)===true;
const routed=t.sanitizeTouchPoint(820,20);checks.railRouting=!((routed.x>=rail.left&&routed.x<=rail.right)&&(routed.y>=rail.top&&routed.y<=rail.bottom));
checks.safeHudCenter=Math.abs(t.safeHudCenterX()-422)<.01;
const es=t.mobileErgonomicsStatus();checks.ergoContract=es.effectiveTapTarget===44&&es.singlePrimaryTouch&&es.secondaryTouchIgnored&&es.coalescedPointerMoves&&es.viewportDebounce&&es.directTouch;
let g=reset();t.setViewport(844,390,true);t.setSafe(0,47,21,47);checks.combatFocus=t.hudFocusMode()==='COMBAT';g.lastChanceT=4.2;checks.lastChanceHighest=t.hudFocusMode()==='LAST_CHANCE'&&t.hudPriorityStatus().text.includes('RESCATE');let drawOK=true;try{t.drawHUD();}catch(e){drawOK=false;console.error(e.stack)}checks.compactDraw=drawOK;
// migration 2.15.17 -> 2.15.18
localStorage.clear();localStorage.setItem('swarm_rift_run_v21517',JSON.stringify({version:'2.15.17',mode:'campaign',runDifficulty:'normal',sector:19,wave:3,score:1818,credits:255,hp:85,shield:42,powers:{},queue:[],powerRanks:{}}));checks.saveMigration=t.hasSave()&&t.loadRun()&&t.getG().sector===19;
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'css/game.css'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
Object.assign(checks,{version:t.VERSION==='2.15.18',statusHook:game.includes('__SWARM_V21518_STATUS'),cssBust:index.includes('css/game.css?v=21518'),jsBust:index.includes('js/game.js?v=21518'),swCache:sw.includes("swarm-rift-v2.15.18"),safeProbe:index.includes('id="safeAreaProbe"')&&css.includes('safe-area-inset-left'),touchTargetCss:css.includes('button::before')&&css.includes('inset:-4px'),secondaryGuard:game.includes('ignoredSecondary++'),coalescedInput:game.includes('getCoalescedEvents'),visibilityCancel:game.includes("resetDirectTouch('visibility')"),orientationCancel:game.includes("resetDirectTouch('orientation')"),debouncedViewport:game.includes('function stabilizeViewport'),dynamicPlayerBounds:game.includes('const bounds=playerCombatBounds()'),directTouchPreserved:css.includes('.stick-zone{display:none!important'),noDashInput:!game.includes("addEventListener('pointerdown',()=>dash"),microSwarmPreserved:game.includes('function spawnMicroSwarm'),riftAllyPreserved:game.includes('function summonRiftAlly'),lastChancePreserved:game.includes('function beginLastChance'),hudPreserved:game.includes('__SWARM_V21517_STATUS'),performancePreserved:game.includes('function performanceGovernorTick')});
const passed=Object.values(checks).filter(Boolean).length,total=Object.keys(checks).length,ok=passed===total;console.log(JSON.stringify({ok,summary:{passed,total},checks,ergonomics:es,bounds:b,rail,routed},null,2));process.exit(ok?0:4);
