const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){} function makeCtx(){const t={measureText:x=>({width:String(x??'').length*6.4}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(t,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}const ctx=makeCtx();
function el(id){return {id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,setAttribute:noop,getAttribute:()=>null,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',getBoundingClientRect:()=>id==='topActions'?({left:585,top:6,width:253,height:44,right:838,bottom:50}):({left:0,top:0,width:844,height:390,right:844,bottom:390})};}
const els=new Map(),getEl=id=>{if(!els.has(id)){const e=el(id);if(id==='game'){e.getContext=()=>ctx;e.width=1280;e.height=720;ctx.canvas=e;}els.set(id,e);}return els.get(id)};
const document={getElementById:getEl,querySelector:()=>el('q'),querySelectorAll:()=>[],createElement:t=>el(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:el('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,visibilityState:'visible'};
class Img{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this._src='';}set src(v){this._src=v}get src(){return this._src}addEventListener(){}} class Aud{constructor(){this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},hardwareConcurrency:4,deviceMemory:4,maxTouchPoints:0},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:2,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:q=>({matches:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:Aud,Image:Img};windowObj.window=windowObj;windowObj.self=windowObj;
const sb={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:Aud,Image:Img,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl};sb.matchMedia=windowObj.matchMedia;sb.addEventListener=noop;sb.removeEventListener=noop;vm.createContext(sb);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');src=src.replace(/\}\)\(\);\s*$/,`window.__T={VERSION,SECTORS,META,getG:()=>G,HIVE_DIRECTOR_MODE,HIVE_DIRECTOR,hiveTargetWindow,hiveThresholds,hiveBuildSnapshot,hiveClassify,hivePlanResponse,hiveRecordOutgoingDamage,hiveRecentDps,hiveStartBossSession,hiveUpdateBossDirector,hiveRecordIncomingDamage,hiveFinalizeBossSession,hiveDirectorStatus,hiveTelemetrySummary,hasSave,loadRun};})();`);vm.runInContext(src,sb,{timeout:10000});const t=windowObj.__T;if(!t)throw Error('hook');
function resetG(world=16){const g=t.getG();Object.assign(g,{screen:'GAME',mode:'campaign',runDifficulty:'normal',sector:world,wave:3,score:0,credits:0,elapsed:100,kills:0,goal:1,level:8,powers:{},powerQueue:[],powerRanks:{},activeCombos:{},fusionSurgeT:0,apexT:0,combo:0,waveHits:0,bullets:[],eBullets:[],pickups:[],particles:[],enemies:[],obstacles:[],frontThreats:[],powerMines:[],riftAlly:null,weaponBoostT:0,weaponBoostMult:1,bossMasteryAchieved:false,hiveDamageSamples:[],hiveBossSession:null,player:{x:100,y:100,r:17,hp:100,maxHp:100,shield:45,maxShield:45,inv:0,fire:0},boss:null});for(const k of Object.keys(t.META.upgrades))delete t.META.upgrades[k];return g;}
const checks={};
checks.version=t.VERSION==='2.15.19';checks.worlds=t.SECTORS.length===20;checks.shadow=t.HIVE_DIRECTOR_MODE==='shadow';
checks.windows=JSON.stringify(t.hiveTargetWindow(1))===JSON.stringify({min:45,max:75,tier:'EARLY'})&&t.hiveTargetWindow(8).min===55&&t.hiveTargetWindow(16).min===70&&t.hiveTargetWindow(20).max===130;
checks.sample20=t.HIVE_DIRECTOR.sampleWindow===20;checks.hysteresis=t.HIVE_DIRECTOR.hysteresis===3&&t.HIVE_DIRECTOR.stateCooldown===5;
let g=resetG(16);g.powers={twin:20,overdrive:14,tesla:18,drone:22};g.powerRanks={twin:5,overdrive:4,tesla:4,drone:3};g.activeCombos={'overdrive+twin':true};t.META.upgrades.damage=6;t.META.upgrades.rate=5;t.META.upgrades.synergy=2;t.META.upgrades.drone=2;g.boss={name:'Atlas Veil',maxHp:10000,hp:10000};const strong=t.hiveBuildSnapshot(g.boss,260);checks.powerIndexMultiInput=strong.index>100&&strong.activePowers===4&&strong.combos===1&&strong.cadence>1&&strong.projectiles>=3&&strong.critical.available===false;
const mBase={powerIndex:100,dpsRatio:1,build:{survival:1,offensiveQuality:4,shieldRatio:.8},ttk:80,initial:false};checks.A1=t.hiveClassify(mBase,16,20)==='A1';checks.A2=t.hiveClassify({...mBase,powerIndex:125,dpsRatio:1.5,ttk:38},16,20)==='A2';checks.A3=t.hiveClassify({...mBase,powerIndex:170,dpsRatio:2.2,ttk:20},16,20)==='A3';checks.A0=t.hiveClassify({...mBase,powerIndex:70,dpsRatio:.45,ttk:180,build:{...mBase.build,survival:.5}},16,20)==='A0';
const a0=t.hivePlanResponse('A0',{...mBase,dpsRatio:.4,build:{survival:.4,shieldRatio:.2,offensiveQuality:1}},16),a2=t.hivePlanResponse('A2',{...mBase,ttk:35},16),a3=t.hivePlanResponse('A3',{...mBase,ttk:18},20);checks.contextHelp=a0.action==='contextual-drop'&&a0.requiresCollection&&a0.maxPerBoss===2;checks.armorLimited=a2.damageReceived<=.88&&a2.damageReceived>=.68;checks.suppressionPlanned=!!a3.suppression&&a3.suppression.seconds>=3&&a3.suppression.seconds<=5&&a3.suppression.telegraph&&a3.suppression.avoidable;checks.rebirthPlanned=!!a3.rebirth&&a3.rebirth.once&&a3.rebirth.hpRatio>=.35&&a3.rebirth.hpRatio<=.5;
// Record 20s DPS window and start a shadow boss session.
g=resetG(20);g.elapsed=100;g.boss={name:'Apis Imperia',maxHp:12000,hp:12000,entry:0,dead:false,dying:false,phaseTransitionT:0};for(let i=81;i<=100;i++){g.elapsed=i;t.hiveRecordOutgoingDamage(180,{dead:false},'normal');}g.elapsed=100;const prior=t.hiveRecentDps('world',20,100);const hs=t.hiveStartBossSession(g.boss);checks.priorDps=prior>150&&hs.priorDps>150;checks.sessionShadow=hs.mode==='shadow'&&hs.responseHistory.length===1&&hs.supportsDelivered===0&&!hs.reactiveArmorActivated&&!hs.resurrection;
// Boss effective DPS + incoming telemetry, then finalize locally.
g.elapsed=104;for(let i=0;i<8;i++){g.elapsed=104+i*.5;t.hiveRecordOutgoingDamage(500,g.boss,'normal');g.boss.hp-=500;}t.hiveRecordIncomingDamage(37);g.elapsed=109;const live=t.hiveDirectorStatus();checks.liveTtk=live.current&&live.current.dps>0&&live.current.ttk!==null;for(let j=0;j<4;j++){g.elapsed=109+j;t.hiveUpdateBossDirector(1.01);}checks.hysteresisTransition=hs.state==='A3'&&hs.stateTimeline.some(x=>x.state==='A3')&&hs.lastPlan?.action==='boss-adaptation';const rec=t.hiveFinalizeBossSession('victory');checks.telemetry=rec&&rec.result==='victory'&&rec.playerDamageReceived===37&&rec.helpsDelivered===0&&rec.reactiveArmorActivated===false&&rec.suppressions===0&&rec.resurrection===false&&rec.shadowGuarantee.gameplayInterventionsApplied===0&&rec.shadowGuarantee.externalTransmission===false;checks.localStored=!!localStorage.getItem('swarm_rift_hive_boss_telemetry_v1')&&t.hiveTelemetrySummary().count>=1;
// migration v2.15.18 -> v2.15.19
localStorage.setItem('swarm_rift_run_v21518',JSON.stringify({version:'2.15.18',mode:'campaign',runDifficulty:'normal',sector:19,wave:3,score:1818,credits:255,hp:85,shield:42,powers:{},queue:[],powerRanks:{}}));checks.saveMigration=t.hasSave()&&t.loadRun()&&t.getG().sector===19;
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');const hiveBlock=game.split('v2.15.19 · ADAPTIVE HIVE BOSS DIRECTOR — SHADOW MODE')[1].split('// ─────────────────────────────────────────────────────────────\n// v2.14.5')[0];
Object.assign(checks,{statusHook:game.includes('__SWARM_V21519_STATUS')&&game.includes('__SWARM_HIVE_SHADOW_STATUS'),spawnHook:game.includes('hiveStartBossSession(G.boss)'),damageHook:game.includes('hiveRecordOutgoingDamage'),incomingHook:game.includes('hiveRecordIncomingDamage'),updateHook:game.includes('hiveUpdateBossDirector(dt)'),victoryHook:game.includes("hiveFinalizeBossSession('victory')"),defeatHook:game.includes("hiveFinalizeBossSession(G?.boss&&!G.boss.dead?'defeat':'run-ended')"),cssBust:index.includes('css/game.css?v=21519'),jsBust:index.includes('js/game.js?v=21519'),swCache:sw.includes("swarm-rift-v2.15.19"),noNetworkInHive:!/(fetch\(|XMLHttpRequest|sendBeacon|WebSocket)/.test(hiveBlock),noAppliedArmor:!/(dmg\s*\*=\s*hs\.|damageReceived\s*\*\s*dmg|lastPlan\.damageReceived)/.test(hiveBlock),preserveMicro:game.includes('function spawnMicroSwarm'),preserveRift:game.includes('function summonRiftAlly'),preserveLastChance:game.includes('function beginLastChance'),preserveBossRush:game.includes('function startBossRush'),preserveCommander:game.includes('function deployCommanderConvergence'),preservePwa:sw.includes('self.addEventListener')});
const passed=Object.values(checks).filter(Boolean).length,total=Object.keys(checks).length,ok=passed===total;console.log(JSON.stringify({ok,summary:{passed,total},checks,strong,prior,session:{state:hs.state,initialTtk:hs.initialTtk,predictedDps:hs.predictedDps},record:rec},null,2));process.exit(ok?0:4);
