const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){} function makeCtx(){const t={measureText:x=>({width:String(x??'').length*6.4}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(t,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}const ctx=makeCtx();
function el(id){return {id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,setAttribute:noop,getAttribute:()=>null,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720,right:1280,bottom:720})};}
const els=new Map(),getEl=id=>{if(!els.has(id)){const e=el(id);if(id==='game'){e.getContext=()=>ctx;e.width=1280;e.height=720;ctx.canvas=e;}els.set(id,e);}return els.get(id)};
const document={getElementById:getEl,querySelector:()=>el('q'),querySelectorAll:()=>[],createElement:t=>el(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:el('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,visibilityState:'visible'};
class Img{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this._src='';}set src(v){this._src=v}get src(){return this._src}addEventListener(){}} class Aud{constructor(){this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},hardwareConcurrency:4,deviceMemory:4,maxTouchPoints:0},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:2,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:q=>({matches:q.includes('pointer:coarse')?!!windowObj.__coarse:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:Aud,Image:Img};windowObj.__coarse=false;windowObj.window=windowObj;windowObj.self=windowObj;
const sb={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:Aud,Image:Img,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl};sb.matchMedia=windowObj.matchMedia;sb.addEventListener=noop;sb.removeEventListener=noop;vm.createContext(sb);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');src=src.replace(/\}\)\(\);\s*$/,`window.__T={VERSION,SECTORS,META,getG:()=>G,setViewport:(w,h,c=false)=>{W=w;H=h;window.__coarse=c;},uiProfile,compactUI,hudFocusMode,hudPriorityStatus,hudPresentationStatus,syncHudPresentation,drawHUD,drawInsect,setScreen,hasSave,loadRun,topActions,shopBtn};})();`);vm.runInContext(src,sb,{timeout:10000});const t=windowObj.__T;if(!t)throw Error('hook');
function reset(){const g=t.getG();g.screen='GAME';g.mode='campaign';g.sector=16;g.wave=2;g.goal=40;g.kills=12;g.runDifficulty='normal';g.elapsed=10;g.score=1000;g.credits=200;g.xp=20;g.xpNext=100;g.level=5;g.powers={};g.powerQueue=[];g.maxActivePowers=6;g.maxQueuePowers=3;g.combo=0;g.preBossT=0;g.postBossT=0;g.bossWarningT=0;g.bossWarningText='';g.lastChanceT=0;g.frenzyT=0;g.familyPlay=null;g.waveObjective=null;g.riftAlly=null;g.apexT=0;g.fusionSurgeT=0;g.player={x:200,y:200,r:18,hp:72,maxHp:100,shield:40,maxShield:100,inv:0};g.boss=null;return g;}
const checks={};
reset();checks.worlds20=t.SECTORS.length===20;t.setViewport(1280,720,false);checks.desktop=t.uiProfile()==='DESKTOP'&&!t.compactUI();
t.setViewport(390,844,true);checks.mobilePortrait=t.uiProfile()==='MOBILE_PORTRAIT'&&t.compactUI();
t.setViewport(844,390,true);checks.mobileLandscape=t.uiProfile()==='MOBILE_LANDSCAPE'&&t.compactUI();
t.setViewport(1180,820,true);checks.tablet=t.uiProfile()==='TABLET'&&t.compactUI();
let g=reset();t.setViewport(844,390,true);checks.combatFocus=t.hudFocusMode()==='COMBAT';g.waveObjective={status:'active',type:'priority',total:3,progress:1,maxT:10,t:2};checks.objectivePriority=t.hudFocusMode()==='OBJECTIVE';g.familyPlay={label:'VELO DE PINZA',stage:'active',adapted:true};checks.tacticalBeatsObjective=t.hudFocusMode()==='TACTICAL';g.boss={name:'ATLAS VEIL',pattern:'moth',phase:2,dead:false};checks.bossBeatsTactical=t.hudFocusMode()==='BOSS';g.preBossT=5;checks.preBossBeatsBoss=t.hudFocusMode()==='PRE_BOSS';g.preBossT=0;g.bossWarningT=1;g.bossWarningText='VELO HIPNÓTICO';checks.bossAlert=t.hudFocusMode()==='BOSS_ALERT';g.lastChanceT=4.2;checks.lastChanceHighest=t.hudFocusMode()==='LAST_CHANCE'&&t.hudPriorityStatus().text.includes('RESCATE');
let drawOK=true;try{t.drawHUD();}catch(e){drawOK=false;console.error(e.stack)}checks.compactDraw=drawOK;
t.syncHudPresentation();checks.domFocus=t.topActions.dataset.hudFocus==='LAST_CHANCE'&&document.body.dataset.hudProfile==='MOBILE_LANDSCAPE';
t.setScreen('MENU');checks.menuResetsDomFocus=t.topActions.dataset.hudFocus==='MENU';g=reset();t.setViewport(844,390,true);const hs=t.hudPresentationStatus();checks.coreVisible=hs.coreAlwaysVisible&&hs.criticalKeepsShopVisible&&hs.gameplayNeutral&&hs.mobilePowerLimit===4;
// Boss HP bar compact render smoke.
g.lastChanceT=0;g.bossWarningT=0;g.boss={name:'ATLAS VEIL',pattern:'moth',phase:2,phaseElapsed:10,hp:500,maxHp:1000,dead:false,dying:false,kind:'boss',r:70,x:650,y:180,guardT:0,coreOpenT:0,phaseTransitionT:0,entryT:0,flash:0,t:0,animAttackT:0};let bossDraw=true;try{t.drawInsect(g.boss,true);}catch(e){bossDraw=false}checks.compactBossBar=bossDraw;
// migration 2.15.16 -> 2.15.17
localStorage.clear();localStorage.setItem('swarm_rift_run_v21516',JSON.stringify({version:'2.15.16',mode:'campaign',runDifficulty:'normal',sector:19,wave:3,score:1717,credits:255,hp:85,shield:42,powers:{},queue:[],powerRanks:{}}));checks.saveMigration=t.hasSave()&&t.loadRun()&&t.getG().sector===19;
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'css/game.css'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
Object.assign(checks,{version:t.VERSION==='2.15.17',statusHook:game.includes('__SWARM_V21517_STATUS'),cssBust:index.includes('css/game.css?v=21517'),jsBust:index.includes('js/game.js?v=21517'),swCache:sw.includes("swarm-rift-v2.15.17"),criticalCss:css.includes('data-hud-focus="LAST_CHANCE"'),directTouchPreserved:css.includes('.stick-zone{display:none!important'),microSwarmPreserved:game.includes('function spawnMicroSwarm'),riftAllyPreserved:game.includes('function summonRiftAlly'),lastChancePreserved:game.includes('function beginLastChance'),aftermathPreserved:game.includes('CH2_BOSS_AFTERMATH'),performancePreserved:game.includes('function performanceGovernorTick')});
const passed=Object.values(checks).filter(Boolean).length,total=Object.keys(checks).length,ok=passed===total;console.log(JSON.stringify({ok,summary:{passed,total},checks,status:hs},null,2));process.exit(ok?0:4);
