const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){}
function makeCtx(){const target={measureText:t=>({width:String(t??'').length*7}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(target,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}
const ctx2d=makeCtx();
function makeEl(id){const e={id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,appendChild:noop,remove:noop,setAttribute:noop,getAttribute:()=>null,focus:noop,blur:noop,click:noop,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',textContent:'',innerHTML:'',value:'',checked:false,disabled:false,clientWidth:1280,clientHeight:720,offsetWidth:1280,offsetHeight:720,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720,right:1280,bottom:720})};if(id==='game'){e.getContext=()=>ctx2d;e.width=1280;e.height=720;ctx2d.canvas=e;e.toDataURL=()=>'';}return e;}
const els=new Map(),getEl=id=>{if(!els.has(id))els.set(id,makeEl(id));return els.get(id)};
const document={getElementById:getEl,querySelector:()=>makeEl('q'),querySelectorAll:()=>[],createElement:t=>makeEl(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:makeEl('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,fonts:{ready:Promise.resolve()},visibilityState:'visible'};
class ImageMock{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this.width=1024;this.height=1024;this.onload=null;this.onerror=null;this._src='';}set src(v){this._src=v;if(this.onload)setTimeout(()=>this.onload(),0)}get src(){return this._src}addEventListener(){}}
class AudioMock{constructor(src=''){this.src=src;this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},userAgent:'node-smoke',maxTouchPoints:0,hardwareConcurrency:4,deviceMemory:4},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:2,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:()=>({matches:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:AudioMock,Image:ImageMock};windowObj.window=windowObj;windowObj.self=windowObj;windowObj.top=windowObj;windowObj.parent=windowObj;
const sandbox={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:AudioMock,Image:ImageMock,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl};sandbox.matchMedia=windowObj.matchMedia;sandbox.addEventListener=noop;sandbox.removeEventListener=noop;
vm.createContext(sandbox);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');
src=src.replace(/\}\)\(\);\s*$/,`window.__V21512_TEST={VERSION,META,G,SECTORS,BOSS_ANIMATIONS,CH2_FAMILY_DEFS,FAMILY_COMBAT_GRAMMAR,FAMILY_COMBO_PLAYS,familyComboPlay,spawnMicroSwarm,killEnemy,spawnEnemy,startFamilyManeuver,updateFamilyManeuver,applyFamilyTacticalMovement,breakFamilyManeuver,updatePlayerBehavior,behaviorCounterLane,riftAllyPool,summonRiftAlly,hitPlayer,rescueLastChance,sectorBalance,adaptivePressure,hasSave,loadRun,PERF,DEVICE,performanceGovernorTick,performanceStatus,performanceEnemyFactor,performanceMicroFactor,performanceParticleCap,performanceRenderScale,effectiveDpr,ASSET_STREAM,CH2_STREAM_REGISTRY,streamLoadCore,streamLoadBoss,streamPrepareWorld,streamPrepareBoss,streamPrepareMenu,streamEvictWorld,streamStatus,CH2_BOSS_IDENTITIES,bossIdentity,bossPhaseNameForSector,bossSignatureConfig,makeBossSignature,updateBossSignatureAttack,updateCH2BossIdentityMovement,BOSS_ANIM_SYNC_PROFILES,bossAnimSyncProfile,bossAttackEmitter,startBossAnimCue,updateBossAnimCue,bossAnimCueFrame,bossAnimFrame,bossAnimState,bossAnimReleaseCue,bossAnimImpactCue,bossAnimStartSignatureCue,BOSS_AUDIO_PROFILES,bossAudioProfile,FAMILY_AUDIO_PROFILES,familyAudioProfile,AudioX,updateRiftAlly,bossSignaturePlayerHit,getG:()=>G};})();`);
try{vm.runInContext(src,sandbox,{filename:'game.js',timeout:7000});}catch(e){console.error('RUNTIME_EVAL_FAIL',e.stack);process.exit(2)}
const t=windowObj.__V21512_TEST;if(!t){console.error('TEST_HOOK_MISSING');process.exit(3)}
function resetWorld(world){t.G.screen='GAME';t.G.mode='campaign';t.G.sector=world;t.G.wave=2;t.G.enemies=[];t.G.eBullets=[];t.G.bullets=[];t.G.obstacles=[];t.G.frontThreats=[];t.G.particles=[];t.G.pickups=[];t.G.boss=null;t.G.bossPending=false;t.G.preBossT=0;t.G.postBossT=0;t.G.sectorClear=false;t.G.lastChanceT=0;t.G.recoveryGraceT=0;t.G.familyPlay=null;t.G.familyPlayTimer=0;t.G.familyPlayCount=0;t.G.familyPlayBreaks=0;t.G.player.hp=t.G.player.maxHp;t.G.player.x=250;t.G.player.y=360;}
// preserves no-empty-screen micro system
resetWorld(1);t.G.kills=3;t.G.microKills=0;t.G.actionGapT=2;const n=t.spawnMicroSwarm(true),micros=t.G.enemies.filter(e=>e.microSwarm),kb=t.G.kills,mb=t.G.microKills;if(micros[0])t.killEnemy(micros[0]);const microOK=n>=4&&n<=10&&t.G.kills===kb&&t.G.microKills===mb+1;
// 10 coordinated playbooks, with worlds 16-20 marked advanced
const playKeys=Object.keys(t.FAMILY_COMBO_PLAYS).map(Number),advanced=playKeys.filter(k=>t.FAMILY_COMBO_PLAYS[k].advanced);const defsOK=playKeys.length===10&&new Set(playKeys.map(k=>t.FAMILY_COMBO_PLAYS[k].id)).size===10&&advanced.length===5&&advanced.every(k=>k>=16);
// World 16: major + medium + minors become a real multi-role play after telegraph
resetWorld(16);const major=t.spawnEnemy('ch2_16_major',950,350),med=t.spawnEnemy('ch2_16_medium',880,300),mins=[0,1,2,3].map(i=>t.spawnEnemy('ch2_16_minor',820+i*18,250+i*60));const maxBefore=[major,med,...mins].map(e=>e.maxHp);const started=t.startFamilyManeuver();const telegraphOK=started&&t.G.familyPlay?.stage==='telegraph'&&major.familyPlayRole==='cover'&&med.familyPlayRole==='breach'&&mins.every(e=>e.familyPlayRole.startsWith('seal_'));t.updateFamilyManeuver(1.0);const active=t.G.familyPlay?.stage==='active',hpSame=[major,med,...mins].every((e,i)=>e.maxHp===maxBefore[i]),surge=med.surgeT>0,guard=major.familyGuardT>0,cloak=mins.some(e=>e.cloakT>0);const mv=t.applyFamilyTacticalMovement(mins[0],t.G.player,-mins[0].spd,0,.016);const roleMoveOK=Number.isFinite(mv.vx)&&Number.isFinite(mv.vy);
// Killing core role breaks formation and awards counterplay bonus
const scoreBefore=t.G.score,breaksBefore=t.G.familyPlayBreaks;t.killEnemy(med);const breakOK=!t.G.familyPlay&&t.G.familyPlayBreaks===breaksBefore+1&&t.G.score>scoreBefore;
// World 20 command play gives brief cover and remains non-HP inflationary
resetWorld(20);const m20=t.spawnEnemy('ch2_20_major',960,360),md20=t.spawnEnemy('ch2_20_medium',890,320),mi20=[t.spawnEnemy('ch2_20_minor',840,260),t.spawnEnemy('ch2_20_minor',840,450),t.spawnEnemy('ch2_20_minor',800,370)];const hp20=[m20,md20,...mi20].map(e=>e.maxHp);const s20=t.startFamilyManeuver();t.updateFamilyManeuver(1.0);const commandOK=s20&&t.G.familyPlay?.stage==='active'&&m20.familyGuardT>0&&[m20,md20,...mi20].every((e,i)=>e.maxHp===hp20[i]);
// Director refuses to launch a play while the player is critical
resetWorld(18);t.spawnEnemy('ch2_18_major',950,350);t.spawnEnemy('ch2_18_medium',880,330);t.spawnEnemy('ch2_18_minor',820,250);t.spawnEnemy('ch2_18_minor',820,450);t.G.player.hp=t.G.player.maxHp*.2;t.G.familyPlayTimer=0;t.updateFamilyManeuver(.2);const reliefOK=!t.G.familyPlay&&t.G.familyPlayTimer>0;
// RIFT ALLY + Last Chance preserved
resetWorld(20);t.G.riftAlly=null;t.G.riftAllyUsed=false;t.META.defeated={};for(let i=1;i<=19;i++)t.META.defeated[i]=true;const pool=t.riftAllyPool(),ally=t.summonRiftAlly(),riftOK=pool.length===19&&ally&&Math.abs(t.G.riftAlly.t-10)<1e-9;
t.G.riftAlly=null;t.G.sector=5;t.G.player.hp=5;t.G.player.shield=0;t.G.player.inv=0;t.G.lastChanceT=0;t.META.supplies=t.META.supplies||{};t.META.supplies.life=1;t.hitPlayer(1000);const warning=t.G.lastChanceT===5&&t.G.player.hp===1,stock=t.META.supplies.life;t.rescueLastChance();const lastChanceOK=warning&&t.G.lastChanceT===0&&t.META.supplies.life===stock-1;
// Difficulty still not HP sponge
const b1=t.sectorBalance(1),b10=t.sectorBalance(10),b20=t.sectorBalance(20),curveOK=b1.enemyHp<1&&b10.enemyHp<=1.05&&b20.enemyHp<=1.10&&b20.pressure>b10.pressure;
// Adaptive Counterplay: repeated upper-lane habit is learned only after sampling and does not change combat stats
resetWorld(16);t.G.behaviorSampleT=0;t.G.behaviorZoneT={upper:0,center:0,lower:0};t.G.behaviorLastZone='center';t.G.behaviorSwitches=0;t.G.behaviorRead='UNREAD';t.G.behaviorConfidence=0;t.G.player.y=120;for(let i=0;i<400;i++)t.updatePlayerBehavior(.016);const readOK=t.G.behaviorRead==='UPPER'&&t.G.behaviorConfidence>.42;let adaptedCount=0,avg=0;for(let i=0;i<120;i++){const q=t.behaviorCounterLane(t.G.player);if(q.adapted)adaptedCount++;avg+=q.y;}avg/=120;const adaptiveLaneOK=readOK&&adaptedCount>55&&avg<720*.55;
// Frequent lane changes are recognized as unpredictable, suppressing targeted counter-lane adaptation
t.G.behaviorSampleT=0;t.G.behaviorZoneT={upper:0,center:0,lower:0};t.G.behaviorLastZone='center';t.G.behaviorSwitches=0;t.G.behaviorRead='UNREAD';for(let i=0;i<420;i++){t.G.player.y=i%2?90:650;t.updatePlayerBehavior(.016);}const unpredictableOK=t.G.behaviorRead==='IMPREDECIBLE'&&!t.behaviorCounterLane(t.G.player).adapted;

// v2.15.10 Boss Identity Pass II — worlds 11–20 own distinct signatures, phases and locomotion.
const expectedIdentity={11:'KHEPRI',12:'VESPERA',13:'REGENT',14:'PYROLUX',15:'CAUSTIC',16:'ATLAS',17:'MIRAGE',18:'PIT',19:'AURICULUS',20:'APIS'};
let identityDefsOK=Object.keys(t.CH2_BOSS_IDENTITIES).length===10,identitySignaturesOK=true,identityMovementOK=true;
for(const w of [11,12,13,14,15,16,17,18,19,20]){
  resetWorld(w);t.G.elapsed=3.5;const sec=t.SECTORS[w-1],id=t.CH2_BOSS_IDENTITIES[w];
  identityDefsOK=identityDefsOK&&id?.key===expectedIdentity[w]&&Array.isArray(id.phases)&&id.phases.length===3&&!!id.signature&&!!id.movement;
  const b={x:920,y:360,r:82,pattern:sec.pattern,name:sec.boss,family:sec.family,t:1.2,fire:0,phase:2,entry:0,phaseTransitionT:0,telegraphT:0,chargeT:0,specialT:0,signatureAttackCd:0,phaseElapsed:4,animAttackT:0,specialCd:0,coreOpenT:0,guardT:0,signatureSide:1};
  const cfg=t.bossSignatureConfig(b),sig=t.makeBossSignature(b,t.G.player,cfg);b.signatureAttack=sig;
  identitySignaturesOK=identitySignaturesOK&&cfg?.name===id.signature&&sig?.identity===id.key&&sig?.stage==='wind'&&t.bossPhaseNameForSector(b,2)===id.phases[1];
  t.updateBossSignatureAttack(b,t.G.player,sec,1.2);identitySignaturesOK=identitySignaturesOK&&['active',undefined].includes(b.signatureAttack?.stage);
  b.fire=0;const beforeBullets=t.G.eBullets.length;t.updateCH2BossIdentityMovement(b,t.G.player,sec,.016,1.2);identityMovementOK=identityMovementOK&&Number.isFinite(b.x)&&Number.isFinite(b.y)&&b.x>=0&&b.y>=0&&(t.G.eBullets.length>=beforeBullets);
}
// v2.15.10 Animation ↔ Attack Sync — telegraph frames lead to an exact release frame, then follow-through.
let animProfilesOK=Object.keys(t.BOSS_ANIM_SYNC_PROFILES).length===20,signatureAnimSyncOK=true,emitterProfilesOK=true;
for(const w of [11,12,13,14,15,16,17,18,19,20]){
  resetWorld(w);t.G.elapsed=4;const sec=t.SECTORS[w-1];
  const b={x:920,y:360,r:82,pattern:sec.pattern,name:sec.boss,family:sec.family,t:1.2,fire:0,phase:2,entry:0,phaseTransitionT:0,telegraphT:0,chargeT:0,specialT:0,signatureAttackCd:0,phaseElapsed:4,animAttackT:0,animCue:null,specialCd:0,coreOpenT:0,guardT:0,signatureSide:1,flash:0,phaseFlash:0};t.G.boss=b;
  const cfg=t.bossSignatureConfig(b),prof=t.bossAnimSyncProfile(b),sig=t.makeBossSignature(b,t.G.player,cfg);b.signatureAttack=sig;t.bossAnimStartSignatureCue(b,cfg,cfg.name);
  const f0=t.bossAnimFrame(b,'attack');t.updateBossAnimCue(b,cfg.wind*.52);const fPrep=t.bossAnimFrame(b,'attack');
  // Crossing the wind/active boundary must snap to the configured release frame even with a large dt.
  t.updateBossAnimCue(b,cfg.wind*.70);t.updateBossSignatureAttack(b,t.G.player,sec,cfg.wind+.01);const fRelease=t.bossAnimFrame(b,'attack');
  t.updateBossAnimCue(b,.18);const fFollow=t.bossAnimFrame(b,'attack');
  signatureAnimSyncOK=signatureAnimSyncOK&&f0<=prof.releaseFrame&&fPrep<=prof.releaseFrame&&fRelease===prof.releaseFrame&&fFollow>=prof.releaseFrame;
  const o=t.bossAttackEmitter(b,'primary');emitterProfilesOK=emitterProfilesOK&&Number.isFinite(o.x)&&Number.isFinite(o.y)&&Math.hypot(o.x-b.x,o.y-b.y)>b.r*.06;
}
// Immediate regular volleys start on the anatomical release frame rather than replaying wind-up after the projectile exists.
resetWorld(20);{const sec=t.SECTORS[19],b={x:910,y:350,r:84,pattern:sec.pattern,name:sec.boss,family:sec.family,t:2,phase:3,animAttackT:0,animCue:null,flash:0,phaseFlash:0};t.G.boss=b;const rf=t.bossAnimSyncProfile(b).releaseFrame;t.bossAnimImpactCue(b,.45,'primary');var primaryImpactSync=t.bossAnimState(b)==='attack'&&t.bossAnimFrame(b,'attack')===rf;t.updateBossAnimCue(b,.20);primaryImpactSync=primaryImpactSync&&t.bossAnimFrame(b,'attack')>=rf;}
// CH2 regular projectiles use the anatomical emitter after the boss movement for that frame.
resetWorld(12);{const sec=t.SECTORS[11],b={x:920,y:360,r:82,pattern:sec.pattern,name:sec.boss,family:sec.family,t:1.8,fire:0,phase:2,entry:0,animAttackT:0,animCue:null,flash:0,phaseFlash:0,identityOpacity:1};t.G.boss=b;t.updateCH2BossIdentityMovement(b,t.G.player,sec,.016,1.2);const shot=t.G.eBullets[0],o=t.bossAttackEmitter(b,'primary');var projectileEmitterSync=!!shot&&Math.hypot(shot.x-o.x,shot.y-o.y)<.001;}

// Phase animation also gets an explicit timeline so phase VFX and body mutation no longer depend on unrelated timers.
resetWorld(16);{const sec=t.SECTORS[15],b={x:900,y:360,r:80,pattern:sec.pattern,name:sec.boss,family:sec.family,t:2,phase:2,animAttackT:0,animCue:null,flash:0,phaseFlash:0};t.G.boss=b;t.startBossAnimCue(b,'phase',{duration:1,releaseAt:.5,releaseFrame:4,startFrame:0,tag:'phase-test'});const a=t.bossAnimFrame(b,'phase');t.updateBossAnimCue(b,.5);const m=t.bossAnimFrame(b,'phase');t.updateBossAnimCue(b,.3);const z=t.bossAnimFrame(b,'phase');var phaseTimelineOK=a===0&&m===4&&z>=4;}

// v2.15.2 migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v2152',JSON.stringify({version:'2.15.2',mode:'campaign',runDifficulty:'normal',sector:16,wave:2,score:444,credits:88,hp:52,shield:17,powers:{},queue:[],powerRanks:{}}));const migrationSeen=t.hasSave(),migrationLoaded=t.loadRun(),migrationOK=migrationSeen&&migrationLoaded&&t.getG().sector===16;
// v2.15.3 migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v2153',JSON.stringify({version:'2.15.3',mode:'campaign',runDifficulty:'normal',sector:17,wave:2,score:555,credits:99,hp:61,shield:22,powers:{},queue:[],powerRanks:{}}));const mig2153Seen=t.hasSave(),mig2153Loaded=t.loadRun(),mig2153OK=mig2153Seen&&mig2153Loaded&&t.getG().sector===17;
// save migrations into v2.15.6
localStorage.clear();localStorage.setItem('swarm_rift_run_v2154',JSON.stringify({version:'2.15.4',mode:'campaign',runDifficulty:'normal',sector:18,wave:2,score:666,credits:111,hp:64,shield:25,powers:{},queue:[],powerRanks:{}}));const mig2154Seen=t.hasSave(),mig2154Loaded=t.loadRun(),mig2154OK=mig2154Seen&&mig2154Loaded&&t.getG().sector===18;
localStorage.clear();localStorage.setItem('swarm_rift_run_v2155',JSON.stringify({version:'2.15.5',mode:'campaign',runDifficulty:'normal',sector:19,wave:2,score:777,credits:123,hp:66,shield:27,powers:{},queue:[],powerRanks:{}}));const mig2155Seen=t.hasSave(),mig2155Loaded=t.loadRun(),mig2155OK=mig2155Seen&&mig2155Loaded&&t.getG().sector===19;
// v2.15.6 -> v2.15.7 save migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v2156',JSON.stringify({version:'2.15.6',mode:'campaign',runDifficulty:'normal',sector:20,wave:2,score:888,credits:144,hp:70,shield:31,powers:{},queue:[],powerRanks:{}}));const mig2156Seen=t.hasSave(),mig2156Loaded=t.loadRun(),mig2156OK=mig2156Seen&&mig2156Loaded&&t.getG().sector===20;

// v2.15.7 -> v2.15.8 save migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v2157',JSON.stringify({version:'2.15.7',mode:'campaign',runDifficulty:'normal',sector:15,wave:2,score:999,credits:166,hp:72,shield:33,powers:{},queue:[],powerRanks:{}}));const mig2157Seen=t.hasSave(),mig2157Loaded=t.loadRun(),mig2157OK=mig2157Seen&&mig2157Loaded&&t.getG().sector===15;
// v2.15.8 -> v2.15.10 save migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v2158',JSON.stringify({version:'2.15.8',mode:'campaign',runDifficulty:'normal',sector:20,wave:2,score:1111,credits:188,hp:75,shield:35,powers:{},queue:[],powerRanks:{}}));const mig2158Seen=t.hasSave(),mig2158Loaded=t.loadRun(),mig2158OK=mig2158Seen&&mig2158Loaded&&t.getG().sector===20;
// v2.15.9 -> v2.15.10 save migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v2159',JSON.stringify({version:'2.15.9',mode:'campaign',runDifficulty:'normal',sector:18,wave:2,score:1212,credits:199,hp:77,shield:36,powers:{},queue:[],powerRanks:{}}));const mig2159Seen=t.hasSave(),mig2159Loaded=t.loadRun(),mig2159OK=mig2159Seen&&mig2159Loaded&&t.getG().sector===18;
// Asset Residency Streamer: no CH2 world is eagerly decoded at boot, current core loads on demand, boss pack loads only when requested, stale world can be evicted.
t.getG().riftAlly=null;for(let w=11;w<=20;w++)t.streamEvictWorld(w);const bootStream=t.streamStatus(),bootEmpty=Object.keys(bootStream.resident).length===0;t.streamPrepareMenu(16);const menuStream=t.streamStatus(),menuOnly=(menuStream.resident[16]?.core||0)<=2&&(menuStream.resident[16]?.boss||0)===0;t.streamPrepareWorld(16,'test-sector');const coreStream=t.streamStatus(),coreLoaded=(coreStream.resident[16]?.core||0)>=13&&(coreStream.resident[16]?.boss||0)===0;t.streamPrepareBoss(16,'test-boss');const bossStream=t.streamStatus(),bossLoaded=(bossStream.resident[16]?.boss||0)>=6;t.streamPrepareWorld(18,'test-next');const evictedStream=t.streamStatus(),staleEvicted=!evictedStream.resident[16]&&(evictedStream.resident[18]?.core||0)>=13;t.streamPrepareWorld(5,'chapter1-return');const chapter1Stream=t.streamStatus(),chapter1Clears=Object.keys(chapter1Stream.resident).length===0;
// Performance governor + device profiler: jank-aware degradation, internal resolution scaling and recovery.
t.getG().screen='GAME';const fullDpr=t.effectiveDpr();for(let i=0;i<100;i++)t.performanceGovernorTick(.04);const slow=t.performanceStatus(),perfRecoveryTier=slow.tier==='RECOVERY'&&slow.enemyFactor<1&&slow.microFactor<1&&slow.particleCap<900&&slow.renderScale<1&&slow.effectiveDpr<fullDpr;
resetWorld(1);const slowMicro=t.spawnMicroSwarm(true),microFloorOK=slowMicro>=4&&slowMicro<=10;
for(let i=0;i<760;i++)t.performanceGovernorTick(.016);const fast=t.performanceStatus(),perfRestores=fast.tier==='FULL'&&fast.enemyFactor===1&&fast.microFactor===1&&fast.particleCap===900&&fast.renderScale===1;
// Jank spikes should be visible in p95/jank telemetry even when average frame time is not catastrophic.
t.PERF.frameWindow.length=0;t.PERF.frameMs=16.67;t.PERF.fps=60;t.PERF.tier='FULL';t.PERF.badT=0;t.PERF.severeT=0;t.PERF.goodT=0;for(let i=0;i<120;i++)t.performanceGovernorTick(i%5===0?.042:.016);const jank=t.performanceStatus(),jankAware=jank.p95Ms>=40&&jank.jank33>.15&&['BALANCED','RECOVERY'].includes(jank.tier);
const deviceProfileOK=['HIGH','MID','LITE'].includes(t.DEVICE.class)&&t.DEVICE.dprCap>=1.4&&t.DEVICE.dprCap<=2&&t.DEVICE.hardwareConcurrency===4&&t.DEVICE.deviceMemory===4;
const dynamicDprOK=fullDpr<=t.DEVICE.dprCap+1e-9&&slow.effectiveDpr<fullDpr&&slow.effectiveDpr>=.85;

// v2.15.11 Audio Event Sync: 20 sonic identities and event-level telemetry.
function resetCurrent(world){const g=t.getG();g.screen='GAME';g.mode='campaign';g.sector=world;g.wave=2;g.enemies=[];g.eBullets=[];g.bullets=[];g.obstacles=[];g.frontThreats=[];g.particles=[];g.pickups=[];g.boss=null;g.bossPending=false;g.preBossT=0;g.postBossT=0;g.sectorClear=false;g.lastChanceT=0;g.recoveryGraceT=0;g.familyPlay=null;g.riftAlly=null;g.riftAllyUsed=false;g.player.hp=g.player.maxHp;g.player.shield=g.player.maxShield;g.player.inv=0;g.player.x=250;g.player.y=360;return g;}
const audioIds=new Set(t.BOSS_AUDIO_PROFILES.map(p=>p.id));
const audioProfilesOK=t.BOSS_AUDIO_PROFILES.length===20&&audioIds.size===20&&t.BOSS_AUDIO_PROFILES.every(p=>Number.isFinite(p.base)&&Number.isFinite(p.accent)&&p.base>0&&p.accent>p.base&&p.type&&p.texture);
const beforeAudio={...t.AudioX.bossEventCounters};
t.AudioX.bossWarn(10);t.AudioX.bossAttack(10,true);t.AudioX.lastBossImpact=0;t.AudioX.bossImpact(10,1);t.AudioX.bossPhase(10);t.AudioX.bossDie(10);
const eventCountersOK=['warn','release','impact','phase','death'].every(k=>(t.AudioX.bossEventCounters[k]||0)>(beforeAudio[k]||0))&&t.AudioX.lastBossEvent?.world===11;
// Regular boss attack cue must invoke release event exactly from the animation impact cue.
{const g=resetCurrent(12),sec=t.SECTORS[11],b={x:910,y:350,r:82,pattern:sec.pattern,name:sec.boss,family:sec.family,t:1,phase:2,animAttackT:0,animCue:null,flash:0,phaseFlash:0};g.boss=b;const c0=t.AudioX.bossEventCounters.release||0;t.bossAnimImpactCue(b,.42,'primary');var releaseAudioSync=(t.AudioX.bossEventCounters.release||0)===c0+1&&t.AudioX.lastBossEvent?.world===12&&t.AudioX.lastBossEvent?.event==='release';}
// RIFT ALLY gets a portal sound identity on entry and exit, without changing its 10s rule.
{const g=resetCurrent(20);t.META.defeated={};for(let i=1;i<=19;i++)t.META.defeated[i]=true;const ai0=t.AudioX.bossEventCounters.allyIn||0,ao0=t.AudioX.bossEventCounters.allyOut||0;const aa=t.summonRiftAlly();const allyAudioIn=!!aa&&(t.AudioX.bossEventCounters.allyIn||0)===ai0+1&&g.riftAlly&&Math.abs(g.riftAlly.t-10)<1e-9;if(g.riftAlly)g.riftAlly.t=.001;t.updateRiftAlly(.01);var riftPortalAudioOK=allyAudioIn&&!g.riftAlly&&(t.AudioX.bossEventCounters.allyOut||0)===ao0+1;}
// Signature hit helper couples real damage with the boss impact event.
{const g=resetCurrent(18),sec=t.SECTORS[17],b={x:900,y:360,r:82,pattern:sec.pattern,name:sec.boss,family:sec.family,t:1,phase:2,animAttackT:0,animCue:null,flash:0,phaseFlash:0};g.boss=b;g.player.shield=0;g.player.inv=0;const hp0=g.player.hp,ci=t.AudioX.bossEventCounters.impact||0;t.AudioX.lastBossImpact=0;t.bossSignaturePlayerHit(b,5,1);var signatureImpactAudio=g.player.hp<hp0&&(t.AudioX.bossEventCounters.impact||0)===ci+1;}
// v2.15.12 Enemy Sonic Ecology: 20 family profiles, tier-aware event grammar and audio budget.
const familyAudioKeys=Object.keys(t.FAMILY_AUDIO_PROFILES),familyProfilesOK=familyAudioKeys.length===20&&new Set(familyAudioKeys).size===20&&familyAudioKeys.every(k=>{const p=t.FAMILY_AUDIO_PROFILES[k];return Number.isFinite(p.base)&&Number.isFinite(p.accent)&&p.accent>p.base&&p.type&&p.texture;});
{const g=resetCurrent(16);t.PERF.tier='FULL';t.AudioX.muted=false;t.AudioX.enemyAudioBudget={windowStart:0,voices:0};t.AudioX.enemyEventAt={spawn:0,shot:0,death:0};t.AudioX.enemyEventCounters={spawn:0,shot:0,death:0,dropped:0};const minor=t.spawnEnemy('ch2_16_minor',900,250),medium=t.spawnEnemy('ch2_16_medium',900,360),major=t.spawnEnemy('ch2_16_major',900,470);t.AudioX.enemyEventAt.shot=0;t.AudioX.enemyShot(medium);t.AudioX.enemyEventAt.death=0;t.AudioX.enemyDeath(major);var familyEventsOK=t.AudioX.enemyEventCounters.spawn>=1&&t.AudioX.enemyEventCounters.shot>=1&&t.AudioX.enemyEventCounters.death>=1&&t.AudioX.lastEnemyEvent?.family==='VEILS';var familyTierOK=t.familyAudioProfile(minor)===t.FAMILY_AUDIO_PROFILES.VEILS&&t.familyAudioProfile(major)===t.FAMILY_AUDIO_PROFILES.VEILS;}
{const g=resetCurrent(20);t.PERF.tier='RECOVERY';t.AudioX.enemyAudioBudget={windowStart:1000,voices:4};t.AudioX.enemyEventCounters.dropped=0;const e={family:'APIARY',kind:'insect',form:'ch2_20_minor',dead:false,microSwarm:false};var audioBudgetOK=t.AudioX.enemyVoiceAllowed('shot',e)===false&&t.AudioX.enemyEventCounters.dropped===1;t.PERF.tier='FULL';}
// v2.15.11 -> v2.15.12 migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v21511',JSON.stringify({version:'2.15.11',mode:'campaign',runDifficulty:'normal',sector:20,wave:2,score:1414,credits:222,hp:80,shield:38,powers:{},queue:[],powerRanks:{}}));const mig21511Seen=t.hasSave(),mig21511Loaded=t.loadRun(),mig21511OK=mig21511Seen&&mig21511Loaded&&t.getG().sector===20;

// v2.15.10 -> v2.15.11 migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v21510',JSON.stringify({version:'2.15.10',mode:'campaign',runDifficulty:'normal',sector:19,wave:2,score:1313,credits:211,hp:79,shield:37,powers:{},queue:[],powerRanks:{}}));const mig21510Seen=t.hasSave(),mig21510Loaded=t.loadRun(),mig21510OK=mig21510Seen&&mig21510Loaded&&t.getG().sector===19;
const checks={version:t.VERSION==='2.15.12',worlds:t.SECTORS.length===20,bosses:Object.keys(t.BOSS_ANIMATIONS).length===20,ch2Families:Object.keys(t.CH2_FAMILY_DEFS).length===10,microSwarm:microOK,playDefinitions:defsOK,telegraphRoles:telegraphOK,playExecution:active&&surge&&guard&&cloak&&roleMoveOK,noHpInflation:hpSame,formationBreak:breakOK,royalCommand:commandOK,criticalRelief:reliefOK,riftAlly:riftOK,lastChance:lastChanceOK,difficultyCurve:curveOK,saveMigration2152:migrationOK,adaptiveBehaviorRead:readOK,adaptiveLaneBias:adaptiveLaneOK,unpredictableRelief:unpredictableOK,saveMigration2153:mig2153OK,saveMigration2154:mig2154OK,saveMigration2155:mig2155OK,performanceRecovery:perfRecoveryTier,performanceRestores:perfRestores,microFloorUnderLoad:microFloorOK,deviceProfiler:deviceProfileOK,dynamicInternalResolution:dynamicDprOK,jankAwareFramePacer:jankAware,saveMigration2156:mig2156OK,saveMigration2157:mig2157OK,saveMigration2158:mig2158OK,bossIdentityDefs:identityDefsOK,bossIdentitySignatures:identitySignaturesOK,bossIdentityMovement:identityMovementOK,animationSyncProfiles:animProfilesOK,signatureReleaseFrame:signatureAnimSyncOK,anatomicalEmitters:emitterProfilesOK,projectileEmitterSync,primaryImpactFrame:primaryImpactSync,phaseTimeline:phaseTimelineOK,saveMigration2159:mig2159OK,audioProfiles:audioProfilesOK,familyAudioProfiles:familyProfilesOK,familyAudioEvents:familyEventsOK,familyAudioTier:familyTierOK,audioBudget:audioBudgetOK,audioEventCounters:eventCountersOK,releaseAudioSync,riftPortalAudio:riftPortalAudioOK,signatureImpactAudio,saveMigration21510:mig21510OK,saveMigration21511:mig21511OK,streamBootLazy:bootEmpty,streamMenuLight:menuOnly,streamCurrentCore:coreLoaded,streamBossOnDemand:bossLoaded,streamEvictsStale:staleEvicted,streamClearsOnChapter1:chapter1Clears};
const ok=Object.values(checks).every(Boolean);console.log(JSON.stringify({ok,checks,world16:{active,surge,guard,cloak,play:t.familyComboPlay(16)?.label},world20:{play:t.familyComboPlay(20)?.label,guard:m20.familyGuardT},counterplay:{breaks:t.G.familyPlayBreaks,scoreGain:t.G.score-scoreBefore},migration:{migrationSeen,migrationLoaded,sector:t.getG().sector,mig2154OK,mig2156OK,mig2158OK},streaming:{bootStream,menuStream,coreStream,bossStream,evictedStream,chapter1Stream},performance:{device:t.DEVICE,fullDpr,slow,fast,jank,slowMicro}},null,2));process.exit(ok?0:4);
