const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){}
function makeCtx(){const target={measureText:t=>({width:String(t??'').length*7}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(target,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}
const ctx2d=makeCtx();
function makeEl(id){const e={id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,appendChild:noop,remove:noop,setAttribute:noop,getAttribute:()=>null,focus:noop,blur:noop,click:noop,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',textContent:'',innerHTML:'',value:'',checked:false,disabled:false,clientWidth:1280,clientHeight:720,offsetWidth:1280,offsetHeight:720,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720,right:1280,bottom:720})};if(id==='game'){e.getContext=()=>ctx2d;e.width=1280;e.height=720;ctx2d.canvas=e;e.toDataURL=()=>'';}return e;}
const els=new Map(),getEl=id=>{if(!els.has(id))els.set(id,makeEl(id));return els.get(id)};
const document={getElementById:getEl,querySelector:()=>makeEl('q'),querySelectorAll:()=>[],createElement:t=>makeEl(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:makeEl('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,fonts:{ready:Promise.resolve()},visibilityState:'visible'};
class ImageMock{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this.width=1024;this.height=1024;this.onload=null;this.onerror=null;this._src='';}set src(v){this._src=v;if(this.onload)setTimeout(()=>this.onload(),0)}get src(){return this._src}addEventListener(){}}
class AudioMock{constructor(src=''){this.src=src;this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},userAgent:'node-smoke',maxTouchPoints:0},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:1,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:()=>({matches:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:AudioMock,Image:ImageMock};windowObj.window=windowObj;windowObj.self=windowObj;windowObj.top=windowObj;windowObj.parent=windowObj;
const sandbox={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:AudioMock,Image:ImageMock,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl};sandbox.matchMedia=windowObj.matchMedia;sandbox.addEventListener=noop;sandbox.removeEventListener=noop;
vm.createContext(sandbox);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');
src=src.replace(/\}\)\(\);\s*$/,`window.__V2155_TEST={VERSION,META,G,SECTORS,BOSS_ANIMATIONS,CH2_FAMILY_DEFS,FAMILY_COMBAT_GRAMMAR,FAMILY_COMBO_PLAYS,familyComboPlay,spawnMicroSwarm,killEnemy,spawnEnemy,startFamilyManeuver,updateFamilyManeuver,applyFamilyTacticalMovement,breakFamilyManeuver,updatePlayerBehavior,behaviorCounterLane,riftAllyPool,summonRiftAlly,hitPlayer,rescueLastChance,sectorBalance,adaptivePressure,hasSave,loadRun,PERF,performanceGovernorTick,performanceStatus,performanceEnemyFactor,performanceMicroFactor,performanceParticleCap,getG:()=>G};})();`);
try{vm.runInContext(src,sandbox,{filename:'game.js',timeout:7000});}catch(e){console.error('RUNTIME_EVAL_FAIL',e.stack);process.exit(2)}
const t=windowObj.__V2155_TEST;if(!t){console.error('TEST_HOOK_MISSING');process.exit(3)}
function resetWorld(world){t.G.screen='GAME';t.G.mode='campaign';t.G.sector=world;t.G.wave=2;t.G.enemies=[];t.G.eBullets=[];t.G.bullets=[];t.G.obstacles=[];t.G.frontThreats=[];t.G.particles=[];t.G.pickups=[];t.G.boss=null;t.G.bossPending=false;t.G.preBossT=0;t.G.postBossT=0;t.G.sectorClear=false;t.G.lastChanceT=0;t.G.recoveryGraceT=0;t.G.familyPlay=null;t.G.familyPlayTimer=0;t.G.familyPlayCount=0;t.G.familyPlayBreaks=0;t.G.player.hp=t.G.player.maxHp;t.G.player.x=250;t.G.player.y=360;}
// preserves no-empty-screen micro system
resetWorld(1);t.G.kills=3;t.G.microKills=0;t.G.actionGapT=2;const n=t.spawnMicroSwarm(true),micros=t.G.enemies.filter(e=>e.microSwarm),kb=t.G.kills,mb=t.G.microKills;if(micros[0])t.killEnemy(micros[0]);const microOK=n>=4&&n<=10&&t.G.kills===kb&&t.G.microKills===mb+1;
// 10 coordinated playbooks, with worlds 16-20 marked advanced
const playKeys=Object.keys(t.FAMILY_COMBO_PLAYS).map(Number),advanced=playKeys.filter(k=>t.FAMILY_COMBO_PLAYS[k].advanced);const defsOK=playKeys.length===10&&new Set(playKeys.map(k=>t.FAMILY_COMBO_PLAYS[k].id)).size===10&&advanced.length===5&&advanced.every(k=>k>=16);
// World 16: major + medium + minors become a real multi-role play after telegraph
resetWorld(16);const major=t.spawnEnemy('ch2_16_major',950,350),med=t.spawnEnemy('ch2_16_medium',880,300),mins=[0,1,2,3].map(i=>t.spawnEnemy('ch2_16_minor',820+i*18,250+i*60));const maxBefore=[major,med,...mins].map(e=>e.maxHp);const started=t.startFamilyManeuver();const telegraphOK=started&&t.G.familyPlay?.stage==='telegraph'&&major.familyPlayRole==='cover'&&med.familyPlayRole==='breach'&&mins.every(e=>e.familyPlayRole.startsWith('seal_'));t.updateFamilyManeuver(1.0);const active=t.G.familyPlay?.stage==='active',hpSame=[major,med,...mins].every((e,i)=>e.maxHp===maxBefore[i]),surge=med.surgeT>0,guard=major.familyGuardT>0,cloak=mins.some(e=>e.cloakT>0);const mv=t.applyFamilyTacticalMovement(mins[0],t.G.player,-mins[0].spd,0,.016);const roleMoveOK=Number.isFinite(mv.vx)&&Number.isFinite(mv.vy);
// Killing core role breaks formation and awards counterplay bonus
const scoreBefore=t.G.score,breaksBefore=t.G.familyPlayBreaks;t.killEnemy(med);const breakOK=!t.G.familyPlay&&t.G.familyPlayBreaks===breaksBefore+1&&t.G.score>scoreBefore;
// World 20 command play gives brief cover and remains non-HP inflationary
resetWorld(20);const m20=t.spawnEnemy('ch2_20_major',960,360),md20=t.spawnEnemy('ch2_20_medium',890,320),mi20=[t.spawnEnemy('ch2_20_minor',840,260),t.spawnEnemy('ch2_20_minor',840,450),t.spawnEnemy('ch2_20_minor',800,370)];const hp20=[m20,md20,...mi20].map(e=>e.maxHp);const s20=t.startFamilyManeuver();t.updateFamilyManeuver(1.0);const commandOK=s20&&t.G.familyPlay?.stage==='active'&&m20.familyGuardT>0&&[m20,md20,...mi20].every((e,i)=>e.maxHp===hp20[i]);
// Director refuses to launch a play while the player is critical
resetWorld(18);t.spawnEnemy('ch2_18_major',950,350);t.spawnEnemy('ch2_18_medium',880,330);t.spawnEnemy('ch2_18_minor',820,250);t.spawnEnemy('ch2_18_minor',820,450);t.G.player.hp=t.G.player.maxHp*.2;t.G.familyPlayTimer=0;t.updateFamilyManeuver(.2);const reliefOK=!t.G.familyPlay&&t.G.familyPlayTimer>0;
// RIFT ALLY + Last Chance preserved
resetWorld(20);t.G.riftAlly=null;t.G.riftAllyUsed=false;t.META.defeated={};for(let i=1;i<=19;i++)t.META.defeated[i]=true;const pool=t.riftAllyPool(),ally=t.summonRiftAlly(),riftOK=pool.length===19&&ally&&Math.abs(t.G.riftAlly.t-10)<1e-9;
t.G.riftAlly=null;t.G.sector=5;t.G.player.hp=5;t.G.player.shield=0;t.G.player.inv=0;t.G.lastChanceT=0;t.META.supplies=t.META.supplies||{};t.META.supplies.life=1;t.hitPlayer(1000);const warning=t.G.lastChanceT===5&&t.G.player.hp===1,stock=t.META.supplies.life;t.rescueLastChance();const lastChanceOK=warning&&t.G.lastChanceT===0&&t.META.supplies.life===stock-1;
// Difficulty still not HP sponge
const b1=t.sectorBalance(1),b10=t.sectorBalance(10),b20=t.sectorBalance(20),curveOK=b1.enemyHp<1&&b10.enemyHp<=1.05&&b20.enemyHp<=1.10&&b20.pressure>b10.pressure;
// Adaptive Counterplay: repeated upper-lane habit is learned only after sampling and does not change combat stats
resetWorld(16);t.G.behaviorSampleT=0;t.G.behaviorZoneT={upper:0,center:0,lower:0};t.G.behaviorLastZone='center';t.G.behaviorSwitches=0;t.G.behaviorRead='UNREAD';t.G.behaviorConfidence=0;t.G.player.y=120;for(let i=0;i<400;i++)t.updatePlayerBehavior(.016);const readOK=t.G.behaviorRead==='UPPER'&&t.G.behaviorConfidence>.42;let adaptedCount=0,avg=0;for(let i=0;i<120;i++){const q=t.behaviorCounterLane(t.G.player);if(q.adapted)adaptedCount++;avg+=q.y;}avg/=120;const adaptiveLaneOK=readOK&&adaptedCount>55&&avg<720*.55;
// Frequent lane changes are recognized as unpredictable, suppressing targeted counter-lane adaptation
t.G.behaviorSampleT=0;t.G.behaviorZoneT={upper:0,center:0,lower:0};t.G.behaviorLastZone='center';t.G.behaviorSwitches=0;t.G.behaviorRead='UNREAD';for(let i=0;i<420;i++){t.G.player.y=i%2?90:650;t.updatePlayerBehavior(.016);}const unpredictableOK=t.G.behaviorRead==='IMPREDECIBLE'&&!t.behaviorCounterLane(t.G.player).adapted;
// v2.15.2 migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v2152',JSON.stringify({version:'2.15.2',mode:'campaign',runDifficulty:'normal',sector:16,wave:2,score:444,credits:88,hp:52,shield:17,powers:{},queue:[],powerRanks:{}}));const migrationSeen=t.hasSave(),migrationLoaded=t.loadRun(),migrationOK=migrationSeen&&migrationLoaded&&t.getG().sector===16;
// v2.15.3 migration
localStorage.clear();localStorage.setItem('swarm_rift_run_v2153',JSON.stringify({version:'2.15.3',mode:'campaign',runDifficulty:'normal',sector:17,wave:2,score:555,credits:99,hp:61,shield:22,powers:{},queue:[],powerRanks:{}}));const mig2153Seen=t.hasSave(),mig2153Loaded=t.loadRun(),mig2153OK=mig2153Seen&&mig2153Loaded&&t.getG().sector===17;
// v2.15.4 save migration into v2.15.5
localStorage.clear();localStorage.setItem('swarm_rift_run_v2154',JSON.stringify({version:'2.15.4',mode:'campaign',runDifficulty:'normal',sector:18,wave:2,score:666,credits:111,hp:64,shield:25,powers:{},queue:[],powerRanks:{}}));const mig2154Seen=t.hasSave(),mig2154Loaded=t.loadRun(),mig2154OK=mig2154Seen&&mig2154Loaded&&t.getG().sector===18;
// Performance governor: degrades gracefully under sustained slow frames and recovers after sustained healthy frames.
t.getG().screen='GAME';for(let i=0;i<100;i++)t.performanceGovernorTick(.04);const slow=t.performanceStatus(),perfRecoveryTier=slow.tier==='RECOVERY'&&slow.enemyFactor<1&&slow.microFactor<1&&slow.particleCap<900;
resetWorld(1);const slowMicro=t.spawnMicroSwarm(true),microFloorOK=slowMicro>=4&&slowMicro<=10;
for(let i=0;i<520;i++)t.performanceGovernorTick(.016);const fast=t.performanceStatus(),perfRestores=fast.tier==='FULL'&&fast.enemyFactor===1&&fast.microFactor===1&&fast.particleCap===900;
const checks={version:t.VERSION==='2.15.5',worlds:t.SECTORS.length===20,bosses:Object.keys(t.BOSS_ANIMATIONS).length===20,ch2Families:Object.keys(t.CH2_FAMILY_DEFS).length===10,microSwarm:microOK,playDefinitions:defsOK,telegraphRoles:telegraphOK,playExecution:active&&surge&&guard&&cloak&&roleMoveOK,noHpInflation:hpSame,formationBreak:breakOK,royalCommand:commandOK,criticalRelief:reliefOK,riftAlly:riftOK,lastChance:lastChanceOK,difficultyCurve:curveOK,saveMigration2152:migrationOK,adaptiveBehaviorRead:readOK,adaptiveLaneBias:adaptiveLaneOK,unpredictableRelief:unpredictableOK,saveMigration2153:mig2153OK,saveMigration2154:mig2154OK,performanceRecovery:perfRecoveryTier,performanceRestores:perfRestores,microFloorUnderLoad:microFloorOK};
const ok=Object.values(checks).every(Boolean);console.log(JSON.stringify({ok,checks,world16:{active,surge,guard,cloak,play:t.familyComboPlay(16)?.label},world20:{play:t.familyComboPlay(20)?.label,guard:m20.familyGuardT},counterplay:{breaks:t.G.familyPlayBreaks,scoreGain:t.G.score-scoreBefore},migration:{migrationSeen,migrationLoaded,sector:t.getG().sector,mig2154OK},performance:{slow,fast,slowMicro}},null,2));process.exit(ok?0:4);
