const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){} function makeCtx(){const t={measureText:x=>({width:String(x??'').length*6.4}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(t,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}const ctx=makeCtx();
function el(id){return {id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,setAttribute:noop,getAttribute:()=>null,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',getBoundingClientRect:()=>id==='topActions'?({left:585,top:6,width:253,height:44,right:838,bottom:50}):({left:0,top:0,width:844,height:390,right:844,bottom:390})};}
const els=new Map(),getEl=id=>{if(!els.has(id)){const e=el(id);if(id==='game'){e.getContext=()=>ctx;e.width=1280;e.height=720;ctx.canvas=e;}els.set(id,e);}return els.get(id)};
const document={getElementById:getEl,querySelector:()=>el('q'),querySelectorAll:()=>[],createElement:t=>el(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:el('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,visibilityState:'visible'};
class Img{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this._src='';}set src(v){this._src=v}get src(){return this._src}addEventListener(){}} class Aud{constructor(){this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},hardwareConcurrency:4,deviceMemory:4,maxTouchPoints:0},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:2,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:q=>({matches:q.includes('pointer:coarse')?!!windowObj.__coarse:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:Aud,Image:Img};windowObj.__coarse=false;windowObj.window=windowObj;windowObj.self=windowObj;
const sb={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:Aud,Image:Img,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl};sb.matchMedia=windowObj.matchMedia;sb.addEventListener=noop;sb.removeEventListener=noop;vm.createContext(sb);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');src=src.replace(/\}\)\(\);\s*$/,`window.__T={VERSION,SECTORS,META,HIVE_TACTICAL_IDENTITY,HIVE_ARENA_IDENTITY,HIVE_COUNTER_EVOLUTION_IDENTITY,HIVE_MICRO_SEQUENCE_IDENTITY,HIVE_DIRECTOR_CONFIG,getG:()=>G,setViewport:(w,h,c=false)=>{W=w;H=h;window.__coarse=c;},setSafe:(top,right,bottom,left)=>{SAFE_AREA={top,right,bottom,left};},uiProfile,compactUI,hudFocusMode,hudPriorityStatus,hudPresentationStatus,syncHudPresentation,drawHUD,drawInsect,setScreen,hasSave,loadRun,topActions,shopBtn,playerCombatBounds,actionRailExclusion,touchStartExcluded,sanitizeTouchPoint,mobileErgonomicsStatus,safeHudCenterX,hiveDirectorSelfTest,hiveRollingDps,hiveResetDamageMeter,hiveRecordPlayerDamage,hiveTargetWindow,hiveProposedResponse,hiveStartBoss,hiveSampleDirector,hiveFinalizeBoss,hiveDirectorStatus,hiveDirectorReport,hivePersistFight,hiveTelemetrySummary,hiveDpsProfile,hiveHistoricalBaseline,hiveCalibratedExpected,hiveExperienceSnapshot,hiveMaybeSignaturePilot,hiveSpatialUpdate,hiveSpatialSnapshot,hiveTacticalPilotUpdate,hiveTacticalVector,hiveTacticalEligible,hiveArenaPilotState,hiveArenaEligible,hiveArenaLanePlan,hiveArenaPrepare,hiveArenaExecute,hiveArenaMorphologyUpdate,hiveCounterEvolutionState,hiveCounterEvolutionTactic,hiveCounterEvolutionPickResponse,hiveCounterEvolutionEffect,hiveCounterEvolutionStart,hiveCounterEvolutionFinish,hiveCounterEvolutionSample,hiveCounterEvolutionSnapshot,hiveMicroSequenceSpec,hiveMicroSequenceDuration,hiveMicroSequenceStage,hiveMicroSequenceObserve,hiveSpatialState,updateCH2BossIdentityMovement,makeCH2IdentitySignature,bossIdentity,resetHiveCache:()=>{HIVE_TELEMETRY_CACHE=null;},resetHiveTelemetry:()=>{HIVE_TELEMETRY_CACHE=null;localStorage.removeItem(KEY_HIVE_TELEMETRY);localStorage.removeItem(KEY_HIVE_TELEMETRY_PREV);}};})();`);vm.runInContext(src,sb,{timeout:10000});const t=windowObj.__T;if(!t)throw Error('hook');
function reset(){const g=t.getG();g.screen='GAME';g.mode='campaign';g.sector=16;g.wave=2;g.goal=40;g.kills=12;g.runDifficulty='normal';g.elapsed=10;g.score=1000;g.credits=200;g.xp=20;g.xpNext=100;g.level=5;g.powers={};g.powerQueue=[];g.maxActivePowers=6;g.maxQueuePowers=3;g.combo=0;g.preBossT=0;g.postBossT=0;g.bossWarningT=0;g.bossWarningText='';g.lastChanceT=0;g.frenzyT=0;g.familyPlay=null;g.waveObjective=null;g.riftAlly=null;g.apexT=0;g.fusionSurgeT=0;g.player={x:200,y:200,r:18,hp:72,maxHp:100,shield:40,maxShield:100,inv:0};g.boss=null;return g;}
const checks={};
reset();checks.worlds20=t.SECTORS.length===20;
t.setViewport(1280,720,false);t.setSafe(0,0,0,0);checks.desktop=t.uiProfile()==='DESKTOP'&&!t.compactUI();checks.desktopBounds=JSON.stringify(t.playerCombatBounds())===JSON.stringify({left:28,right:1252,top:44,bottom:690});
t.setViewport(844,390,true);t.setSafe(0,47,21,47);checks.mobileLandscape=t.uiProfile()==='MOBILE_LANDSCAPE'&&t.compactUI();const b=t.playerCombatBounds();checks.safeAreaBounds=b.left===73&&b.right===771&&b.top===44&&b.bottom===341;
const edge=t.sanitizeTouchPoint(843,389);checks.edgeClamp=edge.x<=b.right&&edge.y<=b.bottom&&edge.x>=b.left&&edge.y>=b.top;
const rail=t.actionRailExclusion(8);checks.actionRailValid=rail.left<rail.right&&rail.top<rail.bottom&&rail.right<=844;checks.actionRailExcluded=t.touchStartExcluded(820,20)===true;
const routed=t.sanitizeTouchPoint(820,20);checks.railRouting=!((routed.x>=rail.left&&routed.x<=rail.right)&&(routed.y>=rail.top&&routed.y<=rail.bottom));
checks.safeHudCenter=Math.abs(t.safeHudCenterX()-422)<.01;
const es=t.mobileErgonomicsStatus();checks.ergoContract=es.effectiveTapTarget===44&&es.singlePrimaryTouch&&es.secondaryTouchIgnored&&es.coalescedPointerMoves&&es.viewportDebounce&&es.directTouch;
let g=reset();t.setViewport(844,390,true);t.setSafe(0,47,21,47);checks.combatFocus=t.hudFocusMode()==='COMBAT';g.lastChanceT=4.2;checks.lastChanceHighest=t.hudFocusMode()==='LAST_CHANCE'&&t.hudPriorityStatus().text.includes('RESCATE');let drawOK=true;try{t.drawHUD();}catch(e){drawOK=false;console.error(e.stack)}checks.compactDraw=drawOK;
// migration v2.15.23 -> v2.15.24
localStorage.clear();localStorage.setItem('swarm_rift_run_v21523',JSON.stringify({version:'2.15.23',mode:'campaign',runDifficulty:'normal',sector:19,wave:3,score:1818,credits:255,hp:85,shield:42,powers:{},queue:[],powerRanks:{}}));checks.saveMigration=t.hasSave()&&t.loadRun()&&t.getG().sector===19;
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8'),index=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'css/game.css'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
Object.assign(checks,{version:t.VERSION==='2.15.24',statusHook:game.includes('__SWARM_V21524_STATUS'),cssBust:index.includes('css/game.css?v=21524'),jsBust:index.includes('js/game.js?v=21524'),swCache:sw.includes("swarm-rift-v2.15.24"),safeProbe:index.includes('id="safeAreaProbe"')&&css.includes('safe-area-inset-left'),touchTargetCss:css.includes('button::before')&&css.includes('inset:-4px'),secondaryGuard:game.includes('ignoredSecondary++'),coalescedInput:game.includes('getCoalescedEvents'),visibilityCancel:game.includes("resetDirectTouch('visibility')"),orientationCancel:game.includes("resetDirectTouch('orientation')"),debouncedViewport:game.includes('function stabilizeViewport'),dynamicPlayerBounds:game.includes('const bounds=playerCombatBounds()'),directTouchPreserved:css.includes('.stick-zone{display:none!important'),noDashInput:!game.includes("addEventListener('pointerdown',()=>dash"),microSwarmPreserved:game.includes('function spawnMicroSwarm'),riftAllyPreserved:game.includes('function summonRiftAlly'),lastChancePreserved:game.includes('function beginLastChance'),hudPreserved:game.includes('__SWARM_V21517_STATUS'),mobileErgonomicsPreserved:game.includes('__SWARM_V21518_STATUS'),performancePreserved:game.includes('function performanceGovernorTick')});

// v2.15.24 Adaptive Hive Boss Director — Coevolution Sequences
const hiveSelf=t.hiveDirectorSelfTest();checks.hiveSelfTest=hiveSelf.pass&&hiveSelf.heavyCountermeasuresShadow&&hiveSelf.signaturePilotPreserved&&hiveSelf.tacticalGeometryNoStatInflation;
checks.hiveStates=hiveSelf.statesPass&&hiveSelf.states.A0==='A0'&&hiveSelf.states.A1==='A1'&&hiveSelf.states.A2==='A2'&&hiveSelf.states.A3==='A3';
checks.hiveHysteresis=hiveSelf.hysteresis.pass;
const hstat=t.hiveDirectorStatus();checks.hiveCadence=hstat.sampleInterval===1&&hstat.damageWindows.burst===3&&hstat.damageWindows.tactical===8&&hstat.damageWindows.sustained===20;
const windows=[t.hiveTargetWindow(1),t.hiveTargetWindow(8),t.hiveTargetWindow(15),t.hiveTargetWindow(20)];checks.hiveTargetWindows=JSON.stringify(windows.map(x=>[x.low,x.high]))===JSON.stringify([[45,75],[55,90],[70,110],[90,130]]);
g=reset();g.sector=11;g.player={x:200,y:200,r:18,hp:100,maxHp:100,shield:100,maxShield:100,inv:0};const a1=t.hiveProposedResponse('A1',{ttk:80,dpsRatio:1});checks.a1Silent=a1.type==='NONE'&&a1.wouldApply===false;
const a3=t.hiveProposedResponse('A3',{ttk:12,dpsRatio:3,confidence:.95,age:10,target:{low:70,high:110,expectedDps:10},profile:{fingerprint:'SUSTAINED_DOMINATION',sustainedVsExpected:3},experience:{phaseDebt:1,signatureDebt:1,coverage:.4,risk:2,nativeGateProtecting:false},hold:{active:false,reasons:[]}});checks.a3Shadow=a3.wouldApply===false&&a3.receivedDamageMultiplier===.70&&a3.suppression&&a3.suppression.restoreExactState===true&&a3.suppression.mutatesBuild===false;
t.hiveResetDamageMeter();g.elapsed=0;t.hiveRecordPlayerDamage(100,false,'normal');g.elapsed=1;t.hiveRecordPlayerDamage(100,false,'normal');checks.dpsRolling=Math.abs(t.hiveRollingDps(2,false)-100)<.001;
// multi-window fingerprint and confidence guard
g=reset();g.sector=11;g.elapsed=0;g.boss={name:'PROFILE_TEST',pattern:'storm',hp:1000,maxHp:1000,phase:2,phaseElapsed:10,signatureAttackCd:8,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0};t.hiveResetDamageMeter();for(let i=0;i<12;i++){g.elapsed=i;t.hiveRecordPlayerDamage(i<9?20:100,true,'normal');}const prof=t.hiveDpsProfile(20,12);checks.multiWindowDps=prof.burst>prof.sustained&&prof.tactical>=prof.sustained&&prof.confidence>.5;
const self2=t.hiveDirectorSelfTest();checks.burstGuard=self2.burstGuard&&self2.confidenceGuard;
t.resetHiveTelemetry();g=reset();g.sector=11;g.elapsed=0;g.boss={name:'HIVE_TEST_BOSS',pattern:'storm',hp:1000,maxHp:1000,phase:1,phaseElapsed:0,signatureAttackCd:8,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0};t.hiveStartBoss(g.boss);for(let i=1;i<=10;i++){g.elapsed=i;g.boss.hp=Math.max(0,1000-i*50);t.hiveRecordPlayerDamage(50,true,'normal');t.hiveSampleDirector();}const simRec=t.hiveFinalizeBoss('defeat');checks.telemetryRuntime=!!simRec&&simRec.world===11&&simRec.boss==='HIVE_TEST_BOSS'&&simRec.result==='defeat'&&simRec.damageReceivedByBoss===500&&simRec.ttkReal===10&&t.hiveTelemetrySummary().stored===1;
t.resetHiveTelemetry();for(let i=0;i<45;i++)t.hivePersistFight({world:(i%20)+1,boss:'T'+i,ttkReal:50,maxState:'A1',result:'victory'});const hs=t.hiveTelemetrySummary();checks.telemetryCap=hs.stored===40&&hs.limit===40;
// telemetry migration 2.15.21 -> 2.15.22
t.resetHiveTelemetry();localStorage.setItem('swarm_rift_hive_telemetry_v21523',JSON.stringify({schema:5,version:'2.15.23',fights:[{world:11,boss:'OLD',difficulty:'normal',dpsDuringBoss:20,ttkReal:50,maxState:'A1',result:'victory'}]}));t.resetHiveCache();const mig=t.hiveTelemetrySummary();checks.telemetryMigration=mig.stored===1&&mig.migratedFrom==='2.15.23';
// local memory calibration bounded to ±12%
const cal=t.hiveCalibratedExpected(10,{eligible:true,medianDps:20});checks.historyClamp=Math.abs(cal.expected-11.2)<.001&&Math.abs(cal.delta-.12)<.001;
// signature pilot: only identity-preserving live intervention
g=reset();g.sector=11;g.mode='campaign';g.elapsed=20;g.boss={name:'PILOT_BOSS',pattern:'storm',hp:500,maxHp:1000,phase:2,phaseElapsed:10,signatureAttackCd:8,signatureAttack:null,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0};const hh={finished:false,state:'A3',confidence:.95,signaturePilotUsedByPhase:{},signaturePilotEvents:[]};const pil=t.hiveMaybeSignaturePilot(hh,g.boss,10,{fingerprint:'SUSTAINED_DOMINATION'},{signatureDebt:1},{active:false,reasons:[]});checks.signaturePilot=pil&&g.boss.signatureAttackCd<=1.05&&hh.signaturePilotEvents.length===1&&hh.signaturePilotUsedByPhase[2]===true;const cdOnce=g.boss.signatureAttackCd;g.boss.signatureAttackCd=8;const pil2=t.hiveMaybeSignaturePilot(hh,g.boss,11,{fingerprint:'SUSTAINED_DOMINATION'},{signatureDebt:1},{active:false,reasons:[]});checks.signaturePilotOncePerPhase=!pil2&&g.boss.signatureAttackCd===8&&hh.signaturePilotEvents.length===1;g.sector=10;const hhEarly={finished:false,state:'A3',confidence:.95,signaturePilotUsedByPhase:{},signaturePilotEvents:[]};const pilEarly=t.hiveMaybeSignaturePilot(hhEarly,g.boss,12,{fingerprint:'SUSTAINED_DOMINATION'},{signatureDebt:1},{active:false,reasons:[]});checks.signaturePilotAdvancedOnly=!pilEarly;g.sector=11;const hhFinal={finished:false,finalizing:true,state:'A3',confidence:.95,signaturePilotUsedByPhase:{},signaturePilotEvents:[]};g.boss.signatureAttackCd=8;const pilFinal=t.hiveMaybeSignaturePilot(hhFinal,g.boss,13,{fingerprint:'SUSTAINED_DOMINATION'},{signatureDebt:1},{active:false,reasons:[]});checks.signaturePilotFinalizingGuard=!pilFinal&&g.boss.signatureAttackCd===8;

// Tactical identity pilot: local spatial reading, bounded geometry, mandatory neutral recovery.
t.resetHiveTelemetry();g=reset();g.sector=11;g.mode='campaign';g.elapsed=0;g.player={x:190,y:180,r:18,hp:100,maxHp:100,shield:100,maxShield:100,inv:0};g.boss={name:'SCARAB IMPERATOR',pattern:'storm',hp:900,maxHp:1000,phase:2,phaseElapsed:8,signatureAttackCd:8,signatureAttack:null,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0,x:850,y:360,r:54};const th=t.hiveStartBoss(g.boss);th.state='A3';th.confidence=.93;th.dpsProfile={fingerprint:'SUSTAINED_DOMINATION',sustainedVsExpected:2};for(let i=0;i<30;i++){g.elapsed+=.2;g.player.y=180+Math.sin(i*.85)*125;t.hiveSpatialUpdate(.2);}const spatial=t.hiveSpatialSnapshot();checks.spatialReader=spatial&&spatial.read!=='READING'&&spatial.samples>=20&&spatial.confidence>=.42;
t.hiveTacticalPilotUpdate(.1);const elig=t.hiveTacticalEligible(th,g.boss);const vec=t.hiveTacticalVector(g.boss,g.player);checks.tacticalEligible=elig.ok===true;checks.tacticalVector=vec.active===true&&Math.abs(vec.yOffset)<=390*.075+1&&Math.abs(vec.xOffset)<=844*.035+1&&vec.spreadScale>=.82&&vec.spreadScale<=1.22;
const tp=th.tacticalPilot;const v1=tp.variant,e1=tp.events.length;tp.segmentT=0;t.hiveTacticalPilotUpdate(.1);const e2=tp.events.length;tp.segmentT=0;t.hiveTacticalPilotUpdate(.1);checks.neutralRecovery=tp.active===false&&tp.variant==='NEUTRAL'&&tp.neutralSegments>=1&&e2>=e1&&v1!=='NEUTRAL';
checks.identityMatrix=Object.keys(t.HIVE_TACTICAL_IDENTITY).length===10&&t.HIVE_TACTICAL_IDENTITY.KHEPRI.variant==='ORBIT_TILT'&&t.HIVE_TACTICAL_IDENTITY.APIS.variant==='ROYAL_PRESSURE';
let identityRuntime=true,signatureRuntime=true;for(let w=11;w<=20;w++){try{g.sector=w;g.enemies=[];g.eBullets=[];g.particles=[];g.obstacles=[];g.frontThreats=[];g.player={x:180,y:230,r:18,hp:100,maxHp:100,shield:100,maxShield:100,inv:0};g.boss={name:'W'+w,pattern:'storm',hp:800,maxHp:1000,phase:2,phaseElapsed:10,signatureAttackCd:8,signatureAttack:null,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0,x:820,y:350,r:54,t:1,fire:0,identityOpacity:1};th.world=w;th.finished=false;th.finalizing=false;th.state='A3';th.confidence=.94;th.dpsProfile={fingerprint:'SUSTAINED_DOMINATION',sustainedVsExpected:2};th.tacticalPilot={active:true,variant:'TEST',segmentT:5,intensity:1,activeSegments:1,totalSegments:1,neutralSegments:0,events:[],lastReason:'test'};const id=t.bossIdentity(w);const sig=t.makeCH2IdentitySignature(g.boss,g.player,{wind:1,active:2},id);if(!sig||sig.identity!==id.key||typeof sig.tacticalVariant!=='string')signatureRuntime=false;t.updateCH2BossIdentityMovement(g.boss,g.player,t.SECTORS[w-1],.016,1);if(!Number.isFinite(g.boss.x)||!Number.isFinite(g.boss.y))identityRuntime=false;}catch(e){identityRuntime=false;signatureRuntime=false;console.error('identity runtime '+w,e.stack);}}
checks.allTenIdentityRuntime=identityRuntime;checks.allTenSignaturePlanning=signatureRuntime;
checks.noExtraProjectileContract=game.includes('noExtraProjectiles:true')&&game.includes('noHpInflation:true')&&game.includes('noDamageBoost:true')&&game.includes('noCadenceBoost:true');
checks.signatureGeometryLockedAtStart=game.includes("tacticalVariant:tactical.variant||'NEUTRAL'")&&game.includes('const tactical=hiveTacticalVector(b,p,id),sigY=')&&game.includes('s.centerY=clamp(sigY');
checks.geometryBoundsContract=game.includes('tacticalAimMax:.115')&&game.includes('tacticalYOffsetMax:.075')&&game.includes('tacticalXOffsetMax:.035')&&game.includes('clamp(delta,-HIVE_DIRECTOR_CONFIG.tacticalAimMax,HIVE_DIRECTOR_CONFIG.tacticalAimMax)');
checks.tacticalTelemetry=hstat.tacticalIdentityPilot?.enabled===true||game.includes('tacticalPilotEvents');
const hiveBlock=game.slice(game.indexOf('// v2.15.24 · ADAPTIVE HIVE BOSS DIRECTOR'),game.indexOf("let shopReturn='MENU'"));checks.localOnly=!/(fetch\s*\(|XMLHttpRequest|sendBeacon|WebSocket\s*\()/i.test(hiveBlock)&&hiveBlock.includes('localStorage.setItem(KEY_HIVE_TELEMETRY');
checks.shadowContract=hiveBlock.includes("inactiveInterventions:['reactive_armor','symbiotic_assist','rift_disruption','rift_rebirth','extra_soft_gates']")&&!hiveBlock.includes('spawnPickup(')&&!hiveBlock.includes('damageEntity(')&&!hiveBlock.includes('G.player.hp=')&&!/\bb\.hp\s*=/.test(hiveBlock);
checks.identitySafeMutation=/signatureAttackCd=/.test(hiveBlock)&&hiveBlock.includes('COEVOLUTION_SEQUENCE_PILOT')&&!/(receivedDamageMultiplier\s*\*=|bossCounterDamageMult\s*=|\bb\.maxHp\s*=|\bb\.hp\s*=|player\.powers\s*=|player\.hp\s*=)/.test(hiveBlock);
checks.hiveStatusHooks=game.includes('__SWARM_HIVE_DIRECTOR_STATUS')&&game.includes('__SWARM_HIVE_DIRECTOR_REPORT')&&game.includes('__SWARM_HIVE_DIRECTOR_SELFTEST')&&game.includes('__SWARM_HIVE_TELEMETRY_SUMMARY');
checks.ttkFormula=game.includes('Math.max(0,b.hp)/dps')&&game.includes('projected=Number.isFinite(ttk)?age+ttk:null');
checks.explicitMigration=game.includes("loadJSON('swarm_rift_meta_v21523',null)")&&game.includes("loadJSON('swarm_rift_run_v21523',null)")&&game.includes("const KEY_HIVE_TELEMETRY_PREV='swarm_rift_hive_telemetry_v21523'");


// v2.15.23 Arena Morphology: guaranteed readable corridor, telegraph, identity matrix and no extra density.
g=reset();g.sector=11;g.mode='campaign';g.elapsed=20;g.eBullets=[];g.enemies=[];g.particles=[];g.obstacles=[];g.player={x:190,y:210,r:18,hp:100,maxHp:100,shield:100,maxShield:100,inv:0};g.boss={name:'SCARAB IMPERATOR',pattern:'titan',hp:900,maxHp:1000,phase:2,phaseElapsed:10,signatureAttackCd:8,signatureAttack:null,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0,x:850,y:360,r:54,t:2,arenaCd:0,guardT:0};const ah=t.hiveStartBoss(g.boss);ah.state='A3';ah.confidence=.93;ah.dpsProfile={fingerprint:'SUSTAINED_DOMINATION',sustainedVsExpected:2};for(let i=0;i<28;i++){g.elapsed+=.2;g.player.y=210+Math.sin(i*.55)*70;t.hiveSpatialUpdate(.2);}const ae=t.hiveArenaEligible(ah,g.boss);const ap=t.hiveArenaLanePlan(g.boss,g.player);checks.arenaEligible=ae.ok===true;checks.arenaIdentityMatrix=Object.keys(t.HIVE_ARENA_IDENTITY).length===10&&t.HIVE_ARENA_IDENTITY.KHEPRI.motif==='GRAVITY_CORRIDOR'&&t.HIVE_ARENA_IDENTITY.APIS.motif==='ROYAL_CELL';checks.arenaSafeCorridor=ap.safeIndex>=0&&ap.safeIndex<4&&Math.abs(ap.safeY-ap.lanes[ap.safeIndex])<.01;const b0=g.eBullets.length,o0=g.obstacles.length;t.hiveArenaPrepare(g.boss,g.player,t.SECTORS[10]);checks.arenaTelegraph=t.hiveArenaPilotState().plan&&t.hiveArenaPilotState().telegraphs===1;t.hiveArenaPilotState().plan.telegraph=0;t.hiveArenaMorphologyUpdate(g.boss,g.player,t.SECTORS[10],.02,{cool:1});checks.arenaExecuted=t.hiveArenaPilotState().executed===1&&t.hiveArenaPilotState().events.length===1&&t.hiveArenaPilotState().plan===null;checks.arenaBudgetBounded=g.eBullets.length-b0<=60&&g.obstacles.length-o0<=4;checks.arenaCooldown=g.boss.arenaCd>=3.1;
checks.arenaSourceContracts=game.includes('safeCorridorGuaranteed:true')&&game.includes('noExtraProjectileDensity:true')&&game.includes('noExtraObstacleDensity:true')&&game.includes('arenaTelegraph:.88')&&game.includes('function hiveArenaMorphologyUpdate');
let arenaRuntime=true;for(let w=11;w<=20;w++){try{g=reset();g.sector=w;g.mode='campaign';g.eBullets=[];g.enemies=[];g.particles=[];g.obstacles=[];g.player={x:190,y:210,r:18,hp:100,maxHp:100,shield:100,maxShield:100,inv:0};const sec=t.SECTORS[w-1];g.boss={name:sec.boss,pattern:sec.pattern,hp:900,maxHp:1000,phase:2,phaseElapsed:10,signatureAttackCd:8,signatureAttack:null,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0,x:850,y:360,r:54,t:2,arenaCd:0,guardT:0};const hh=t.hiveStartBoss(g.boss);hh.state='A3';hh.confidence=.93;hh.dpsProfile={fingerprint:'SUSTAINED_DOMINATION',sustainedVsExpected:2};for(let i=0;i<20;i++){g.elapsed+=.2;g.player.y=210+Math.sin(i*.4)*55;t.hiveSpatialUpdate(.2);}const pp=t.hiveArenaLanePlan(g.boss,g.player);t.hiveArenaExecute(g.boss,g.player,sec,pp);if(!Number.isFinite(g.boss.x)||!Number.isFinite(g.boss.y)||pp.safeIndex<0||pp.safeIndex>3)arenaRuntime=false;}catch(e){arenaRuntime=false;console.error('arena runtime '+w,e.stack);}}checks.allTenArenaRuntime=arenaRuntime;


// v2.15.24 Tactical Memory + Coevolution Microsequences.
g=reset();g.sector=11;g.mode='campaign';g.elapsed=30;g.eBullets=[];g.enemies=[];g.particles=[];g.obstacles=[];g.player={x:190,y:195,r:18,hp:100,maxHp:100,shield:100,maxShield:100,inv:0};g.boss={name:'SCARAB IMPERATOR',pattern:'titan',hp:900,maxHp:1000,phase:2,phaseElapsed:12,signatureAttackCd:8,signatureAttack:null,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0,x:850,y:360,r:54,t:2,arenaCd:4,guardT:0};const ch=t.hiveStartBoss(g.boss);ch.state='A3';ch.confidence=.94;ch.dpsProfile={fingerprint:'SUSTAINED_DOMINATION',sustainedVsExpected:2,tactical:30};
for(let i=0;i<30;i++){g.elapsed+=.2;g.player.y=195;t.hiveSpatialUpdate(.2);}const csp=t.hiveSpatialSnapshot();checks.counterSpatialReady=csp&&csp.read!=='READING';for(let q=0;q<4;q++)t.hiveTacticalPilotUpdate(.2);
for(let sec=0;sec<4;sec++){g.elapsed+=1;t.hiveRecordPlayerDamage(30,true,'normal');t.hiveCounterEvolutionSample(ch,g.boss,g.elapsed-ch.startedAt,ch.dpsProfile,{active:false,reasons:[]});}
let ces=t.hiveCounterEvolutionSnapshot();checks.counterTrialStarted=!!ces?.active&&ces.active.mode==='TRIAL'&&ces.active.response;
const activeId=ces?.active?.response;const hpBefore=g.boss.hp,powersBefore=JSON.stringify(g.powers);const cev=t.hiveCounterEvolutionEffect();const cvec=t.hiveTacticalVector(g.boss,g.player);checks.counterGeometryEffect=!!cev&&cvec.counterEvolution===activeId&&Math.abs(cvec.yOffset)<=390*.075+1&&Math.abs(cvec.xOffset)<=844*.035+1;
g.elapsed+=6;t.hiveCounterEvolutionFinish(t.hiveCounterEvolutionState(),ch,g.boss,g.elapsed-ch.startedAt,ch.dpsProfile);ces=t.hiveCounterEvolutionSnapshot();checks.counterLearned=ces.successes===1&&Object.keys(ces.learned).length===1&&ces.active===null;
const learnedTactic=Object.keys(ces.learned)[0],learnedId=ces.learned[learnedTactic];t.hiveCounterEvolutionState().cooldownUntil=0;t.hiveCounterEvolutionState().currentTactic=learnedTactic;t.hiveCounterEvolutionState().streak=t.HIVE_DIRECTOR_CONFIG.counterEvolutionRepeatSamples;g.elapsed+=1;t.hiveCounterEvolutionSample(ch,g.boss,g.elapsed-ch.startedAt,ch.dpsProfile,{active:false,reasons:[]});ces=t.hiveCounterEvolutionSnapshot();checks.counterMicroSequenceStarted=ces.active?.mode==='MICRO_SEQUENCE'&&ces.active?.response===learnedId&&!!ces.active?.sequence;
const seqStartSnap=ces,seqActive=t.hiveCounterEvolutionState().active,seqSpec=t.hiveMicroSequenceSpec(t.bossIdentity(11));
checks.microSequenceMatrix=Object.keys(t.HIVE_MICRO_SEQUENCE_IDENTITY).length===10&&Object.values(t.HIVE_MICRO_SEQUENCE_IDENTITY).every(x=>x.steps?.length===3);
checks.microSequenceThreeAct=!!seqSpec&&seqSpec.steps.map(x=>x.id).join('>')==='OPEN>PRESS>CLOSE'&&t.hiveMicroSequenceDuration(seqSpec)>=4;
checks.microSequenceEffect=(()=>{const e=t.hiveCounterEvolutionEffect();return !!e&&e.microSequence===seqSpec.id&&['OPEN','PRESS','CLOSE'].includes(e.sequenceStage);})();
const seqTarget=seqActive?.tactic;if(seqActive){const sp=t.hiveSpatialState();sp.read=seqTarget==='EDGE_ANCHOR'?'CENTER_HOLD':'EDGE_ANCHOR';sp.confidence=.9;const baseAge=g.elapsed-ch.startedAt;t.hiveMicroSequenceObserve(t.hiveCounterEvolutionState(),ch,g.boss,baseAge+.10,ch.dpsProfile);t.hiveMicroSequenceObserve(t.hiveCounterEvolutionState(),ch,g.boss,baseAge+.20,ch.dpsProfile);}
ces=t.hiveCounterEvolutionSnapshot();checks.microSequenceMutates=ces.sequencesMutated===1&&ces.active?.sequenceMutated===true;
if(t.hiveCounterEvolutionState().active){const baseAge=g.elapsed-ch.startedAt;t.hiveMicroSequenceObserve(t.hiveCounterEvolutionState(),ch,g.boss,baseAge+.30,ch.dpsProfile);t.hiveMicroSequenceObserve(t.hiveCounterEvolutionState(),ch,g.boss,baseAge+.40,ch.dpsProfile);}
ces=t.hiveCounterEvolutionSnapshot();checks.microSequenceAbandons=ces.sequencesAbandoned===1&&ces.active===null&&ces.sequenceRetired[seqTarget]===true;
// Anti-stacking: active sequence blocks arena scheduling and signature priority scheduling.
t.hiveCounterEvolutionState().active={mode:'MICRO_SEQUENCE',tactic:'CENTER_HOLD',response:{...t.HIVE_COUNTER_EVOLUTION_IDENTITY.KHEPRI.responses[0],learned:true},phase:2,startedAt:g.elapsed-ch.startedAt,endsAt:g.elapsed-ch.startedAt+4,baselineDps:20,baselinePlayerDamage:0,sequence:{spec:seqSpec,decodeSamples:0,lastStageIndex:-1,mutated:false,mutationResponse:null,forceClosure:false}};
checks.microSequenceArenaAntiStack=t.hiveArenaEligible(ch,g.boss).reason==='micro_sequence_lock';
checks.microSequenceSignatureAntiStack=t.hiveMaybeSignaturePilot(ch,g.boss,g.elapsed-ch.startedAt,{fingerprint:'SUSTAINED_DOMINATION'}, {signatureDebt:1}, {active:false,reasons:[]})===false;
t.hiveCounterEvolutionState().active=null;
// Explicit failed trial retires one response instead of repeating it forever.
t.hiveCounterEvolutionState().active=null;t.hiveCounterEvolutionState().cooldownUntil=0;const failTactic=learnedTactic;const candidates=t.HIVE_COUNTER_EVOLUTION_IDENTITY.KHEPRI.responses;const alt=candidates.find(x=>x.id!==learnedId);t.hiveCounterEvolutionStart(t.hiveCounterEvolutionState(),ch,g.boss,g.elapsed-ch.startedAt,failTactic,{...alt,learned:false});const failActive=t.hiveCounterEvolutionState().active;failActive.baselineDps=10;t.hiveSpatialState().read=failTactic;t.hiveSpatialState().confidence=.9;g.elapsed+=6;for(let k=0;k<3;k++){t.hiveRecordPlayerDamage(10,true,'normal');}t.hiveCounterEvolutionFinish(t.hiveCounterEvolutionState(),ch,g.boss,g.elapsed-ch.startedAt,ch.dpsProfile);ces=t.hiveCounterEvolutionSnapshot();checks.counterRetiresFailure=ces.failures>=1&&Array.isArray(ces.retired[failTactic])&&ces.retired[failTactic].includes(alt.id);
checks.counterNoStatMutation=g.boss.hp===hpBefore&&JSON.stringify(g.powers)===powersBefore;
checks.counterIdentityMatrix=Object.keys(t.HIVE_COUNTER_EVOLUTION_IDENTITY).length===10&&t.HIVE_COUNTER_EVOLUTION_IDENTITY.KHEPRI.responses.length===3&&t.HIVE_COUNTER_EVOLUTION_IDENTITY.APIS.responses.length===3;
checks.counterBounds=t.HIVE_DIRECTOR_CONFIG.counterEvolutionMaxTrialsPerPhase===2&&t.HIVE_DIRECTOR_CONFIG.counterEvolutionMaxReuses===2&&t.HIVE_DIRECTOR_CONFIG.counterEvolutionTrialSec===5.5;
checks.counterSourceContracts=game.includes('sessionTacticalMemory:true')&&game.includes('noPersistentPlayerProfile:true')&&game.includes('noBuildMutation:true')&&game.includes('function hiveCounterEvolutionSample')&&game.includes('threeActSequences:true')&&game.includes('oneMutationBeforeAbandon:true');
const cstat=windowObj.__SWARM_V21524_STATUS();checks.counterStatusHook=cstat?.adaptiveHiveCoevolutionSequences?.counterEvolution?.enabled===true&&cstat.liveIntervention.counterEvolutionGeometry===true&&cstat.liveIntervention.coevolutionMicroSequences===true;
let counterRuntime=true,counterResponseCount=0;for(let w=11;w<=20;w++){try{g=reset();g.sector=w;g.mode='campaign';g.elapsed=40;g.eBullets=[];g.enemies=[];g.particles=[];g.obstacles=[];g.player={x:185,y:220,r:18,hp:100,maxHp:100,shield:100,maxShield:100,inv:0};const sec=t.SECTORS[w-1];g.boss={name:sec.boss,pattern:sec.pattern,hp:900,maxHp:1000,phase:2,phaseElapsed:12,signatureAttackCd:8,signatureAttack:null,dead:false,dying:false,entry:0,phaseTransitionT:0,telegraphT:0,specialT:0,chargeT:0,x:850,y:360,r:54,t:2,arenaCd:4,guardT:0};const hh=t.hiveStartBoss(g.boss);hh.state='A3';hh.confidence=.94;hh.dpsProfile={fingerprint:'SUSTAINED_DOMINATION',sustainedVsExpected:2,tactical:20};for(let i=0;i<24;i++){g.elapsed+=.2;g.player.y=220+Math.sin(i*.35)*45;t.hiveSpatialUpdate(.2);}hh.tacticalPilot={active:true,variant:'CE_TEST',segmentT:8,intensity:1,activeSegments:1,totalSegments:1,neutralSegments:0,events:[],lastReason:'test'};const id=t.bossIdentity(w),responses=t.HIVE_COUNTER_EVOLUTION_IDENTITY[id.key].responses;counterResponseCount+=responses.length;for(const r of responses){const st=t.hiveCounterEvolutionState();st.active={mode:'TRIAL',tactic:'MOBILE_MIX',response:{...r},phase:2,startedAt:0,endsAt:5,baselineDps:20,baselinePlayerDamage:0};const v=t.hiveTacticalVector(g.boss,g.player,id),lp=t.hiveArenaLanePlan(g.boss,g.player);if(v.counterEvolution!==r.id||!Number.isFinite(v.aimAngle)||Math.abs(v.yOffset)>390*.075+1||Math.abs(v.xOffset)>844*.035+1||lp.safeIndex<0||lp.safeIndex>3)counterRuntime=false;} }catch(e){counterRuntime=false;console.error('counter evolution runtime '+w,e.stack);}}
checks.allTenCounterEvolutionRuntime=counterRuntime&&counterResponseCount===30;
let sequenceRuntime=true,sequenceCount=0;for(let w=11;w<=20;w++){try{const id=t.bossIdentity(w),spec=t.hiveMicroSequenceSpec(id);sequenceCount++;if(!spec||spec.steps.length!==3||t.hiveMicroSequenceDuration(spec)<4)sequenceRuntime=false;const fake={mode:'MICRO_SEQUENCE',tactic:'MOBILE_MIX',response:{...t.HIVE_COUNTER_EVOLUTION_IDENTITY[id.key].responses[0],learned:true},phase:2,startedAt:10,endsAt:20,sequence:{spec,decodeSamples:0,lastStageIndex:-1,mutated:false,mutationResponse:null,forceClosure:false}};const a=t.hiveMicroSequenceStage(fake,10.2),m=t.hiveMicroSequenceStage(fake,11.6),z=t.hiveMicroSequenceStage(fake,14.1);if(a?.id!=='OPEN'||m?.id!=='PRESS'||z?.id!=='CLOSE')sequenceRuntime=false;}catch(e){sequenceRuntime=false;console.error('sequence runtime '+w,e.stack);}}
checks.allTenMicroSequenceRuntime=sequenceRuntime&&sequenceCount===10;

const s53=windowObj.__SWARM_V2153_STATUS(),s59=windowObj.__SWARM_V2159_STATUS(),s513=windowObj.__SWARM_V21513_STATUS(),s514=windowObj.__SWARM_V21514_STATUS(),s515=windowObj.__SWARM_V21515_STATUS(),s516=windowObj.__SWARM_V21516_STATUS(),s43=windowObj.__SWARM_V2143_HANGAR_STATUS();
checks.twentyBosses=s53.worlds===20&&s53.bosses===20;
checks.familyCombatPreserved=s53.familyCombat.enabled&&s53.familyCombat.grammars===10&&s53.familyCombat.comboPlays===10;
checks.bossIdentityPreserved=s59.bossIdentityPass.complete&&s59.bossIdentityPass.worlds.length===10;
checks.waveChoreographerPreserved=s513.waveChoreographer.enabled&&s513.waveChoreographer.worlds===10&&s513.waveChoreographer.acts===30;
checks.preBossPreserved=s514.preBossEscalation.enabled&&s514.preBossEscalation.worlds===10;
checks.arenaPresentationPreserved=s515.bossArenaPresentation.enabled&&s515.bossArenaPresentation.worlds===10;
checks.aftermathPreserved=s516.bossDeathAftermath.enabled&&s516.bossDeathAftermath.worlds===10;
checks.hangarPreserved=s43.powers.total>=19&&s43.fusion.combos>0&&s43.branches.available>0;
checks.commanderConvergencePreserved=game.includes('function updateCommanderConvergence');
checks.waveObjectivesPreserved=game.includes('function prepareWaveObjective')&&game.includes('function updateWaveObjective');
checks.bossRushPreserved=game.includes('function startBossRush')&&game.includes('function startGrandBossRush');
checks.chasePreserved=game.includes('function startChase')||game.includes("mode:'chase'");
checks.rewardLedgerPreserved=game.includes('rewardLedger:{credits:{},xp:{}}');
checks.checkpointsPreserved=game.includes('bossCheckpoint')&&game.includes('saveRun()');
checks.audioPreserved=game.includes('Enemy Sonic Ecology')||game.includes('enemyAudioStatus');

const passed=Object.values(checks).filter(Boolean).length,total=Object.keys(checks).length,ok=passed===total;console.log(JSON.stringify({ok,summary:{passed,total},checks,ergonomics:es,bounds:b,rail,routed},null,2));process.exit(ok?0:4);
