const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
function noop(){} function makeCtx(){const t={measureText:x=>({width:String(x??'').length*6.4}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),createPattern:()=>({}),getImageData:()=>({data:new Uint8ClampedArray(4)}),canvas:null};return new Proxy(t,{get:(o,k)=>k in o?o[k]:noop,set:(o,k,v)=>(o[k]=v,true)});}const ctx=makeCtx();
function el(id){return {id,style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},addEventListener:noop,removeEventListener:noop,setAttribute:noop,getAttribute:()=>null,play:()=>Promise.resolve(),pause:noop,load:noop,currentTime:0,duration:180,volume:1,muted:false,paused:true,loop:false,src:'',getBoundingClientRect:()=>id==='topActions'?({left:585,top:6,width:253,height:44,right:838,bottom:50}):({left:0,top:0,width:844,height:390,right:844,bottom:390})};}
const els=new Map(),getEl=id=>{if(!els.has(id)){const e=el(id);if(id==='game'){e.getContext=()=>ctx;e.width=1280;e.height=720;ctx.canvas=e;}els.set(id,e);}return els.get(id)};
const document={getElementById:getEl,querySelector:()=>el('q'),querySelectorAll:()=>[],createElement:t=>el(t),documentElement:{style:{},requestFullscreen:()=>Promise.resolve(),clientWidth:1280,clientHeight:720},body:el('body'),fullscreenElement:null,addEventListener:noop,removeEventListener:noop,visibilityState:'visible'};
class Img{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1024;this._src='';}set src(v){this._src=v}get src(){return this._src}addEventListener(){}} class Aud{constructor(){this.currentTime=0;this.duration=180;this.volume=1;this.paused=true;this.loop=false;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}addEventListener(){}removeEventListener(){}load(){}}
const visualViewport={width:1280,height:720,addEventListener:noop},navigator={serviceWorker:{register:()=>Promise.resolve({})},hardwareConcurrency:4,deviceMemory:4,maxTouchPoints:0},location={protocol:'file:',href:'file:///game/index.html'},screen={orientation:{lock:()=>Promise.resolve()}},performance={now:()=>1000};
const windowObj={document,visualViewport,devicePixelRatio:2,innerWidth:1280,innerHeight:720,navigator,location,screen,performance,addEventListener:noop,removeEventListener:noop,matchMedia:q=>({matches:q.includes('pointer:coarse')?!!windowObj.__coarse:false,addEventListener:noop,removeEventListener:noop}),setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:noop,cancelAnimationFrame:noop,localStorage,Audio:Aud,Image:Img};windowObj.__coarse=false;windowObj.window=windowObj;windowObj.self=windowObj;
const sb={...windowObj,window:windowObj,self:windowObj,globalThis:windowObj,document,navigator,location,screen,performance,visualViewport,localStorage,Audio:Aud,Image:Img,console,Math,Date,JSON,Promise,Map,Set,WeakMap,Uint8ClampedArray,Intl};sb.matchMedia=windowObj.matchMedia;sb.addEventListener=noop;sb.removeEventListener=noop;vm.createContext(sb);
let src=fs.readFileSync(path.join(root,'js/game.js'),'utf8');src=src.replace(/\}\)\(\);\s*$/,`window.__T={VERSION,SECTORS,META,getG:()=>G,setViewport:(w,h,c=false)=>{W=w;H=h;window.__coarse=c;},setSafe:(top,right,bottom,left)=>{SAFE_AREA={top,right,bottom,left};},uiProfile,compactUI,hudFocusMode,hudPriorityStatus,hudPresentationStatus,syncHudPresentation,drawHUD,drawInsect,setScreen,hasSave,loadRun,topActions,shopBtn,playerCombatBounds,actionRailExclusion,touchStartExcluded,sanitizeTouchPoint,mobileErgonomicsStatus,safeHudCenterX};})();`);vm.runInContext(src,sb,{timeout:10000});const t=windowObj.__T;if(!t)throw Error('hook');
const profiles=[
 {name:'iphone-landscape-notch',w:844,h:390,c:true,s:[0,47,21,47],expect:'MOBILE_LANDSCAPE'},
 {name:'compact-landscape-notch',w:667,h:375,c:true,s:[0,44,21,44],expect:'MOBILE_LANDSCAPE'},
 {name:'android-landscape',w:915,h:412,c:true,s:[0,0,0,0],expect:'MOBILE_LANDSCAPE'},
 {name:'tablet-landscape',w:1180,h:820,c:true,s:[0,0,0,0],expect:'TABLET'},
 {name:'mobile-portrait',w:390,h:844,c:true,s:[47,0,34,0],expect:'MOBILE_PORTRAIT'}
];
const results=[];let ok=true;
for(const p of profiles){const [top,right,bottom,left]=p.s;t.setViewport(p.w,p.h,p.c);t.setSafe(top,right,bottom,left);const b=t.playerCombatBounds(),rail=t.actionRailExclusion(8),a=t.sanitizeTouchPoint(-100,-100),z=t.sanitizeTouchPoint(p.w+100,p.h+100);const checks={profile:t.uiProfile()===p.expect,bounds:b.left>=left&&b.right<=p.w-right&&b.top>=Math.min(44,top+38)&&b.bottom<=p.h-Math.min(34,bottom+28),usableW:b.right-b.left>=Math.min(120,p.w*.50),usableH:b.bottom-b.top>=Math.min(100,p.h*.60),clampA:a.x>=b.left&&a.y>=b.top,clampZ:z.x<=b.right&&z.y<=b.bottom,railSane:rail.left>=0&&rail.right<=p.w&&rail.bottom<=p.h&&rail.left<rail.right,center:t.safeHudCenterX()>=left&&t.safeHudCenterX()<=p.w-right};for(const v of Object.values(checks))if(!v)ok=false;results.push({...p,bounds:b,rail,checks});}
console.log(JSON.stringify({ok,profiles:results,status:t.mobileErgonomicsStatus()},null,2));process.exit(ok?0:4);
