/* ═══════════════════════════════════════════════════════════
   PequeWorld — VOCABULARIO NIVEL 3 “Héroe” (6–7 años)
   ═══════════════════════════════════════════════════════════ */
WORLDS.push(
  /* ── FULL ALPHABET ── */
  {id:'letters_full', name:'Alphabet', es:'Alfabeto completo', icon:'🏙️', color:'wc-letters', lvl:3, kind:'letters',
   story:'En la Ciudad del Alfabeto juntas todas las letras. ¡Ahora sí: de A a Z!',
   items:[
    {en:'A',es:'A', img:'apple',    em:'🍎', hint:'A de Apple'},
    {en:'B',es:'B', img:'bee',      em:'🐝', hint:'B de Bee'},
    {en:'C',es:'C', img:'cat',      em:'🐱', hint:'C de Cat'},
    {en:'D',es:'D', img:'dog',      em:'🐶', hint:'D de Dog'},
    {en:'E',es:'E', img:'egg',      em:'🥚', hint:'E de Egg'},
    {en:'F',es:'F', img:'frog',     em:'🐸', hint:'F de Frog'},
    {en:'G',es:'G', img:'grapes',   em:'🍇', hint:'G de Grapes'},
    {en:'H',es:'H', img:'house',    em:'🏠', hint:'H de House'},
    {en:'I',es:'I', img:'icecream', em:'🍦', hint:'I de Ice cream'},
    {en:'J',es:'J', img:'controller',em:'🕹️', hint:'J de Joystick'},
    {en:'K',es:'K', img:'key',      em:'🔑', hint:'K de Key'},
    {en:'L',es:'L', img:'lion',     em:'🦁', hint:'L de Lion'},
    {en:'M',es:'M', img:'moon',     em:'🌙', hint:'M de Moon'},
    {en:'N',es:'N', img:'notes',    em:'🎵', hint:'N de Note'},
    {en:'O',es:'O', img:'octopus',  em:'🐙', hint:'O de Octopus'},
    {en:'P',es:'P', img:'penguin',  em:'🐧', hint:'P de Penguin'},
    {en:'Q',es:'Q', img:'queen',    em:'👑', hint:'Q de Queen'},
    {en:'R',es:'R', img:'rainbow',  em:'🌈', hint:'R de Rainbow'},
    {en:'S',es:'S', img:'sun',      em:'☀️', hint:'S de Sun'},
    {en:'T',es:'T', img:'turtle',   em:'🐢', hint:'T de Turtle'},
    {en:'U',es:'U', img:'umbrella', em:'☂️', hint:'U de Umbrella'},
    {en:'V',es:'V', img:'violin',   em:'🎻', hint:'V de Violin'},
    {en:'W',es:'W', img:'wave',     em:'🌊', hint:'W de Wave'},
    {en:'X',es:'X', img:'xylophone',em:'🎸', hint:'X de Xylophone'},
    {en:'Y',es:'Y', img:'yarn',     em:'🧶', hint:'Y de Yarn'},
    {en:'Z',es:'Z', img:'lightning',em:'⚡', hint:'Z de Zap'},
   ]},

  /* ── NUMBERS 21–30 ── */
  {id:'numbers_21_30', name:'Numbers 21–30', es:'Números 21–30', icon:'🧠', color:'wc-numbers', lvl:3, kind:'numbers',
   story:'Desafío final: del 21 al 30. Ya cuentas como un campeón.',
   items:[
    {en:'Twenty-one',  es:'Veintiuno',  num:21},
    {en:'Twenty-two',  es:'Veintidós',  num:22},
    {en:'Twenty-three',es:'Veintitrés', num:23},
    {en:'Twenty-four', es:'Veinticuatro',num:24},
    {en:'Twenty-five', es:'Veinticinco',num:25},
    {en:'Twenty-six',  es:'Veintiséis', num:26},
    {en:'Twenty-seven',es:'Veintisiete',num:27},
    {en:'Twenty-eight',es:'Veintiocho', num:28},
    {en:'Twenty-nine', es:'Veintinueve',num:29},
    {en:'Thirty',      es:'Treinta',    num:30},
   ]},

  /* ── HOME ── */
  {id:'home', name:'Home', es:'Casa', icon:'🏠', color:'wc-home', lvl:3, kind:'words',
   story:'En la Casa Secreta encuentras objetos. Nombres simples, muy cotidianos.',
   items:[
    {en:'Door', es:'Puerta',    img:'door',  em:'🚪'},
    {en:'Window',es:'Ventana',  img:'window',em:'🪟'},
    {en:'Chair',es:'Silla',     img:'chair', em:'🪑'},
    {en:'Bed',  es:'Cama',      img:'bed',   em:'🛏️'},
    {en:'Lamp', es:'Lámpara',   img:'lamp',  em:'💡'},
    {en:'TV',   es:'Televisor', img:'tv',    em:'📺'},
    {en:'Book', es:'Libro',     img:'book',  em:'📘'},
    {en:'Toy',  es:'Juguete',   img:'teddy', em:'🧸'},
   ]},

  /* ── BODY ── */
  {id:'body', name:'Body', es:'Cuerpo', icon:'🧍', color:'wc-body', lvl:3, kind:'words',
   story:'En el Robot Amigo aprendes partes del cuerpo con fotos claras.',
   items:[
    {en:'Head', es:'Cabeza',  img:'face_happy',em:'🙂'},
    {en:'Eye',  es:'Ojo',     img:'eye',       em:'👁️'},
    {en:'Nose', es:'Nariz',   img:'nose',      em:'👃'},
    {en:'Mouth',es:'Boca',    img:'mouth',     em:'👄'},
    {en:'Ear',  es:'Oreja',   img:'ear',       em:'👂'},
    {en:'Hand', es:'Mano',    img:'hand',      em:'✋'},
    {en:'Foot', es:'Pie',     img:'foot',      em:'🦶'},
    {en:'Heart',es:'Corazón', img:'heart',     em:'❤️'},
    {en:'Arm',    es:'Brazo',   img:'arm',    em:'💪'},
    {en:'Leg',    es:'Pierna',  img:'leg',    em:'🦵'},
    {en:'Finger', es:'Dedo',    img:'finger', em:'👆'},
    {en:'Teeth',  es:'Dientes', img:'teeth',  em:'🦷'},
    {en:'Knee',   es:'Rodilla', img:'knee',   em:'🦵'},
    {en:'Shoulder',es:'Hombro', img:'shoulder',em:'🙆'},
   ]},

  /* ── WEATHER ── */
  {id:'weather', name:'Weather', es:'Clima', icon:'⛅', color:'wc-weather', lvl:3, kind:'words',
   story:'En el Cielo Cambiante identificas el clima con fotos reales.',
   items:[
    {en:'Sun',    es:'Sol',     img:'sun',     em:'☀️'},
    {en:'Rain',   es:'Lluvia',  img:'rain',    em:'🌧️'},
    {en:'Cloud',  es:'Nube',    img:'cloud',   em:'☁️'},
    {en:'Snow',   es:'Nieve',   img:'snow',    em:'❄️'},
    {en:'Wind',   es:'Viento',  img:'kite',    em:'💨'},
    {en:'Rainbow',es:'Arcoíris',img:'rainbow', em:'🌈'},
    {en:'Fog',    es:'Niebla',  img:'fog',     em:'🌫️'},
    {en:'Storm',  es:'Tormenta',img:'storm',   em:'⛈️'},
    {en:'Lightning',es:'Relámpago',img:'lightning',em:'⚡'},
    {en:'Umbrella',es:'Paraguas',img:'umbrella',em:'☂️'},
   ]},

  /* ── EMOTIONS (hero) ── */
  {id:'emotions_hero', name:'Emotions Pro', es:'Emociones (pro)', icon:'🧠', color:'wc-phrases', lvl:3, kind:'words',
   story:'En la Academia de Emociones nombramos sensaciones más complejas.',
   items:[
    {en:'Grateful',  es:'Agradecido', img:'hearthands',    em:'🙏', hint:'Gracias'},
    {en:'Confused',  es:'Confundido', img:'face_confused', em:'😵', hint:'¿Eh?'},
    {en:'Frustrated',es:'Frustrado',  img:'face_angry',    em:'😣', hint:'No sale'},
    {en:'Brave',     es:'Valiente',   img:'herokid',       em:'🛡️', hint:'Me animo'},
    {en:'Lonely',    es:'Solo',       img:'face_sad',      em:'🥺', hint:'Necesito'},
    {en:'Curious',   es:'Curioso',    img:'face_surprised',em:'🧐', hint:'Quiero saber'},
    {en:'Relaxed',   es:'Relajado',   img:'face_calm',     em:'🧘', hint:'Calma'},
    {en:'Excited',   es:'Emocionado', img:'face_excited',  em:'😬', hint:'¡Wii!'},
    {en:'Proud',     es:'Orgulloso',  img:'face_proud',    em:'🏅', hint:'Lo logré'},
    {en:'Kind',      es:'Amable',     img:'heart',         em:'💗', hint:'Cuido'},
   ]},

  /* ── PETS (advanced) ── */
  {id:'pets_advanced', name:'Pets Pro', es:'Mascotas (pro)', icon:'🏥', color:'wc-animals', lvl:3, kind:'words',
   story:'En el Centro de Mascotas aprendemos palabras de cuidado y rutinas.',
   items:[
    {en:'Vet',    es:'Veterinario',img:'vet',      em:'🏥', hint:'Clínica'},
    {en:'Vaccine',es:'Vacuna',     img:'syringe',  em:'💉', hint:'Protege'},
    {en:'Bath',   es:'Baño',       img:'bath',     em:'🧼', hint:'Limpio'},
    {en:'Brush',  es:'Cepillo',    img:'brush',    em:'🪥', hint:'Peinar'},
    {en:'Collar', es:'Collar',     img:'leash',    em:'📿', hint:'Cuello'},
    {en:'Treat',  es:'Premio',     img:'bone',     em:'🦴', hint:'Buen perro'},
    {en:'Adopt',  es:'Adoptar',    img:'house',    em:'🏡', hint:'Nuevo hogar'},
    {en:'Train',  es:'Entrenar',   img:'dog',      em:'🎯', hint:'Aprender'},
    {en:'Walk',   es:'Pasear',     img:'kid_run',  em:'🚶', hint:'Caminar'},
    {en:'Play',   es:'Jugar',      img:'ball',     em:'🪀', hint:'Diversión'},
   ]},

  /* ── PRINCESS (story) ── */
  {id:'princess_story', name:'Royal Story', es:'Historia real', icon:'📜', color:'wc-home', lvl:3, kind:'words',
   story:'En el Libro del Castillo armamos una mini-historia con palabras del reino.',
   items:[
    {en:'Palace',  es:'Palacio', img:'castle',       em:'🏰', hint:'Reino'},
    {en:'Guard',   es:'Guardia', img:'helmet',       em:'💂', hint:'Cuida'},
    {en:'Bridge',  es:'Puente',  img:'bridge',       em:'🌉', hint:'Cruza'},
    {en:'Dragon',  es:'Dragón',  img:'dragon',       em:'🐲', hint:'Fantástico'},
    {en:'Princess',es:'Princesa',img:'princess',     em:'👸', hint:'Real'},
    {en:'Crown',   es:'Corona',  img:'crown',        em:'👑', hint:'Rey/Reina'},
    {en:'Secret',  es:'Secreto', img:'key',          em:'🗝️', hint:'Llave'},
    {en:'Treasure',es:'Tesoro',  img:'ui_chest_open',em:'🪙', hint:'Oro'},
    {en:'Forest',  es:'Bosque',  img:'tree',         em:'🌲', hint:'Árboles'},
    {en:'Spell',   es:'Hechizo', img:'wand',         em:'🪄', hint:'Magia'},
   ]},

  /* ── SUPERHERO (mission) ── */
  {id:'superhero_mission', name:'Hero Mission', es:'Misión héroe', icon:'🏙️', color:'wc-words', lvl:3, kind:'words',
   story:'En la Mega-Ciudad usamos palabras para describir una misión de rescate.',
   items:[
    {en:'Rescue', es:'Rescatar', img:'ambulance', em:'🚁', hint:'Heli'},
    {en:'Fly',    es:'Volar',    img:'eagle',     em:'🧗', hint:'Cielo'},
    {en:'Protect',es:'Proteger', img:'shield',    em:'🛡️', hint:'Escudo'},
    {en:'Help',   es:'Ayudar',   img:'raisedhand',em:'🤝', hint:'Mano'},
    {en:'Fast',   es:'Rápido',   img:'racecar',   em:'🏎️', hint:'Carrera'},
    {en:'Quiet',  es:'Silencio', img:'face_sleepy',em:'🤫', hint:'Shh'},
    {en:'Danger', es:'Peligro',  img:'lightning', em:'⚠️', hint:'Cuidado'},
    {en:'Safe',   es:'Seguro',   img:'thumbsup',  em:'🟢', hint:'Ok'},
    {en:'Team',   es:'Equipo',   img:'handshake', em:'👥', hint:'Juntos'},
    {en:'Victory',es:'Victoria', img:'ui_trophy', em:'🏆', hint:'Ganar'},
   ]},

  /* ── UNIVERSE (science) ── */
  {id:'universe_science', name:'Space Lab', es:'Laboratorio espacial', icon:'🔭', color:'wc-weather', lvl:3, kind:'words',
   story:'En el Laboratorio Espacial aparecen palabras científicas fáciles.',
   items:[
    {en:'Telescope',es:'Telescopio',img:'telescope',em:'🔭', hint:'Mirar'},
    {en:'Comet',    es:'Cometa',    img:'comet',    em:'🌠', hint:'Cae'},
    {en:'Crater',   es:'Cráter',    img:'moon',     em:'🕳️', hint:'Hueco'},
    {en:'Orbit',    es:'Órbita',    img:'satellite',em:'🔄', hint:'Vuelta'},
    {en:'Gravity',  es:'Gravedad',  img:'apple',    em:'🧲', hint:'Jala'},
    {en:'Planet',   es:'Planeta',   img:'planet',   em:'🪐', hint:'Mundo'},
    {en:'Moon',     es:'Luna',      img:'moon',     em:'🌕', hint:'Redonda'},
    {en:'Sun',      es:'Sol',       img:'sun',      em:'☀️', hint:'Energía'},
    {en:'Rocket',   es:'Cohete',    img:'rocket',   em:'🚀', hint:'Viaja'},
    {en:'Astronaut',es:'Astronauta',img:'astronaut',em:'👨‍🚀', hint:'Traje'},
   ]},

  /* ── DINOSAURS (jurassic) ── */
  {id:'dinos_jurassic', name:'Jurassic', es:'Jurásico', icon:'🌋', color:'wc-animals', lvl:3, kind:'words',
   story:'En la Isla Jurásica combinamos dinosaurios con lugares y acciones.',
   items:[
    {en:'Jurassic', es:'Jurásico',  img:'jungle',    em:'🗓️', hint:'Hace mucho'},
    {en:'Volcano',  es:'Volcán',    img:'volcano',   em:'🌋', hint:'Lava'},
    {en:'Footprint',es:'Huella',    img:'footprint', em:'👣', hint:'Pasos'},
    {en:'T-Rex',    es:'T-Rex',     img:'trex',      em:'🦖', hint:'Rey'},
    {en:'Roar',     es:'Rugir',     img:'lion',      em:'📣', hint:'Fuerte'},
    {en:'Hunt',     es:'Cazar',     img:'eagle',     em:'🏹', hint:'Buscar'},
    {en:'Gigantic', es:'Gigante',   img:'elephant',  em:'🦣', hint:'Enorme'},
    {en:'Fast',     es:'Rápido',    img:'kid_run',   em:'🏃‍♂️', hint:'Corre'},
    {en:'Dinosaur', es:'Dinosaurio',img:'dinosaur',  em:'🦖', hint:'Grande'},
    {en:'Fossil',   es:'Fósil',     img:'fossil',    em:'🦴', hint:'Antiguo'},
   ]},

  /* ── ELEMENTS (science) ── */
  {id:'elements_science', name:'Elements Lab', es:'Elementos (ciencia)', icon:'⚡', color:'wc-weather', lvl:3, kind:'words',
   story:'En el Laboratorio de Energía aprendemos palabras de fuerzas y fenómenos.',
   items:[
    {en:'Electric',es:'Eléctrico',img:'lightning', em:'⚡', hint:'Chispa'},
    {en:'Magnet',  es:'Imán',     img:'magnet',    em:'🧲', hint:'Pega'},
    {en:'Energy',  es:'Energía',  img:'battery',   em:'🔋', hint:'Batería'},
    {en:'Light',   es:'Luz',      img:'lamp',      em:'🔦', hint:'Enciende'},
    {en:'Sound',   es:'Sonido',   img:'speaker',   em:'🔊', hint:'Escuchar'},
    {en:'Heat',    es:'Calor',    img:'fire',      em:'🌡️', hint:'Sube'},
    {en:'Cold',    es:'Frío',     img:'ice',       em:'🥶', hint:'Brr'},
    {en:'Steam',   es:'Vapor',    img:'cloud',     em:'♨️', hint:'Sale'},
    {en:'Shadow',  es:'Sombra',   img:'shadow',    em:'🌑', hint:'Oscuro'},
    {en:'Spark',   es:'Chispa',   img:'fireworks', em:'✨', hint:'Brilla'},
   ]},

  /* ── TOYS (games) ── */
  {id:'toys_games', name:'Games', es:'Juegos (pro)', icon:'🎲', color:'wc-words', lvl:3, kind:'words',
   story:'En la Sala de Juegos practicamos palabras de juegos y objetos.',
   items:[
    {en:'Board game',es:'Juego de mesa',img:'boardgame',em:'🎲', hint:'Dados'},
    {en:'Dice',      es:'Dado',        img:'dice',     em:'🎲', hint:'Lanza'},
    {en:'Marbles',   es:'Canicas',     img:'marbles',  em:'🔵', hint:'Bolitas'},
    {en:'Puzzle',    es:'Puzzle',      img:'puzzle',   em:'🧩', hint:'Encaja'},
    {en:'Robot',     es:'Robot',       img:'robot',    em:'🤖', hint:'Máquina'},
    {en:'Teddy',     es:'Osito',       img:'teddy',    em:'🧸', hint:'Abrazo'},
    {en:'Xylophone', es:'Xilófono',    img:'xylophone',em:'🎶', hint:'Notas'},
    {en:'Yo-yo',     es:'Yo-yo',       img:'yoyo',     em:'🪀', hint:'Gira'},
    {en:'Controller',es:'Control',     img:'controller',em:'🕹️', hint:'Palanca'},
    {en:'Trophy',    es:'Trofeo',      img:'ui_trophy',em:'🏆', hint:'Ganar'},
   ]},

  /* ── BIRTHDAY (story) ── */
  {id:'birthday_story', name:'Birthday Story', es:'Historia de cumple', icon:'🪅', color:'wc-food', lvl:3, kind:'words',
   story:'En la Fiesta Sorpresa armamos frases con palabras de celebración.',
   items:[
    {en:'Surprise',es:'Sorpresa', img:'gift',      em:'🎊', hint:'¡Tadaa!'},
    {en:'Wish',    es:'Deseo',    img:'wish',      em:'🌠', hint:'Pedir'},
    {en:'Candle',  es:'Vela',     img:'candle',    em:'🕯️', hint:'Soplar'},
    {en:'Cake',    es:'Torta',    img:'cake',      em:'🎂', hint:'Dulce'},
    {en:'Party',   es:'Fiesta',   img:'confetti',  em:'🎉', hint:'Celebrar'},
    {en:'Friends', es:'Amigos',   img:'friends',   em:'🧑‍🤝‍🧑', hint:'Conmigo'},
    {en:'Balloon', es:'Globo',    img:'balloon',   em:'🎈', hint:'Vuela'},
    {en:'Music',   es:'Música',   img:'notes',     em:'🎶', hint:'Sonar'},
    {en:'Dance',   es:'Bailar',   img:'kid_dance', em:'🕺', hint:'Mover'},
    {en:'Hug',     es:'Abrazo',   img:'hug',       em:'🤗', hint:'Cariño'},
   ]},

  /* ── JOBS (future) ── */
  {id:'jobs_future', name:'Future Jobs', es:'Trabajos del futuro', icon:'💻', color:'wc-home', lvl:3, kind:'words',
   story:'En el Taller del Futuro aparecen profesiones y herramientas modernas.',
   items:[
    {en:'Programmer',es:'Programador',img:'laptop',       em:'💻', hint:'Código'},
    {en:'Designer',  es:'Diseñador',  img:'paintpalette', em:'🎨', hint:'Crea'},
    {en:'Doctor',    es:'Doctor',     img:'doctor',       em:'🩺', hint:'Salud'},
    {en:'Architect', es:'Arquitecto', img:'house',        em:'🏗️', hint:'Planos'},
    {en:'Reporter',  es:'Reportero',  img:'microphone',   em:'🎤', hint:'Noticias'},
    {en:'Chef',      es:'Chef',       img:'chef',         em:'👨‍🍳', hint:'Cocina'},
    {en:'Scientist', es:'Científico', img:'scientist',    em:'🔬', hint:'Investiga'},
    {en:'Mechanic',  es:'Mecánico',   img:'mechanic',     em:'🔧', hint:'Arregla'},
    {en:'Pilot',     es:'Piloto',     img:'pilot',        em:'✈️', hint:'Vuela'},
    {en:'Teacher',   es:'Profesor',   img:'teacher',      em:'📚', hint:'Enseña'},
   ]},

  /* ── 🍜 WORLD FOOD ── */
  {id:'food_advanced', name:'World Food', es:'Comida del mundo', icon:'🍜', color:'wc-food', lvl:3, kind:'words',
   story:'En el Festival Gastronómico probamos platos de todo el mundo con sus nombres en inglés.',
   items:[
    {en:'Sushi',   es:'Sushi',          img:'sushi',    em:'🍣', hint:'Japón'},
    {en:'Taco',    es:'Taco',           img:'taco',     em:'🌮', hint:'México'},
    {en:'Pasta',   es:'Pasta',          img:'pasta',    em:'🍝', hint:'Italia'},
    {en:'Burger',  es:'Hamburguesa',    img:'burger',   em:'🍔', hint:'USA'},
    {en:'Hot dog', es:'Perro caliente', img:'hotdog',   em:'🌭', hint:'Mostaza'},
    {en:'Sandwich',es:'Sándwich',       img:'sandwich', em:'🥪', hint:'Pan'},
    {en:'Soup',    es:'Sopa',           img:'soup',     em:'🍲', hint:'Caliente'},
    {en:'Salad',   es:'Ensalada',       img:'salad',    em:'🥗', hint:'Verde'},
    {en:'Fries',   es:'Papas fritas',   img:'fries',    em:'🍟', hint:'Crujiente'},
    {en:'Popcorn', es:'Palomitas',      img:'popcorn',  em:'🍿', hint:'Cine'},
   ]},

  /* ── 🏠 ROOMS ── */
  {id:'rooms_advanced', name:'Rooms', es:'Los cuartos', icon:'🛋️', color:'wc-home', lvl:3, kind:'words',
   story:'En la Casa Exploradora conocemos cada cuarto y los objetos que hay dentro.',
   items:[
    {en:'Kitchen',   es:'Cocina',    img:'kitchen',em:'🍳', hint:'Cocinar'},
    {en:'Bedroom',   es:'Dormitorio',img:'bedroom',em:'🛏️', hint:'Dormir'},
    {en:'Bathroom',  es:'Baño',      img:'bathroom',em:'🚿', hint:'Lavar'},
    {en:'Living room',es:'Sala',     img:'sofa',   em:'🛋️', hint:'Descansar'},
    {en:'Garage',    es:'Garaje',    img:'garage', em:'🚗', hint:'Carro'},
    {en:'Garden',    es:'Jardín',    img:'garden', em:'🌷', hint:'Plantas'},
    {en:'Staircase', es:'Escalera',  img:'stairs', em:'🪜', hint:'Sube'},
    {en:'Roof',      es:'Techo',     img:'house',  em:'🏠', hint:'Arriba'},
    {en:'Study',     es:'Estudio',   img:'book',   em:'📦', hint:'Leer'},
    {en:'Playroom',  es:'Sala de juegos',img:'ball',em:'🧸', hint:'Jugar'},
   ]},

  /* ── 🌎 COUNTRIES ── */
  {id:'countries_basic', name:'Countries', es:'Países', icon:'🌎', color:'wc-travel', lvl:3, kind:'words',
   story:'En el Globo Terráqueo viajamos por los países más fascinantes del mundo.',
   items:[
    {en:'Colombia', es:'Colombia',       img:'flag_colombia', em:'🇨🇴', hint:'Café'},
    {en:'Mexico',   es:'México',         img:'flag_mexico',   em:'🇲🇽', hint:'Tacos'},
    {en:'USA',      es:'Estados Unidos', img:'flag_usa',      em:'🇺🇸', hint:'NY'},
    {en:'France',   es:'Francia',        img:'flag_france',   em:'🇫🇷', hint:'París'},
    {en:'Japan',    es:'Japón',          img:'flag_japan',    em:'🇯🇵', hint:'Sushi'},
    {en:'Brazil',   es:'Brasil',         img:'flag_brazil',   em:'🇧🇷', hint:'Samba'},
    {en:'Australia',es:'Australia',      img:'flag_australia',em:'🇦🇺', hint:'Canguro'},
    {en:'Italy',    es:'Italia',         img:'flag_italy',    em:'🇮🇹', hint:'Pasta'},
    {en:'Spain',    es:'España',         img:'flag_spain',    em:'🇪🇸', hint:'Flamenco'},
    {en:'China',    es:'China',          img:'flag_china',    em:'🇨🇳', hint:'Muralla'},
   ]},

  /* ── ⏰ TIME & DAYS (cards tipográficas) ── */
  {id:'time_days', name:'Time & Days', es:'Tiempo y días', icon:'⏰', color:'wc-numbers', lvl:3, kind:'words',
   story:'En el Reloj Mágico aprendemos los días de la semana y las palabras del tiempo.',
   items:[
    {en:'Monday',   es:'Lunes',    em:'🌙', tint:'#8E7CC3'},
    {en:'Tuesday',  es:'Martes',   em:'🍎', tint:'#E74C3C'},
    {en:'Wednesday',es:'Miércoles',em:'🌿', tint:'#27AE60'},
    {en:'Thursday', es:'Jueves',   em:'🌟', tint:'#F1C40F'},
    {en:'Friday',   es:'Viernes',  em:'🎉', tint:'#FF6B9D'},
    {en:'Saturday', es:'Sábado',   em:'⛺', tint:'#3498DB'},
    {en:'Sunday',   es:'Domingo',  em:'☀️', tint:'#FF8C42'},
    {en:'Today',    es:'Hoy',      img:'calendar',em:'📅', hint:'Ahora'},
    {en:'Tomorrow', es:'Mañana',   img:'sunrise', em:'🌅', hint:'Después'},
    {en:'Yesterday',es:'Ayer',     img:'sunset',  em:'🌇', hint:'Antes'},
   ]},

  /* ── 🌡️ SCIENCE WORDS ── */
  {id:'science_words', name:'Science', es:'Ciencia', icon:'🔬', color:'wc-weather', lvl:3, kind:'words',
   story:'En el Laboratorio Científico aprendemos palabras de experimentos y descubrimientos.',
   items:[
    {en:'Experiment',es:'Experimento',img:'scientist', em:'🧪', hint:'Probar'},
    {en:'Microscope',es:'Microscopio',img:'microscope',em:'🔬', hint:'Ver chico'},
    {en:'Magnet',    es:'Imán',       img:'magnet',    em:'🧲', hint:'Atrae'},
    {en:'Discover',  es:'Descubrir',  img:'map',       em:'🗺️', hint:'¡Hallazgo!'},
    {en:'Planet',    es:'Planeta',    img:'planet',    em:'🪐', hint:'Espacio'},
    {en:'Fossil',    es:'Fósil',      img:'fossil',    em:'🦴', hint:'Antiguo'},
    {en:'Robot',     es:'Robot',      img:'robot',     em:'🤖', hint:'Máquina'},
    {en:'Energy',    es:'Energía',    img:'battery',   em:'🔋', hint:'Fuerza'},
    {en:'Nature',    es:'Naturaleza', img:'tree',      em:'🌿', hint:'Vida'},
    {en:'Invention', es:'Invención',  img:'lamp',      em:'💡', hint:'Idea nueva'},
   ]},

  /* ── 👋 GREETINGS PRO ── */
  {id:'greetings_pro', name:'Hello & Bye!', es:'Saludos y frases', icon:'👋', color:'wc-phrases', lvl:3, kind:'phrases',
   story:'En la Estación de Saludos aprendemos frases cortas para hablar con todos en inglés.',
   items:[
    {en:'Good morning!',    es:'¡Buenos días!', img:'sunrise',   em:'🌅'},
    {en:'Good night!',      es:'¡Buenas noches!',img:'moon',     em:'🌙'},
    {en:'How are you?',     es:'¿Cómo estás?',  img:'face_confused',em:'🤔'},
    {en:'I am fine!',       es:'¡Estoy bien!',  img:'face_happy',em:'😊'},
    {en:'See you later!',   es:'¡Hasta luego!', img:'waving',    em:'👋'},
    {en:'Nice to meet you!',es:'¡Mucho gusto!', img:'handshake', em:'🤝'},
    {en:'Thank you!',       es:'¡Gracias!',     img:'hearthands',em:'🌟'},
    {en:'You are welcome!', es:'¡De nada!',     img:'openhands', em:'🙌'},
    {en:'Good luck!',       es:'¡Buena suerte!',img:'ladybug',   em:'🍀'},
    {en:'Have fun!',        es:'¡Diviértete!',  img:'friends',   em:'🎉'},
   ]},

  /* ── 🩺 AT THE DOCTOR ── */
  {id:'at_doctor', name:'At the Doctor', es:'En el médico', icon:'🩺', color:'wc-body', lvl:3, kind:'words',
   story:'En la Clínica Amiga aprendemos palabras de la salud para hablar con el doctor.',
   items:[
    {en:'Doctor',     es:'Doctor',  img:'doctor',      em:'🩺'},
    {en:'Nurse',      es:'Enfermera',img:'nurse',      em:'💉'},
    {en:'Medicine',   es:'Medicina',img:'medicine',    em:'💊'},
    {en:'Bandage',    es:'Curita',  img:'bandage',     em:'🩹'},
    {en:'Syringe',    es:'Jeringa', img:'syringe',     em:'💉'},
    {en:'Thermometer',es:'Termómetro',img:'thermometer',em:'🌡️'},
    {en:'Rest',       es:'Descansar',img:'kid_sleep',  em:'🛌'},
    {en:'Healthy',    es:'Saludable',img:'apple',      em:'💪'},
    {en:'Ambulance',  es:'Ambulancia',img:'ambulance', em:'🚑'},
    {en:'Sick',       es:'Enfermo', img:'face_sick',   em:'🤒'},
   ]},

  /* ── 🏖️ AT THE BEACH ── */
  {id:'at_beach', name:'At the Beach', es:'En la playa', icon:'🏖️', color:'wc-ocean', lvl:3, kind:'words',
   story:'En la Playa Mágica aprendemos todo lo que ves y haces en un día de sol.',
   items:[
    {en:'Sand',     es:'Arena',            img:'sand',          em:'🏖️'},
    {en:'Wave',     es:'Ola',              img:'wave',          em:'🌊'},
    {en:'Sunscreen',es:'Bloqueador solar', img:'sunscreen',     em:'🧴'},
    {en:'Towel',    es:'Toalla',           img:'towel',         em:'🧺'},
    {en:'Umbrella', es:'Sombrilla',        img:'beachumbrella', em:'⛱️'},
    {en:'Shell',    es:'Concha marina',    img:'seashell',      em:'🐚'},
    {en:'Swimsuit', es:'Traje de baño',    img:'swimsuit',      em:'🩱'},
    {en:'Ice cream',es:'Helado',           img:'icecream',      em:'🍦'},
    {en:'Crab',     es:'Cangrejo',         img:'crab',          em:'🦀'},
    {en:'Sun hat',  es:'Sombrero de sol',  img:'sunhat',        em:'👒'},
   ]},

  /* ── ⛺ CAMPING ── */
  {id:'camping', name:'Camping!', es:'De campamento', icon:'⛺', color:'wc-animals', lvl:3, kind:'words',
   story:'En la Aventura del Bosque aprendemos palabras del campamento bajo las estrellas.',
   items:[
    {en:'Tent',        es:'Carpa',           img:'tent',        em:'⛺'},
    {en:'Campfire',    es:'Fogata',          img:'campfire',    em:'🔥'},
    {en:'Backpack',    es:'Mochila',         img:'backpack',    em:'🎒'},
    {en:'Map',         es:'Mapa',            img:'map',         em:'🗺️'},
    {en:'Flashlight',  es:'Linterna',        img:'flashlight',  em:'🔦'},
    {en:'Sleeping bag',es:'Bolsa de dormir', img:'sleepingbag', em:'🥱'},
    {en:'Insect',      es:'Insecto',         img:'caterpillar', em:'🐛'},
    {en:'Stars',       es:'Estrellas',       img:'star',        em:'✨'},
    {en:'Trail',       es:'Sendero',         img:'boot',        em:'🥾'},
    {en:'Campsite',    es:'Campamento',      img:'jungle',      em:'🌲'},
   ]},

  /* ── 🎭 HOW DO YOU FEEL? ── */
  {id:'feelings_situations', name:'How do you feel?', es:'¿Cómo te sientes?', icon:'🎭', color:'wc-phrases', lvl:3, kind:'phrases',
   story:'En el Teatro de Emociones practicamos frases para contar cómo nos sentimos.',
   items:[
    {en:'I am happy!', es:'¡Estoy feliz!',   img:'face_happy',  em:'😄'},
    {en:'I am tired.', es:'Estoy cansado.',  img:'face_sleepy', em:'😴'},
    {en:'I am hungry!',es:'¡Tengo hambre!',  img:'kid_eat',     em:'🍽️'},
    {en:'I am scared.',es:'Tengo miedo.',    img:'face_scared', em:'😱'},
    {en:'I need help!',es:'¡Necesito ayuda!',img:'raisedhand',  em:'🆘'},
    {en:'I want water!',es:'¡Quiero agua!',  img:'water',       em:'💧'},
    {en:'I love you!', es:'¡Te quiero!',     img:'hearthands',  em:'❤️'},
    {en:'I am sorry.', es:'Lo siento.',      img:'face_sad',    em:'😔'},
    {en:'I am bored.', es:'Estoy aburrido.', img:'face_bored',  em:'🥱'},
    {en:"Let's play!", es:'¡Vamos a jugar!', img:'friends',     em:'🎮'},
   ]},

  /* ── 🎪 THE CIRCUS ── */
  {id:'circus_fun', name:'The Circus!', es:'¡El Circo!', icon:'🎪', color:'wc-words', lvl:3, kind:'words',
   story:'Bajo la gran carpa del circo aprendemos las palabras más divertidas del espectáculo.',
   items:[
    {en:'Clown',    es:'Payaso',            img:'clown',   em:'🤡'},
    {en:'Acrobat',  es:'Acróbata',          img:'kid_jump',em:'🤸'},
    {en:'Magician', es:'Mago',              img:'wand',    em:'🪄'},
    {en:'Juggle',   es:'Malabarismo',       img:'ball',    em:'🎪'},
    {en:'Elephant', es:'Elefante',          img:'elephant',em:'🐘'},
    {en:'Lion',     es:'León',              img:'lion',    em:'🦁'},
    {en:'Popcorn',  es:'Palomitas',         img:'popcorn', em:'🍿'},
    {en:'Ticket',   es:'Entrada',           img:'ticket',  em:'🎟️'},
    {en:'Spotlight',es:'Reflector',         img:'lamp',    em:'💡'},
    {en:'Applause', es:'Aplausos',          img:'clapping',em:'👏'},
   ]},

  /* ── 🎊 SPECIAL DAYS ── */
  {id:'special_events', name:'Special Days', es:'Días especiales', icon:'🎊', color:'wc-food', lvl:3, kind:'words',
   story:'En el Calendario Mágico aprendemos palabras de los días más especiales del año.',
   items:[
    {en:'Christmas',es:'Navidad',            img:'christmastree',em:'🎄'},
    {en:'New Year', es:'Año Nuevo',          img:'calendar',     em:'🥂'},
    {en:'Halloween',es:'Halloween',          img:'pumpkin',      em:'🎃'},
    {en:'Easter',   es:'Pascua',             img:'chick',        em:'🐣'},
    {en:'Carnival', es:'Carnaval',           img:'mask',         em:'🎭'},
    {en:'Holiday',  es:'Vacaciones',         img:'airplane',     em:'✈️'},
    {en:'Festival', es:'Festival',           img:'confetti',     em:'🎡'},
    {en:'Fireworks',es:'Fuegos artificiales',img:'fireworks',    em:'🎆'},
    {en:'Gift',     es:'Regalo',             img:'gift',         em:'🎀'},
    {en:'Candle',   es:'Vela',               img:'candle',       em:'🕯️'},
   ]},

  /* ── 🍽️ FOOD TALK ── */
  {id:'food_phrases', name:'Food Talk', es:'Hablar de comida', icon:'🍽️', color:'wc-food', lvl:3, kind:'phrases',
   story:'En el Restaurante Inglés aprendemos frases cortas para pedir y hablar de comida.',
   items:[
    {en:'I want a pizza!',  es:'¡Quiero una pizza!', img:'pizza',      em:'🍕'},
    {en:'It is delicious!', es:'¡Está delicioso!',   img:'kid_eat',    em:'😋'},
    {en:'I am full.',       es:'Estoy lleno.',       img:'face_calm',  em:'😌'},
    {en:'More please!',     es:'¡Más por favor!',    img:'openhands',  em:'🙏'},
    {en:'It is too spicy!', es:'¡Está muy picante!', img:'chili',      em:'🌶️'},
    {en:'I do not like it.',es:'No me gusta.',       img:'thumbsdown', em:'🙅'},
    {en:'Yummy!',           es:'¡Ñami!',             img:'icecream',   em:'🤤'},
    {en:'I love tacos!',    es:'¡Amo los tacos!',    img:'taco',       em:'🌮'},
    {en:"Let's eat!",       es:'¡A comer!',          img:'family',     em:'🍽️'},
    {en:'Can I have juice?',es:'¿Me das un jugo?',   img:'juice',      em:'🥤'},
   ]},

  /* ── 🌤️ WEATHER TALK ── */
  {id:'weather_talk', name:'Weather Talk', es:'Hablar del clima', icon:'🌤️', color:'wc-weather', lvl:3, kind:'phrases',
   story:'En la Estación Meteorológica aprendemos frases para hablar del tiempo que hace hoy.',
   items:[
    {en:'It is sunny!',    es:'¡Hay sol!',        img:'sun',     em:'☀️'},
    {en:'It is raining.',  es:'Está lloviendo.',  img:'rain',    em:'🌧️'},
    {en:'It is cold!',     es:'¡Hace frío!',      img:'ice',     em:'🥶'},
    {en:'It is hot!',      es:'¡Hace calor!',     img:'desert',  em:'🥵'},
    {en:'It is windy.',    es:'Hay viento.',      img:'kite',    em:'💨'},
    {en:'I see a rainbow!',es:'¡Veo un arcoíris!',img:'rainbow', em:'🌈'},
    {en:'It is snowing!',  es:'¡Está nevando!',   img:'snow',    em:'❄️'},
    {en:'Take a jacket!',  es:'¡Lleva chaqueta!', img:'jacket',  em:'🧥'},
    {en:'It is cloudy.',   es:'Está nublado.',    img:'cloud',   em:'☁️'},
    {en:'It is warm!',     es:'¡Está templado!',  img:'sunrise', em:'🌤️'},
   ]},

  /* ── 📚 IN CLASS ── */
  {id:'school_phrases', name:'In Class!', es:'En clase', icon:'📚', color:'wc-school', lvl:3, kind:'phrases',
   story:'En el Aula Bilingüe practicamos las frases más usadas en el salón de clases.',
   items:[
    {en:'Open your book!', es:'¡Abre tu libro!',    img:'book',      em:'📖'},
    {en:'Sit down, please.',es:'Siéntate, por favor.',img:'chair',  em:'🪑'},
    {en:'Raise your hand!',es:'¡Levanta la mano!',  img:'raisedhand',em:'🙋'},
    {en:'Good job!',       es:'¡Buen trabajo!',     img:'thumbsup',  em:'👍'},
    {en:"Let's learn!",    es:'¡Vamos a aprender!', img:'school',    em:'🧠'},
    {en:'Pay attention!',  es:'¡Presta atención!',  img:'eye',       em:'👀'},
    {en:'Read!',           es:'¡Lee!',              img:'kid_read',  em:'📖'},
    {en:'Write!',          es:'¡Escribe!',          img:'pencil',    em:'✏️'},
    {en:'Draw!',           es:'¡Dibuja!',           img:'crayons',   em:'🖍️'},
    {en:'Listen!',         es:'¡Escucha!',          img:'ear',       em:'👂'},
   ]},
);
